import type { Topic } from "@/lib/types";

export const modernFinalPack: Topic = {
  id: "modern-final-pack",
  title: "Modern — Final Pack",
  summary: "Final MCQs on modern Orthodox issues.",
  learningObjectives: ["Drill the modern landscape."],
  primarySources: ["Contemporary synodal documents"],
  items: [
    {
      id: "mod-fin-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["paris-school"],
      prompt: "What was the 'Paris School' of Russian Orthodox theology in the 20th century?",
      choices: [
        { id: "a", text: "Émigré theologians at St. Sergius Institute, Paris (1925 onward): Bulgakov, Lossky, Florovsky, Afanasiev, Evdokimov, Schmemann, Meyendorff. Shaped much of modern Orthodox theology in the West.", rationale: "Correct." },
        { id: "b", text: "A school in 12th-c. Constantinople" },
        { id: "c", text: "A medieval Western mystical movement" },
        { id: "d", text: "A non-Orthodox group" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Various histories of 20th-c. Russian theology" }],
    },
    {
      id: "mod-fin-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["st-vladimirs"],
      prompt: "What is St. Vladimir's Orthodox Theological Seminary?",
      choices: [
        { id: "a", text: "An Orthodox seminary in Yonkers, NY (since 1938), associated with the OCA. Schmemann, Meyendorff, Hopko taught there.", rationale: "Correct." },
        { id: "b", text: "A Russian Orthodox church in Moscow" },
        { id: "c", text: "A Vatican commission" },
        { id: "d", text: "An Athonite monastery" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "St. Vladimir's Seminary website and history" }],
    },
    {
      id: "mod-fin-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["holy-trinity-seminary"],
      prompt: "What is Holy Trinity Orthodox Seminary?",
      choices: [
        { id: "a", text: "The seminary of the Russian Church Abroad (ROCOR) at Jordanville, NY (since 1948), more traditional in style than St. Vladimir's.", rationale: "Correct." },
        { id: "b", text: "An Antiochian seminary" },
        { id: "c", text: "A Greek institute in Athens" },
        { id: "d", text: "A Vatican institution" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Holy Trinity Seminary, Jordanville, NY" }],
    },
    {
      id: "mod-fin-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["crete-2016"],
      prompt: "What was the 'Holy and Great Council of Crete' (June 2016)?",
      choices: [
        { id: "a", text: "A pan-Orthodox synod long-prepared, finally meeting on Crete; attended by 10 of 14 autocephalous Churches (Russia, Antioch, Bulgaria, Georgia did not attend). Its documents (on ecumenism, marriage, fasting, etc.) are debated; not all jurisdictions have received them.", rationale: "Correct." },
        { id: "b", text: "A Vatican council" },
        { id: "c", text: "A meeting between Lutherans and Orthodox" },
        { id: "d", text: "A condemnation of Pope Francis" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Holy and Great Council, Crete, June 2016 — documents online" }],
    },
    {
      id: "mod-fin-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["jordanville-typikon"],
      prompt: "What is 'Sergianism' in current Russian Orthodox discourse?",
      choices: [
        { id: "a", text: "Originally: Met. Sergius's 1927 submission to Soviet power. Today: broader code-word for ecclesiastical compromise with secular state power; traditionalists charge contemporary Russian Church leadership with renewed Sergianism in their relationship to the Russian state.", rationale: "Correct." },
        { id: "b", text: "Following St. Sergius of Radonezh" },
        { id: "c", text: "A liturgical school" },
        { id: "d", text: "A reformed monastic order" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Various traditionalist publications" }],
    },
  ],
};
