import type { Topic } from "@/lib/types";

export const modernFactsPack: Topic = {
  id: "modern-facts-pack",
  title: "Modern Issues — Quick Recall",
  summary: "MCQ pack on modern Orthodox issues and global situation.",
  learningObjectives: ["Drill the modern landscape."],
  primarySources: ["Various contemporary synodal documents"],
  items: [
    {
      id: "mod-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["autocephaly"],
      prompt: "What does 'autocephalous' mean of an Orthodox Church?",
      choices: [
        { id: "a", text: "Self-headed — having its own primate (patriarch, archbishop, metropolitan) and governed by its own synod, in communion with all other Orthodox.", rationale: "Correct." },
        { id: "b", text: "Independent of the Orthodox communion" },
        { id: "c", text: "Under the Pope of Rome" },
        { id: "d", text: "Without bishops" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Orthodox ecclesiology" }],
    },
    {
      id: "mod-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["patriarchates"],
      prompt: "How many autocephalous Orthodox Churches are there today (broadly recognized)?",
      choices: [
        { id: "a", text: "Approximately 14-15, depending on how OCU and OCA are counted.", rationale: "Correct. Constantinople, Alexandria, Antioch, Jerusalem, Russia, Serbia, Romania, Bulgaria, Georgia, Cyprus, Greece, Poland, Albania, Czech Lands and Slovakia, plus OCA (recognized by some) and OCU (recognized by some)." },
        { id: "b", text: "Five — the ancient Pentarchy" },
        { id: "c", text: "Three — Greek, Russian, Antiochian" },
        { id: "d", text: "One — the Ecumenical Patriarchate" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard listing in Orthodox ecumenical sources" }],
    },
    {
      id: "mod-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["ecumenical-patriarch"],
      prompt: "Where does the Ecumenical Patriarch reside today?",
      choices: [
        { id: "a", text: "At the Phanar in Istanbul (Constantinople), Turkey", rationale: "Correct." },
        { id: "b", text: "In Athens" },
        { id: "c", text: "In Moscow" },
        { id: "d", text: "On Mount Athos" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Ecumenical Patriarchate of Constantinople — patriarchate.org" }],
    },
    {
      id: "mod-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["athos"],
      prompt: "Mount Athos is a self-governing monastic republic on what peninsula?",
      choices: [
        { id: "a", text: "The eastern (Mount Athos) finger of the Chalkidiki Peninsula in northern Greece.", rationale: "Correct. 20 sovereign monasteries + sketes; women forbidden ('Avaton') by ancient typikon." },
        { id: "b", text: "Crete" },
        { id: "c", text: "The Black Sea coast of Russia" },
        { id: "d", text: "Cyprus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hagioritic Typikon (since AD 972)" }],
    },
    {
      id: "mod-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["athos", "20-monasteries"],
      prompt: "How many ruling monasteries are on Mount Athos?",
      choices: [
        { id: "a", text: "Twenty (17 Greek, 1 Russian, 1 Serbian, 1 Bulgarian)", rationale: "Correct." },
        { id: "b", text: "Ten" },
        { id: "c", text: "Forty" },
        { id: "d", text: "Five" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hagioritic Typikon" }],
    },
    {
      id: "mod-fp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["holy-synod"],
      prompt: "What is the Holy Synod of the Russian Orthodox Church today?",
      choices: [
        { id: "a", text: "The supreme governing council, chaired by the Patriarch of Moscow, with permanent members (the Metropolitans of Kyiv-deprecated, Krutitsy, etc.) and rotating ones.", rationale: "Correct." },
        { id: "b", text: "An advisory committee of laymen" },
        { id: "c", text: "An ecumenical body for inter-Orthodox dialogue" },
        { id: "d", text: "A historical body abolished by Peter the Great" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Statute of the Russian Orthodox Church (2000, amended)" }],
    },
  ],
};
