import type { Topic } from "@/lib/types";

export const ldsFinalPack: Topic = {
  id: "lds-final-pack",
  title: "LDS Final Drill Pack",
  summary: "Final MCQ pack on LDS distinctives and history.",
  learningObjectives: ["Drill remaining LDS topics."],
  primarySources: ["Joseph Smith Papers; LDS scripture"],
  items: [
    {
      id: "lds-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["nephites-lamanites"],
      prompt: "Per the Book of Mormon, who are the 'Lamanites'?",
      choices: [
        { id: "a", text: "Descendants of Laman (Lehi's son) who populated the pre-Columbian Americas — the Book's Introduction was revised in 2007 from 'principal ancestors of the American Indians' to 'among the ancestors,' acknowledging DNA evidence.", rationale: "DNA studies (2000s onward) show Native Americans are of East Asian descent, not Semitic. The 2007 wording change is documented." },
        { id: "b", text: "A lost African tribe descended from Solomon, dispersed by the Babylonian captivity.", rationale: "Wrong. The Book of Mormon places the Lehite migration to America, not Africa. No 'lost African tribe' is in the text." },
        { id: "c", text: "Pre-Columbian Asian peoples who migrated across the Bering land bridge.", rationale: "Wrong, although Asian-origin migration via Beringia IS the actual scholarly consensus on Native American ancestry — but the Book of Mormon says Semitic, not Asian." },
        { id: "d", text: "Early European explorers led by Madoc, the 12th-century Welsh prince.", rationale: "Wrong. Madoc legends are a real 16th-c. claim, but unrelated to the Book of Mormon's Lamanites (who are pre-Columbian Israelites per the text)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Book of Mormon, Introduction (1981 and 2007 editions); LDS Gospel Topics Essay: Book of Mormon and DNA Studies (2014)" }],
    },
    {
      id: "lds-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["jaredites"],
      prompt: "In the Book of Mormon, who are the 'Jaredites'?",
      choices: [
        { id: "a", text: "A pre-Lehite civilization that traveled from the Tower of Babel (~2200 BC) and built a great civilization that destroyed itself in massive wars.", rationale: "Recounted in the Book of Ether. Their final battle is at Cumorah (Ether 15), which the Book of Mormon also names as the place of the Nephite final battle." },
        { id: "b", text: "Descendants of Joseph in Egypt who came to America before the Exodus.", rationale: "Wrong. The Joseph-line descent is the LEHITES (Nephi and his brothers); Jaredites are from Babel, before Joseph." },
        { id: "c", text: "The same people as the Nephites, referred to by an earlier name.", rationale: "Wrong. The Book of Mormon presents them as a distinct, earlier civilization that destroyed itself before the Nephites arrived." },
        { id: "d", text: "The actual historical Mayan civilization, identified by LDS apologetic scholarship.", rationale: "Wrong, although LDS apologists (FAIR) have proposed various Mesoamerican locations. The Book itself does not identify Mayans by name; mainstream archaeology does not corroborate the identification." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Book of Mormon, Ether 1-15" }],
    },
    {
      id: "lds-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["aaronic-priesthood"],
      prompt: "According to LDS history, who restored the Aaronic Priesthood to Joseph Smith?",
      choices: [
        { id: "a", text: "John the Baptist, on May 15, 1829, in a vision near Harmony, Pennsylvania.", rationale: "Joseph Smith History 1:68-72; D&C 13. The Aaronic Priesthood includes the offices of deacon, teacher, and priest in LDS usage." },
        { id: "b", text: "Peter, James, and John, in a vision a few weeks before.", rationale: "Wrong. P/J/J restored the MELCHIZEDEK Priesthood (higher); John the Baptist restored the AARONIC (lower)." },
        { id: "c", text: "Moses, who appeared to Joseph Smith at the Kirtland Temple in 1836.", rationale: "Wrong. Moses appears in D&C 110 (April 3, 1836, Kirtland Temple), but he restores the keys of the gathering of Israel, not the Aaronic Priesthood." },
        { id: "d", text: "Elijah the Prophet, who restored the sealing keys.", rationale: "Wrong. Elijah appears (per D&C 110) restoring SEALING keys at the Kirtland Temple, not the Aaronic Priesthood." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Joseph Smith History 1:68-72; D&C 13" }],
    },
    {
      id: "lds-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["melchizedek-priesthood"],
      prompt: "According to LDS history, who restored the Melchizedek Priesthood to Joseph Smith?",
      choices: [
        { id: "a", text: "Peter, James, and John, sometime in 1829 (the exact date is uncertain in early Joseph Smith records).", rationale: "D&C 27:12; D&C 128:20. Joseph Smith's accounts of the event vary and the precise date and location are debated." },
        { id: "b", text: "John the Baptist, just after he restored the Aaronic Priesthood.", rationale: "Wrong. John the Baptist restored only the AARONIC. P/J/J restored the Melchizedek." },
        { id: "c", text: "An angel called Moroni, in the same vision that revealed the gold plates.", rationale: "Wrong. Moroni revealed the location of the plates; the priesthood restorations are separate events." },
        { id: "d", text: "Adam himself, in an 1833 vision at Adam-ondi-Ahman.", rationale: "Wrong. Adam-ondi-Ahman IS a real LDS site (in Missouri) and Adam is venerated in LDS theology, but the Melchizedek restoration is attributed to P/J/J." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "D&C 27:12; D&C 128:20" }],
    },
    {
      id: "lds-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["kinderhook"],
      prompt: "What are the 'Kinderhook plates'?",
      choices: [
        { id: "a", text: "Six brass plates manufactured by Illinois locals (1843) and presented to Joseph Smith to test his translation gift.", rationale: "Smith began translation; the plates were exposed as a 19th-c. forgery by 1980 metallurgical analysis (Ensign August 1981, Stanley Kimball)." },
        { id: "b", text: "Original Book of Mormon manuscripts dictated by Joseph Smith in 1829.", rationale: "Wrong. Those are the Original Manuscript and Printer's Manuscript of the Book of Mormon — preserved in part. Kinderhook is a separate hoax." },
        { id: "c", text: "The original brass plates of Laban from which Nephi obtained the Old Testament.", rationale: "Wrong. The Brass Plates of Laban are an in-text Book of Mormon artifact (1 Nephi 3-4); they were never produced physically. Kinderhook plates were a 19th-c. fake." },
        { id: "d", text: "Egyptian funerary documents purchased by Joseph Smith from Michael Chandler in 1835.", rationale: "Wrong. Those are the JOSEPH SMITH PAPYRI (related to the Book of Abraham). The Kinderhook plates are a different artifact." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Stanley B. Kimball, 'Kinderhook Plates Brought to Joseph Smith Appear to Be a Nineteenth-Century Hoax,' Ensign (August 1981)" }],
    },
    {
      id: "lds-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["ces-letter"],
      prompt: "What is the 'CES Letter' (Letter to a CES Director)?",
      choices: [
        { id: "a", text: "A 2013 document by Jeremy Runnells listing historical and doctrinal concerns about the LDS Church — originally addressed to a Church Education System director.", rationale: "Widely read; the LDS Church has not formally responded. Runnells himself resigned from the LDS Church in 2014." },
        { id: "b", text: "An official LDS Church Education System curriculum document, governing seminary and institute instruction.", rationale: "Wrong. CES IS the real LDS Church Education System, but the 'CES Letter' is a CRITIQUE OF the Church addressed to a CES director — not an official document." },
        { id: "c", text: "An 1830s letter from Joseph Smith to W.W. Phelps explaining the Book of Mormon translation process.", rationale: "Wrong. There IS a real 1832 Smith-Phelps correspondence (the 'Pure Language' letter), but that is not the 'CES Letter.'" },
        { id: "d", text: "A novel by Mormon author Brandon Sanderson exploring religious doubt.", rationale: "Wrong. Sanderson is a real LDS author of fantasy novels but the CES Letter is non-fiction by Runnells." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Jeremy Runnells, Letter to a CES Director (2013, cesletter.org)" }],
    },
  ],
};
