import type { Topic } from "@/lib/types";

export const ldsFinalPack: Topic = {
  id: "lds-final-pack",
  title: "LDS Final Drill Pack",
  summary: "Final MCQ pack on LDS distinctives and history.",
  learningObjectives: ["Drill remaining LDS topics."],
  primarySources: ["Joseph Smith Papers; LDS scripture"],
  items: [
    {
      id: "lds-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["nephites-lamanites"],
      prompt: "Who, per the Book of Mormon, are the 'Lamanites'?",
      choices: [
        { id: "a", text: "Descendants of Laman (son of Lehi), said to have populated the pre-Columbian Americas. The Introduction to the Book of Mormon was revised in 2007 from 'principal ancestors of the American Indians' to 'among the ancestors,' acknowledging DNA evidence.", rationale: "Correct." },
        { id: "b", text: "An African tribe" },
        { id: "c", text: "Asians" },
        { id: "d", text: "Europeans" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Book of Mormon, Introduction (1981 and 2007 editions)" }],
    },
    {
      id: "lds-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["jaredites"],
      prompt: "In the Book of Mormon, the 'Jaredites' are a second civilization that:",
      choices: [
        { id: "a", text: "Arrived in the Americas from the Tower of Babel (~2200 BC), built a great civilization, and destroyed itself in massive wars (Book of Ether).", rationale: "Correct. The Book of Ether is internal to the Book of Mormon." },
        { id: "b", text: "Descended from Joseph in Egypt" },
        { id: "c", text: "Are the Nephites under a different name" },
        { id: "d", text: "Are the Maya" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Book of Mormon, Ether" }],
    },
    {
      id: "lds-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["aaronic-priesthood"],
      prompt: "According to LDS history, who restored the Aaronic Priesthood to Joseph Smith?",
      choices: [
        { id: "a", text: "John the Baptist, on May 15, 1829, in a vision near Harmony, Pennsylvania.", rationale: "Correct (per Joseph Smith History 1:68-72)." },
        { id: "b", text: "Peter, James, and John" },
        { id: "c", text: "Moses" },
        { id: "d", text: "Elijah" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Joseph Smith History 1:68-72; D&C 13" }],
    },
    {
      id: "lds-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["melchizedek-priesthood"],
      prompt: "According to LDS history, who restored the Melchizedek Priesthood to Joseph Smith?",
      choices: [
        { id: "a", text: "Peter, James, and John, sometime in 1829.", rationale: "Correct (the exact date is uncertain in early Joseph Smith records)." },
        { id: "b", text: "John the Baptist" },
        { id: "c", text: "An angel called Moroni" },
        { id: "d", text: "Adam" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "D&C 27:12; D&C 128:20" }],
    },
    {
      id: "lds-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["kinderhook"],
      prompt: "What are the 'Kinderhook plates,' and what is their significance for LDS apologetics?",
      choices: [
        { id: "a", text: "Six brass plates planted by a group of Illinois locals (1843) to test Joseph Smith. He attempted to translate them; they were later confirmed as a 19th-century forgery in 1980 metallurgical analysis.", rationale: "Correct. Joseph Smith History records that he had begun a translation; the modern LDS Church has not pursued the matter." },
        { id: "b", text: "Original Book of Mormon manuscripts" },
        { id: "c", text: "The original Aaronic Priesthood plates" },
        { id: "d", text: "Egyptian funerary documents" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Stanley B. Kimball, 'Kinderhook Plates Brought to Joseph Smith Appear to be a Nineteenth-Century Hoax,' Ensign (August 1981)" }],
    },
    {
      id: "lds-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["ces-letter"],
      prompt: "What is the 'CES Letter' (Letter to a CES Director)?",
      choices: [
        { id: "a", text: "A 2013 document by Jeremy Runnells, originally addressed to a Church Education System director, cataloguing his historical and doctrinal concerns about the LDS Church. Widely read; the LDS Church has not formally responded.", rationale: "Correct." },
        { id: "b", text: "An official LDS document" },
        { id: "c", text: "A 19th-c. revelation" },
        { id: "d", text: "A novel" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Jeremy Runnells, Letter to a CES Director (2013, online)" }],
    },
  ],
};
