import type { Topic } from "@/lib/types";

export const ldsHistoryPack: Topic = {
  id: "lds-history-pack",
  title: "LDS History — Quick Facts",
  summary: "Key dates and figures in LDS history.",
  learningObjectives: ["Drill the basic LDS timeline."],
  primarySources: ["Joseph Smith Papers; LDS Church History"],
  items: [
    {
      id: "lds-hp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["joseph-smith"],
      prompt: "When and where was the LDS Church founded by Joseph Smith?",
      choices: [
        { id: "a", text: "April 6, 1830, in Fayette, NY — at the home of Peter Whitmer Sr.", rationale: "Six original members (D&C 20). The date is annually commemorated; one of three LDS sub-traditions claims a Manchester, NY founding instead." },
        { id: "b", text: "March 26, 1820, in the Sacred Grove near Palmyra — the First Vision.", rationale: "Wrong. The First Vision (~1820) is reported as the call; the CHURCH was organized later, April 1830." },
        { id: "c", text: "September 22, 1827, on the Hill Cumorah — when the gold plates were given to Smith.", rationale: "Wrong. The reception of the plates is dated September 22, 1827, but is NOT the founding of the Church (organized 1830)." },
        { id: "d", text: "July 24, 1847, at the Great Salt Lake — 'This is the place,' Brigham Young's settlement.", rationale: "Wrong. July 24, 1847 is the Utah founding ('Pioneer Day') under Brigham Young — seventeen years AFTER the Church's organization." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Joseph Smith History 1; D&C 21" }],
    },
    {
      id: "lds-hp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["joseph-smith", "death"],
      prompt: "When and how did Joseph Smith die?",
      choices: [
        { id: "a", text: "Killed by a mob at Carthage Jail, Illinois, on June 27, 1844 — age 38, with his brother Hyrum.", rationale: "He had been jailed on charges of treason and inciting a riot (relating to the destruction of the Nauvoo Expositor newspaper). The mob stormed the jail; Joseph was shot." },
        { id: "b", text: "Natural causes at Nauvoo, IL in 1846, after handing leadership to Brigham Young.", rationale: "Wrong. Joseph Smith was murdered in 1844; Young led the succession crisis after his death." },
        { id: "c", text: "Drowned during a baptism in the Mississippi River in 1842.", rationale: "Wrong. He performed many baptisms in the Mississippi but did not die there." },
        { id: "d", text: "Assassinated by a Danite faction during the 1838 Mormon-Missouri War.", rationale: "Wrong. The Danites were a real Mormon paramilitary in 1838 Missouri, and the war was real, but Joseph survived it and died six years later at Carthage." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "B.H. Roberts, Comprehensive History of the Church II" }],
    },
    {
      id: "lds-hp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["brigham-young", "utah"],
      prompt: "Who led the LDS migration to the Salt Lake Valley, and when did they arrive?",
      choices: [
        { id: "a", text: "Brigham Young, July 24, 1847 — annually celebrated in Utah as 'Pioneer Day.'", rationale: "Young led the pioneer company from winter quarters in Nebraska after the 1846 expulsion from Nauvoo." },
        { id: "b", text: "Sidney Rigdon, in 1845, after his rejection by the Twelve Apostles.", rationale: "Wrong. Rigdon DID lead a splinter group (which became the precursor to the Bickertonite branch) but did not lead the main Utah migration; that was Young." },
        { id: "c", text: "John Taylor, the third LDS President, in 1850.", rationale: "Wrong. Taylor was the third LDS President (1880-1887), but he did not lead the original Utah migration; Brigham Young did." },
        { id: "d", text: "Joseph Smith III, the son of the founder, leading the Reorganized Church westward in 1860.", rationale: "Wrong. Joseph Smith III led the Reorganized Church (later Community of Christ) but STAYED in the Midwest, not Utah." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "B.H. Roberts, Comprehensive History of the Church III-IV" }],
    },
    {
      id: "lds-hp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["d-and-c"],
      prompt: "What is the LDS Doctrine and Covenants (D&C)?",
      choices: [
        { id: "a", text: "A collection of 138 revelations + 2 Official Declarations attributed to Joseph Smith and his successors — considered scripture alongside the Bible and the Book of Mormon.", rationale: "First published 1835 as Book of Commandments (1833). Includes the controversial Section 132 on plural marriage." },
        { id: "b", text: "The original 1830 edition of the Book of Mormon, before later editorial revisions.", rationale: "Wrong. The Book of Mormon and the D&C are distinct LDS scriptures, both extant in 1830s." },
        { id: "c", text: "The LDS priesthood handbook, governing the duties of bishops and stake presidents.", rationale: "Wrong. The Church Handbook of Instructions IS a real LDS document, but the D&C is canonical scripture, not a manual." },
        { id: "d", text: "Joseph Smith's translation of the Egyptian Book of Abraham papyri.", rationale: "Wrong. That is the BOOK OF ABRAHAM (in the Pearl of Great Price), a different LDS scripture." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Doctrine and Covenants (1835; current edition has 138 sections + 2 Declarations)" }],
    },
    {
      id: "lds-hp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["pearl-of-great-price"],
      prompt: "What works comprise the Pearl of Great Price (LDS scripture)?",
      choices: [
        { id: "a", text: "Selections from the Book of Moses, the Book of Abraham, Joseph Smith-Matthew, Joseph Smith-History, and the Articles of Faith.", rationale: "First compiled 1851 by Franklin D. Richards in England; canonized 1880. The Book of Abraham is the focus of the 'Egyptian papyri' controversy." },
        { id: "b", text: "The Book of Mormon's principal sections — 1 Nephi, 2 Nephi, Mosiah, Alma, Helaman.", rationale: "Wrong. Those are sections of the Book of Mormon, not the Pearl of Great Price." },
        { id: "c", text: "The Doctrine and Covenants alone, in its 1835 first edition.", rationale: "Wrong. D&C is a separate LDS scripture from the Pearl of Great Price." },
        { id: "d", text: "Joseph Smith's King Follett Discourse and his Wentworth Letter only.", rationale: "Wrong. The King Follett Discourse (1844) is NOT canonized; the Wentworth Letter (1842) IS the source of the Articles of Faith but only those (not the whole Letter) made it into scripture." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pearl of Great Price (1851 first compilation; canonized 1880)" }],
    },
    {
      id: "lds-hp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["membership"],
      prompt:
        "Approximately how many self-identified Latter-day Saints does the LDS Church report globally (2020s)?",
      choices: [
        { id: "a", text: "About seventeen million (claimed by the Church; sociological research suggests ~30-40% are active).", rationale: "LDS Church statistical reports given at the April General Conference each year. Active rate from independent surveys (Pew, ARIS)." },
        { id: "b", text: "About one million — concentrated in Utah and the Mountain West.", rationale: "Wrong. The LDS Church passed one million worldwide in the 1940s; current claimed membership is ~17 million." },
        { id: "c", text: "About fifty million — making it the third-largest American religion after Catholicism and Baptists.", rationale: "Wrong. LDS is around the 4th-5th largest U.S. religion at ~7 million in the U.S. (subset of the 17 million worldwide)." },
        { id: "d", text: "About two hundred million — comparable to global Anglican Communion membership.", rationale: "Wrong. The Anglican Communion is ~85 million globally; LDS is ~17 million." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "LDS Church Statistical Report (annual April General Conference)" }],
    },
  ],
};
