import type { Topic } from "@/lib/types";

export const ldsHistoryPack: Topic = {
  id: "lds-history-pack",
  title: "LDS History — Quick Facts",
  summary: "Key dates and figures in LDS history.",
  learningObjectives: ["Drill the basic LDS timeline."],
  primarySources: ["Joseph Smith Papers; LDS Church History"],
  items: [
    {
      id: "lds-hp-001",
      kind: "mcq",
      difficulty: 1,
      tags: ["joseph-smith"],
      prompt: "When was the LDS Church founded by Joseph Smith?",
      choices: [
        { id: "a", text: "April 6, 1830, in Fayette, NY", rationale: "Correct." },
        { id: "b", text: "July 24, 1847, in Utah" },
        { id: "c", text: "December 25, 1820" },
        { id: "d", text: "January 1, 1900" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Joseph Smith History 1; D&C 21" }],
    },
    {
      id: "lds-hp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["joseph-smith", "death"],
      prompt: "When and how did Joseph Smith die?",
      choices: [
        { id: "a", text: "Killed by a mob in Carthage Jail, Illinois, on June 27, 1844, age 38.", rationale: "Correct. Together with his brother Hyrum." },
        { id: "b", text: "Natural causes, 1860, in Utah" },
        { id: "c", text: "Lost at sea, 1840" },
        { id: "d", text: "Killed by Brigham Young in 1846" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "B.H. Roberts, Comprehensive History of the Church II" }],
    },
    {
      id: "lds-hp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["brigham-young", "utah"],
      prompt: "Who led the LDS migration to Utah, and when did they arrive?",
      choices: [
        { id: "a", text: "Brigham Young, July 24, 1847 — 'Pioneer Day' in Utah.", rationale: "Correct." },
        { id: "b", text: "Sidney Rigdon, 1845" },
        { id: "c", text: "John Taylor, 1850" },
        { id: "d", text: "Joseph Smith Jr., posthumously" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Various LDS history sources" }],
    },
    {
      id: "lds-hp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["d-and-c"],
      prompt: "What is the Doctrine & Covenants (D&C)?",
      choices: [
        { id: "a", text: "A collection of revelations and historical documents (138 sections + 2 Official Declarations) considered scripture by the LDS Church.", rationale: "Correct." },
        { id: "b", text: "The original 1830 Book of Mormon" },
        { id: "c", text: "The Mormon priesthood manual" },
        { id: "d", text: "The Book of Abraham translation" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Doctrine and Covenants (1835 first edition; current edition)" }],
    },
    {
      id: "lds-hp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["pearl-of-great-price"],
      prompt: "What four works comprise the Pearl of Great Price (LDS scripture)?",
      choices: [
        { id: "a", text: "Moses, Abraham, JS-Matthew, JS-History, plus the Articles of Faith", rationale: "Correct. Selections drawn from Smith's writings and revelations." },
        { id: "b", text: "1 Nephi, 2 Nephi, Mosiah, Alma" },
        { id: "c", text: "Doctrine and Covenants only" },
        { id: "d", text: "King Follett Discourse alone" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pearl of Great Price (1851 / current edition)" }],
    },
    {
      id: "lds-hp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["membership"],
      prompt: "Approximately how many self-identified Latter-day Saints are there globally today (2020s)?",
      choices: [
        { id: "a", text: "~17 million (claimed; active rate much lower)", rationale: "Correct. The LDS Church reports about 17 million members; sociological research suggests active rates around 30-40% of that." },
        { id: "b", text: "~50 million" },
        { id: "c", text: "~1 million" },
        { id: "d", text: "~200 million" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "LDS Church Statistical Report (annual General Conference)" }],
    },
  ],
};
