import type { Topic } from "@/lib/types";

export const sevenCouncilsQuickRecall: Topic = {
  id: "seven-councils-quick",
  title: "Seven Ecumenical Councils — Quick Recall",
  summary: "Year, location, primary heresy addressed, central dogmatic definition.",
  learningObjectives: ["Match each council to its year, heresy, and definition."],
  primarySources: ["Acts of the Seven Ecumenical Councils"],
  items: [
    {
      id: "co-7-001",
      kind: "chronology",
      difficulty: 3,
      tags: ["seven-councils", "chronology"],
      prompt: "Place the seven Ecumenical Councils in chronological order.",
      choices: [
        { id: "a", text: "Nicaea I" },
        { id: "b", text: "Constantinople I" },
        { id: "c", text: "Ephesus" },
        { id: "d", text: "Chalcedon" },
        { id: "e", text: "Constantinople II" },
        { id: "f", text: "Constantinople III" },
        { id: "g", text: "Nicaea II" },
      ],
      correctOrder: ["a", "b", "c", "d", "e", "f", "g"],
      citations: [{ source: "325, 381, 431, 451, 553, 680-1, 787" }],
    },
    {
      id: "co-7-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["nicaea-i"],
      prompt: "Which Ecumenical Council was primarily convoked to address Arianism?",
      choices: [
        { id: "a", text: "Nicaea I (325) — under Constantine, presided by Hosius of Cordoba.", rationale: "318 Fathers; defined homoousios; promulgated the first part of the Symbol of Faith and 20 canons." },
        { id: "b", text: "Constantinople I (381) — under Theodosius I, addressing the Pneumatomachi.", rationale: "Wrong. Constantinople I addressed the Pneumatomachi (Spirit-fighters) and completed the Symbol. Arianism was first condemned at Nicaea I, 56 years earlier." },
        { id: "c", text: "Ephesus (431) — under Theodosius II, addressing Nestorianism.", rationale: "Wrong. Ephesus addressed Nestorius's refusal of Theotokos. Arianism was a century earlier." },
        { id: "d", text: "Chalcedon (451) — under Marcian, addressing Eutychian Monophysitism.", rationale: "Wrong. Chalcedon addressed Eutyches. Arianism is Nicaea I." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Nicaea I (325)" }],
    },
    {
      id: "co-7-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["ephesus"],
      prompt: "Which Ecumenical Council dogmatically affirmed the title Theotokos?",
      choices: [
        { id: "a", text: "Ephesus (431) — under Cyril of Alexandria's presidency.", rationale: "Nestorius had refused the title; Cyril's First Letter and Twelve Anathemas were ratified at Ephesus." },
        { id: "b", text: "Nicaea I (325) — which produced the original Symbol of Faith.", rationale: "Wrong. Nicaea I addressed Arianism; the Symbol mentions the Virgin only briefly. The dogmatic AFFIRMATION of Theotokos is Ephesus 431." },
        { id: "c", text: "Constantinople I (381) — which completed the Symbol of Faith.", rationale: "Wrong. Constantinople I completed the Pneumatology; the Theotokos affirmation is Ephesus 431." },
        { id: "d", text: "Nicaea II (787) — which restored the icons.", rationale: "Wrong. Nicaea II addressed iconoclasm; the Theotokos title was settled four centuries earlier at Ephesus." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Ephesus (431)" }],
    },
    {
      id: "co-7-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["constantinople-iii"],
      prompt: "Which Ecumenical Council condemned Monothelitism?",
      choices: [
        { id: "a", text: "Constantinople III (680-681) — vindicated St. Maximus the Confessor posthumously.", rationale: "Defined two wills and two operations in Christ. Condemned Pope Honorius I by name (Session 13)." },
        { id: "b", text: "Constantinople II (553) — under Justinian, addressed the Three Chapters and Origenism.", rationale: "Wrong. Constantinople II addressed the Three Chapters; the monothelite condemnation came at the THIRD Constantinople council (681)." },
        { id: "c", text: "Nicaea II (787) — restored the icons.", rationale: "Wrong. Nicaea II addressed iconoclasm; monothelitism was condemned a century earlier." },
        { id: "d", text: "Lateran I (1123) — a medieval Western council.", rationale: "Wrong, and not an Orthodox-received council. Constantinople III (681) condemned monothelitism." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople III (681)" }],
    },
    {
      id: "co-7-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["nicaea-ii"],
      prompt: "Which Ecumenical Council restored the veneration of icons?",
      choices: [
        { id: "a", text: "Nicaea II (787) — under Empress Irene; 350+ Fathers; condemned iconoclasm.", rationale: "Definition: 'The honor paid to the image passes on to that which the image represents.' Distinguished proskynesis from latreia." },
        { id: "b", text: "Constantinople III (680-681) — vindicated St. Maximus the Confessor.", rationale: "Wrong. Constantinople III addressed monothelitism; iconoclasm was condemned a century later." },
        { id: "c", text: "The Council in Trullo / Quinisext (692) — 102 canons supplementing V and VI.", rationale: "Wrong. Trullo is disciplinary; iconoclasm did not yet exist (it begins 726). Nicaea II (787) is the icon council." },
        { id: "d", text: "The Photian Council / Constantinople IV (879-880) — anti-Filioque.", rationale: "Wrong. Photian council addressed Filioque; iconoclasm had been settled a century earlier at Nicaea II." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Nicaea II (787)" }],
    },
    {
      id: "co-7-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedon"],
      prompt: "Approximately how many Fathers attended the Council of Chalcedon (451), by Orthodox tradition?",
      choices: [
        { id: "a", text: "150 — the count of Constantinople I (381).", rationale: "Wrong. 150 is the Constantinople I count. Chalcedon's count is 630." },
        { id: "b", text: "318 — the count of Nicaea I (325).", rationale: "Wrong. 318 is the Nicene count (symbolic of Gen 14:14). Chalcedon is 630." },
        { id: "c", text: "630 — by Orthodox tradition; the largest of the seven Ecumenical Councils.", rationale: "Synaxarion, Sunday of the Fathers of the Fourth Council. Modern historians estimate 500-600+." },
        { id: "d", text: "Over 1000 — including all the local Egyptian bishops who supported Dioscorus.", rationale: "Wrong. The Egyptian bishops did NOT all support Chalcedon (the schism with the Coptic Church begins here). Total is ~630." },
      ],
      correctChoiceId: "c",
      citations: [{ source: "Synaxarion, Sunday of the Fathers of the Fourth Council" }],
    },
  ],
};

export const synodicon: Topic = {
  id: "synodicon",
  title: "The Synodikon of Orthodoxy",
  summary: "Read each year on the First Sunday of Great Lent (the Triumph of Orthodoxy). Contains the conciliar anathemas against the major heresies and the proclamation of the holy icons and the Orthodox confession.",
  learningObjectives: ["Identify when the Synodikon is read.", "Note its dogmatic role."],
  primarySources: ["Synodikon of Orthodoxy (March 843 base + later additions)"],
  items: [
    {
      id: "co-syn-001",
      kind: "qa",
      difficulty: 3,
      tags: ["synodikon"],
      prompt: "What is the Synodikon of Orthodoxy, and when is it read?",
      expectedAnswer: "The Synodikon is a liturgical text containing the Orthodox confession of faith, the memorial of the holy Fathers and Confessors, and the anathemas against the principal heresies (Arianism, Iconoclasm, Origenism, Apollinarianism, the Filioque, anti-Palamism, etc.). Its core dates from March 843 (the Triumph of Orthodoxy) and was expanded over subsequent centuries (especially by the Hesychast Synods of 1341-51). It is read every year at the Liturgy on the First Sunday of Great Lent, the 'Sunday of Orthodoxy.'",
      citations: [{ source: "Synodikon of Orthodoxy — Triumph of Orthodoxy" }],
    },
  ],
};
