import type { Topic } from "@/lib/types";

export const councilsDetail: Topic = {
  id: "councils-detail-mcq",
  title: "Councils — Quick Recall Pack 2",
  summary: "More MCQs on the seven councils and key local councils.",
  learningObjectives: ["Drill the details."],
  primarySources: ["Acts of the Seven Councils"],
  items: [
    {
      id: "co-d2-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["nicaea-i", "fathers"],
      prompt: "Approximately how many Fathers attended Nicaea I (325)?",
      choices: [
        { id: "a", text: "318 (by Orthodox tradition; cf. Gen 14:14)", rationale: "Correct." },
        { id: "b", text: "150" },
        { id: "c", text: "200" },
        { id: "d", text: "630" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, Sunday of the Fathers of the First Ecumenical Council" }],
    },
    {
      id: "co-d2-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["constantinople-i", "fathers"],
      prompt: "Approximately how many Fathers attended Constantinople I (381)?",
      choices: [
        { id: "a", text: "150 (by Orthodox tradition)", rationale: "Correct." },
        { id: "b", text: "318" },
        { id: "c", text: "200" },
        { id: "d", text: "300" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, Sunday of the Fathers of the Second Council" }],
    },
    {
      id: "co-d2-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedon", "creed"],
      prompt: "What is the 'Chalcedonian Definition'?",
      choices: [
        { id: "a", text: "The dogmatic statement of Chalcedon 451 affirming two natures (divine and human) in one Person, 'inconfusedly, unchangeably, indivisibly, inseparably.'", rationale: "Correct." },
        { id: "b", text: "A list of canons" },
        { id: "c", text: "The Symbol of Faith" },
        { id: "d", text: "The Tome of Leo" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Chalcedon (451)" }],
    },
    {
      id: "co-d2-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["origenism"],
      prompt: "Constantinople II (553) anathematized fifteen propositions of which earlier author?",
      choices: [
        { id: "a", text: "Origen", rationale: "Correct. The Origenist controversies of the 5th-6th centuries." },
        { id: "b", text: "Tertullian" },
        { id: "c", text: "Augustine" },
        { id: "d", text: "Theodore of Mopsuestia" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople II (553), Anathemas Against Origen" }],
    },
    {
      id: "co-d2-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["pope-honorius"],
      prompt: "Constantinople III (681) condemned which Pope by name?",
      choices: [
        { id: "a", text: "Honorius I, for monothelitism", rationale: "Correct. The decisive counterexample to Vatican I." },
        { id: "b", text: "Liberius" },
        { id: "c", text: "Vigilius" },
        { id: "d", text: "Eugene IV" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople III, Session 13" }],
    },
    {
      id: "co-d2-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["irene"],
      prompt: "Who convoked Nicaea II (787)?",
      choices: [
        { id: "a", text: "Empress Irene with her son Constantine VI", rationale: "Correct." },
        { id: "b", text: "Justinian I" },
        { id: "c", text: "Charlemagne" },
        { id: "d", text: "Theodora" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Nicaea II (787)" }],
    },
  ],
};
