import type { Topic } from "@/lib/types";

export const sevenCouncilsQuickRecall: Topic = {
  id: "seven-councils-quick",
  title: "Seven Ecumenical Councils — Quick Recall",
  summary: "Year, location, primary heresy addressed, central dogmatic definition.",
  learningObjectives: ["Match each council to its year, heresy, and definition."],
  primarySources: ["Acts of the Seven Ecumenical Councils"],
  items: [
    {
      id: "co-7-001",
      kind: "chronology",
      difficulty: 3,
      tags: ["seven-councils", "chronology"],
      prompt: "Place the seven Ecumenical Councils in chronological order.",
      choices: [
        { id: "a", text: "Nicaea I" },
        { id: "b", text: "Constantinople I" },
        { id: "c", text: "Ephesus" },
        { id: "d", text: "Chalcedon" },
        { id: "e", text: "Constantinople II" },
        { id: "f", text: "Constantinople III" },
        { id: "g", text: "Nicaea II" },
      ],
      correctOrder: ["a", "b", "c", "d", "e", "f", "g"],
      citations: [{ source: "325, 381, 431, 451, 553, 680-1, 787" }],
    },
    {
      id: "co-7-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["nicaea-i"],
      prompt: "Which council addressed Arianism?",
      choices: [
        { id: "a", text: "Nicaea I (325)", rationale: "Correct." },
        { id: "b", text: "Constantinople I (381) — addressed Pneumatomachi" },
        { id: "c", text: "Ephesus (431) — addressed Nestorianism" },
        { id: "d", text: "Chalcedon (451) — addressed Monophysitism" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Nicaea I (325)" }],
    },
    {
      id: "co-7-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["ephesus"],
      prompt: "Which council dogmatically defined the title Theotokos?",
      choices: [
        { id: "a", text: "Nicaea I" },
        { id: "b", text: "Constantinople I" },
        { id: "c", text: "Ephesus (431)", rationale: "Correct." },
        { id: "d", text: "Nicaea II" },
      ],
      correctChoiceId: "c",
      citations: [{ source: "Acts of Ephesus (431)" }],
    },
    {
      id: "co-7-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["constantinople-iii"],
      prompt: "Which council condemned Monothelitism?",
      choices: [
        { id: "a", text: "Constantinople II (553)" },
        { id: "b", text: "Constantinople III (680-1)", rationale: "Correct." },
        { id: "c", text: "Nicaea II (787)" },
        { id: "d", text: "Lateran I (1123) — not Orthodox" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Acts of Constantinople III (681)" }],
    },
    {
      id: "co-7-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["nicaea-ii"],
      prompt: "Which council restored the veneration of icons?",
      choices: [
        { id: "a", text: "Nicaea II (787)", rationale: "Correct." },
        { id: "b", text: "Constantinople III" },
        { id: "c", text: "Trullo" },
        { id: "d", text: "Constantinople IV (Photian)" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Nicaea II (787)" }],
    },
    {
      id: "co-7-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedon"],
      prompt: "How many Fathers attended the Council of Chalcedon (451)?",
      choices: [
        { id: "a", text: "150" },
        { id: "b", text: "318" },
        { id: "c", text: "630 (per Orthodox tradition)", rationale: "Correct." },
        { id: "d", text: "1000+" },
      ],
      correctChoiceId: "c",
      citations: [{ source: "Synaxarion, Sunday of the Fathers of the Fourth Council" }],
    },
  ],
};

export const synodicon: Topic = {
  id: "synodicon",
  title: "The Synodikon of Orthodoxy",
  summary: "Read each year on the First Sunday of Great Lent (the Triumph of Orthodoxy). Contains the conciliar anathemas against the major heresies and the proclamation of the holy icons and the Orthodox confession.",
  learningObjectives: ["Identify when the Synodikon is read.", "Note its dogmatic role."],
  primarySources: ["Synodikon of Orthodoxy (March 843 base + later additions)"],
  items: [
    {
      id: "co-syn-001",
      kind: "qa",
      difficulty: 3,
      tags: ["synodikon"],
      prompt: "What is the Synodikon of Orthodoxy, and when is it read?",
      expectedAnswer: "The Synodikon is a liturgical text containing the Orthodox confession of faith, the memorial of the holy Fathers and Confessors, and the anathemas against the principal heresies (Arianism, Iconoclasm, Origenism, Apollinarianism, the Filioque, anti-Palamism, etc.). Its core dates from March 843 (the Triumph of Orthodoxy) and was expanded over subsequent centuries (especially by the Hesychast Synods of 1341-51). It is read every year at the Liturgy on the First Sunday of Great Lent, the 'Sunday of Orthodoxy.'",
      citations: [{ source: "Synodikon of Orthodoxy — Triumph of Orthodoxy" }],
    },
  ],
};
