import type { Topic } from "@/lib/types";

export const councilsFinalPack: Topic = {
  id: "councils-final-pack",
  title: "Councils — Final Pack",
  summary: "Final MCQs on Ecumenical and important local councils.",
  learningObjectives: ["Master council details."],
  primarySources: ["Acts of the seven councils; Pedalion"],
  items: [
    {
      id: "co-final-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["fathers-feast"],
      prompt:
        "When is the 'Sunday of the Holy Fathers of the First Ecumenical Council' observed in the Orthodox calendar?",
      choices: [
        { id: "a", text: "The Sunday between the Ascension and Pentecost (the Seventh Sunday of Pascha).", rationale: "Honoring the 318 Fathers of Nicaea (325). Two other 'Sundays of Fathers' commemorate the first six councils together (mid-July) and the seven councils together (mid-October)." },
        { id: "b", text: "The First Sunday of Great Lent — the Triumph of Orthodoxy.", rationale: "Wrong. The First Sunday of Lent commemorates the restoration of icons (843), not the Fathers of Nicaea." },
        { id: "c", text: "Holy Saturday — the day Christ rested in the tomb.", rationale: "Wrong. Holy Saturday is Christ's descent into Hades; not a council commemoration." },
        { id: "d", text: "All Saints Sunday — the first Sunday after Pentecost.", rationale: "Wrong. All Saints Sunday (1st after Pentecost) honors all the saints; the Fathers of Nicaea are commemorated the Sunday BEFORE Pentecost." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pentecostarion — Sunday of the Fathers of Nicaea" }],
    },
    {
      id: "co-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedon-canon-28"],
      prompt: "What does canon 28 of Chalcedon (451) decree?",
      choices: [
        { id: "a", text: "Constantinople receives 'equal privileges' (isa presbeia) with Rome and primacy over Pontus, Asia, and Thrace.", rationale: "On the basis that Constantinople is 'New Rome.' The Roman legates protested unsuccessfully; the canon was confirmed by the Council." },
        { id: "b", text: "It promulgates the Definition of Chalcedon affirming the two natures of Christ.", rationale: "Wrong. That is the DEFINITION (a separate dogmatic document), not canon 28 (a disciplinary canon about church order)." },
        { id: "c", text: "It establishes the 40-day Lenten fast as universally binding.", rationale: "Wrong. The Lenten fast was already in place by 451; canon 28 deals with episcopal precedence, not fasting." },
        { id: "d", text: "It formally rejects the Tome of Pope Leo as Nestorian-leaning.", rationale: "Wrong. The Council ACCLAIMED Leo's Tome ('Peter has spoken through Leo!'); canon 28 has nothing to do with rejecting it." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Canon 28 of Chalcedon (451)" }],
    },
    {
      id: "co-final-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["jerusalem-1672"],
      prompt: "What was the Synod of Jerusalem (1672)?",
      choices: [
        { id: "a", text: "An Orthodox synod under Patriarch Dositheus of Jerusalem, refuting the Calvinist 'Confession' attributed to Patriarch Cyril Lucaris.", rationale: "Sometimes called the 'Council of Bethlehem.' Produced the Confession of Dositheus, an authoritative 17th-c. Orthodox confessional document." },
        { id: "b", text: "A Roman Catholic council condemning Jansenism alongside the bull Unigenitus.", rationale: "Wrong. Unigenitus is a real 1713 papal bull against Jansenism — but the Synod of Jerusalem 1672 is Orthodox, not Catholic." },
        { id: "c", text: "A Coptic Orthodox synod restoring communion with the Eastern Orthodox after the Chalcedonian split.", rationale: "Wrong. No such reunion has happened (the Chalcedonian-non-Chalcedonian split remains). Jerusalem 1672 is internal Eastern Orthodox." },
        { id: "d", text: "An Anglican gathering setting forth the 'Branch Theory' of the Church.", rationale: "Wrong. The Anglican Branch Theory is a 19th-c. high-church development, not the 1672 Synod of Jerusalem." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Confession of Dositheus (1672)" }],
    },
    {
      id: "co-final-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["nikon-reforms"],
      prompt: "What was the great schism (Raskol) in the Russian Church (1666-1667)?",
      choices: [
        { id: "a", text: "Patriarch Nikon's liturgical reforms (three-finger sign of the cross, spelling 'Iisus,' triple Alleluia) were imposed; dissenters were anathematized — creating the Old Believers (Starovery).", rationale: "The Old Believers split into priestly (Popovtsy) and priestless (Bezpopovtsy) branches; persist to the present, with partial reconciliations in 1971 (Local Council of the ROC lifted the anathemas)." },
        { id: "b", text: "The Russian Church's formal break with Constantinople, leading to its autocephaly.", rationale: "Wrong. Russian autocephaly was established gradually (de facto 1448; de jure tomos from Constantinople 1589). The Raskol is internal to the Russian Church (1666-67)." },
        { id: "c", text: "Patriarch Nikon's condemnation of Western liturgical influences in Ukrainian Orthodox practice.", rationale: "Wrong. Nikon DID engage with Ukrainian Orthodox influences, but the Raskol was about IMPOSING Greek norms (Nikon's faction) against Russian tradition (Old Believers)." },
        { id: "d", text: "The monastic reform of Joseph of Volokolamsk against the Non-Possessors led by Nilus of Sora.", rationale: "Wrong. The Josephites-vs-Non-Possessors controversy IS a real 15th-16th c. Russian dispute, but it is separate from and earlier than the Nikon Raskol (1666-67)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of the Great Moscow Synod (1666-1667)" }],
    },
    {
      id: "co-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["athonite-typikon"],
      prompt: "When was the foundational governing Typikon of Mount Athos issued?",
      choices: [
        { id: "a", text: "972, by Emperor John Tzimiskes ('Tragos'), regulating Athonite monasticism after Athanasios's reforms.", rationale: "The 'Tragos' (so called from the goatskin parchment) gave Athos its self-governing constitution. Updated by Constantine IX Monomachos (1045)." },
        { id: "b", text: "1453, after the fall of Constantinople, to consolidate monastic life under Ottoman rule.", rationale: "Wrong. Athos's typikon predates the Ottomans by half a millennium." },
        { id: "c", text: "1054, in connection with the Great Schism's reordering of Byzantine institutions.", rationale: "Wrong. Athonite typikon predates 1054 by 80+ years." },
        { id: "d", text: "1700, by Patriarch Dositheus of Jerusalem, after the consolidation of Athonite reform.", rationale: "Wrong. Dositheus is associated with the 1672 Jerusalem synod, not the Athonite typikon." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hagioritic Typikon (Tragos) of John Tzimiskes, 972" }],
    },
  ],
};
