import type { Topic } from "@/lib/types";

export const councilsFinalPack: Topic = {
  id: "councils-final-pack",
  title: "Councils — Final Pack",
  summary: "Final MCQs on Ecumenical and important local councils.",
  learningObjectives: ["Master council details."],
  primarySources: ["Acts of the seven councils; Pedalion"],
  items: [
    {
      id: "co-final-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["fathers-feast"],
      prompt: "When is the 'Sunday of the Holy Fathers' commemorating the First Ecumenical Council observed?",
      choices: [
        { id: "a", text: "The Sunday between Ascension and Pentecost", rationale: "Correct. Honoring the 318 Fathers of Nicaea." },
        { id: "b", text: "The First Sunday of Lent" },
        { id: "c", text: "Holy Saturday" },
        { id: "d", text: "All Saints Sunday" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pentecostarion — Sunday of the Fathers of Nicaea" }],
    },
    {
      id: "co-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedon-canon-28"],
      prompt: "What does canon 28 of Chalcedon (451) decree?",
      choices: [
        { id: "a", text: "It grants the See of Constantinople equal privileges with Rome and primacy over Pontus, Asia, and Thrace.", rationale: "Correct. Rome's legates protested but were overruled." },
        { id: "b", text: "It defines the two natures" },
        { id: "c", text: "It establishes the Lenten fast" },
        { id: "d", text: "It rejects the Tome of Leo" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Canon 28 of Chalcedon (451)" }],
    },
    {
      id: "co-final-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["jerusalem-1672"],
      prompt: "What was the Synod of Jerusalem (1672)?",
      choices: [
        { id: "a", text: "An Orthodox synod under Patriarch Dositheus of Jerusalem, responding to Calvinizing tendencies introduced by Patriarch Cyril Lucaris's posthumous 'Confession.' The Confession of Dositheus answered point by point.", rationale: "Correct. Sometimes called the 'Council of Bethlehem.'" },
        { id: "b", text: "A Roman Catholic council" },
        { id: "c", text: "A Coptic synod" },
        { id: "d", text: "An Anglican gathering" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Confession of Dositheus (1672)" }],
    },
    {
      id: "co-final-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["nikon-reforms"],
      prompt: "What was the great schism (Raskol) in the Russian Church (1666-67)?",
      choices: [
        { id: "a", text: "Patriarch Nikon's liturgical reforms (sign of the cross with 3 fingers vs 2, spelling of 'Iisus', triple Alleluia, etc.) were imposed and dissenters condemned, creating the Old Believer (Starovery) schism that continues to this day.", rationale: "Correct." },
        { id: "b", text: "The break with Constantinople" },
        { id: "c", text: "A condemnation of Western influences" },
        { id: "d", text: "A monastic reform" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of the Great Moscow Synod (1666-67)" }],
    },
    {
      id: "co-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["athonite-typikon"],
      prompt: "When was the foundational Typikon of Mount Athos issued?",
      choices: [
        { id: "a", text: "Typikon of John Tzimiskes (~AD 972), reorganizing Athonite monasticism after St. Athanasios the Athonite.", rationale: "Correct." },
        { id: "b", text: "AD 1453" },
        { id: "c", text: "AD 1054" },
        { id: "d", text: "AD 1700" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hagioritic Typikon (972)" }],
    },
  ],
};
