import type { Topic } from "@/lib/types";

export const scriptureFinalPack: Topic = {
  id: "scripture-final-pack",
  title: "Scripture — Final Pack",
  summary: "Final MCQs on Scripture.",
  learningObjectives: ["Last drill on biblical questions."],
  primarySources: ["Standard biblical references"],
  items: [
    {
      id: "scr-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["pentateuch"],
      prompt: "What are the five books of the Pentateuch?",
      choices: [
        { id: "a", text: "Genesis, Exodus, Leviticus, Numbers, Deuteronomy", rationale: "Correct. The Torah." },
        { id: "b", text: "Joshua, Judges, Ruth, 1 Samuel, 2 Samuel" },
        { id: "c", text: "Isaiah, Jeremiah, Ezekiel, Daniel, Hosea" },
        { id: "d", text: "Matthew, Mark, Luke, John, Acts" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Old Testament" }],
    },
    {
      id: "scr-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["four-gospels"],
      prompt: "Which four evangelists wrote the Gospels?",
      choices: [
        { id: "a", text: "Matthew, Mark, Luke, John", rationale: "Correct. Traditional symbols: man (Mt), lion (Mk), ox (Lk), eagle (Jn)." },
        { id: "b", text: "Peter, Paul, James, Jude" },
        { id: "c", text: "Andrew, Bartholomew, Thomas, Philip" },
        { id: "d", text: "Stephen, Philip, Apollos, Barnabas" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard NT" }],
    },
    {
      id: "scr-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["catholic-epistles"],
      prompt: "What are the 'Catholic Epistles' (also called General Epistles)?",
      choices: [
        { id: "a", text: "James, 1-2 Peter, 1-3 John, Jude — seven letters not addressed to specific churches.", rationale: "Correct." },
        { id: "b", text: "The Pauline letters" },
        { id: "c", text: "Letters of the Pope" },
        { id: "d", text: "The four Gospels" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard NT canon" }],
    },
    {
      id: "scr-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["divisions-ot"],
      prompt: "How does the Orthodox tradition group the Old Testament books?",
      choices: [
        { id: "a", text: "Law (Pentateuch), Histories (Joshua-Esther), Wisdom (Job-Sirach), Prophets (Isaiah-Maccabees with the 12 minor)", rationale: "Correct. With the Anaginōskomena interspersed." },
        { id: "b", text: "Tanakh: Torah, Nevi'im, Ketuvim — strictly only" },
        { id: "c", text: "Three categories: holy, semi-holy, profane" },
        { id: "d", text: "By size only" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "LXX organization; Orthodox liturgical tradition" }],
    },
    {
      id: "scr-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["textus-receptus"],
      prompt: "What is the 'Textus Receptus,' and how does the Orthodox Greek liturgical NT relate to it?",
      choices: [
        { id: "a", text: "The Greek NT edited by Erasmus (1516), basis of KJV; Orthodox liturgical Greek NT (Patriarchal Text) is closely related but not identical, drawn from continuous Byzantine manuscript tradition.", rationale: "Correct." },
        { id: "b", text: "The Septuagint" },
        { id: "c", text: "The Latin Vulgate" },
        { id: "d", text: "The original autographs" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Patriarchal Text of the Greek New Testament; Erasmus, Novum Instrumentum (1516)" }],
    },
    {
      id: "scr-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["nt-readings-liturgy"],
      prompt: "How many Gospel + Epistle readings does the Orthodox lectionary contain in a year?",
      choices: [
        { id: "a", text: "Approximately 360 — one for each day of the moveable cycle, plus festal readings, plus saints of the day.", rationale: "Correct. The Apostolos and Evangelion are arranged accordingly." },
        { id: "b", text: "Only 52 (one per Sunday)" },
        { id: "c", text: "Around 100" },
        { id: "d", text: "Over 1000" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Apostolos and Evangelion (Orthodox lectionary books)" }],
    },
  ],
};
