import type { Topic } from "@/lib/types";

export const scriptureFinalPack: Topic = {
  id: "scripture-final-pack",
  title: "Scripture — Final Pack",
  summary: "Final MCQs on Scripture.",
  learningObjectives: ["Last drill on biblical questions."],
  primarySources: ["Standard biblical references"],
  items: [
    {
      id: "scr-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["pentateuch"],
      prompt: "What are the five books of the Pentateuch?",
      choices: [
        { id: "a", text: "Genesis, Exodus, Leviticus, Numbers, Deuteronomy — the Torah, attributed to Moses.", rationale: "The Torah (Greek pente teuchos 'five books'). Foundational for Jewish and Christian Scripture." },
        { id: "b", text: "Joshua, Judges, Ruth, 1 Samuel, 2 Samuel — the Former Prophets.", rationale: "Wrong. These are the Deuteronomistic History (or 'Former Prophets' in Jewish ordering), which FOLLOWS the Pentateuch, not it." },
        { id: "c", text: "Isaiah, Jeremiah, Ezekiel, Daniel, Hosea — the Major Prophets plus the first Minor.", rationale: "Wrong. Isaiah, Jeremiah, Ezekiel, Daniel are the four Major Prophets (in Christian ordering); Hosea begins the Twelve Minor. They are prophets, not Pentateuch." },
        { id: "d", text: "Matthew, Mark, Luke, John, Acts — the New Testament historical books.", rationale: "Wrong. These are NEW Testament (Gospels + Acts), not OT Pentateuch." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Old Testament (Pentateuch / Torah)" }],
    },
    {
      id: "scr-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["four-gospels"],
      prompt: "Who are the four Evangelists, by traditional attribution?",
      choices: [
        { id: "a", text: "Matthew, Mark, Luke, John — traditional symbols: man (Mt), lion (Mk), ox (Lk), eagle (Jn).", rationale: "Irenaeus Against Heresies III.11 famously argues for exactly four Gospels. The four living creatures of Revelation 4 became their iconographic emblems." },
        { id: "b", text: "Peter, Paul, James, and Jude — the apostolic founders of the four ancient sees.", rationale: "Wrong. These are the four 'pillars' (Gal 2:9 names Peter, James, John) and Paul, but they are not the four EVANGELISTS." },
        { id: "c", text: "Andrew, Bartholomew, Thomas, Philip — four of the Twelve who preached widely east of the Jordan.", rationale: "Wrong. All four are real Apostles who preached widely (Andrew to Scythia, Thomas to India), but none wrote a canonical Gospel." },
        { id: "d", text: "Stephen, Philip, Apollos, Barnabas — early-Church preachers whose teaching is reflected in Acts and beyond.", rationale: "Wrong. All four are real early-Church figures, but none wrote a Gospel. Stephen and Philip are deacons (Acts 6); Apollos and Barnabas are co-laborers of Paul." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Irenaeus, Against Heresies III.11" }],
    },
    {
      id: "scr-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["catholic-epistles"],
      prompt: "What are the 'Catholic' (General) Epistles in the NT?",
      choices: [
        { id: "a", text: "James, 1-2 Peter, 1-3 John, Jude — seven letters not addressed to a specific local church.", rationale: "'Catholic' (universal) because their address is general, not local. In the Eastern tradition they immediately follow Acts in canonical order." },
        { id: "b", text: "Romans through Philemon (excluding Hebrews) — the thirteen undisputed Pauline letters.", rationale: "Wrong. Those are the Pauline letters, not the Catholic Epistles." },
        { id: "c", text: "The encyclical letters of the Popes of Rome, beginning with 1 Clement (~96).", rationale: "Wrong. Papal encyclicals are post-canonical writings; the Catholic Epistles are inside the NT." },
        { id: "d", text: "The four Gospels — 'catholic' (universal) since written for all Christians.", rationale: "Wrong. The Gospels are 'gospels,' not 'epistles.'" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard NT canon" }],
    },
    {
      id: "scr-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["divisions-ot"],
      prompt: "How does the Orthodox tradition group the Old Testament books?",
      choices: [
        { id: "a", text: "Law (Pentateuch), Historical (Joshua-Esther + Maccabees), Wisdom (Job-Sirach), Prophets (Isaiah-Malachi + Baruch/Letter of Jeremiah).", rationale: "Christian (LXX-derived) grouping. Anaginōskomena are interspersed in their respective categories." },
        { id: "b", text: "Tanakh — Torah, Nevi'im (Prophets), Ketuvim (Writings) — following the Hebrew Masoretic order.", rationale: "Wrong. That is the JEWISH ordering. Orthodox follows the Christian LXX-based ordering, which differs (e.g., the Prophets come at the end, not in the middle)." },
        { id: "c", text: "Three categories: canonical, deuterocanonical, apocryphal.", rationale: "Wrong. The Orthodox tradition does have a distinction between 'canonical' and 'anaginōskomena' (read in church) but does not call the latter 'deuterocanonical' (Roman terminology) or 'apocryphal' (Protestant terminology, which excludes them)." },
        { id: "d", text: "By the language of original composition — Hebrew books first, Aramaic books second, Greek books last.", rationale: "Wrong. The OT is not ordered by language. The LXX-Christian order is by genre/era." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "LXX organization; Orthodox liturgical tradition" }],
    },
    {
      id: "scr-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["textus-receptus"],
      prompt:
        "What is the 'Textus Receptus' in NT textual criticism, and how does it relate to the Orthodox liturgical Greek NT?",
      choices: [
        { id: "a", text: "The Greek NT first edited by Erasmus (1516); basis of the King James Version. The Orthodox liturgical Patriarchal Text is closely related but drawn from a broader Byzantine manuscript witness.", rationale: "Erasmus's 1516 edition went through several revisions; the 'received text' name came from the Elzevir brothers' 1633 preface. The Orthodox Patriarchal Edition (1904) was prepared from selected Byzantine lectionary manuscripts." },
        { id: "b", text: "The Septuagint (LXX) Greek translation of the Old Testament, used liturgically.", rationale: "Wrong. The Textus Receptus is a NT edition, not the OT Septuagint." },
        { id: "c", text: "The Latin Vulgate translated by Jerome (~382-405) from Hebrew and Greek.", rationale: "Wrong. The Vulgate is Latin. The Textus Receptus is Greek." },
        { id: "d", text: "The original autograph manuscripts of the New Testament, preserved at Mount Sinai.", rationale: "Wrong. The original autographs do not survive. The Textus Receptus is a 16th-c. printed edition." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Patriarchal Text of the Greek New Testament (1904); Erasmus, Novum Instrumentum (1516)" }],
    },
    {
      id: "scr-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["nt-readings-liturgy"],
      prompt:
        "Approximately how many distinct Gospel + Apostolic readings does the Orthodox lectionary use over the year?",
      choices: [
        { id: "a", text: "Around 360 readings — covering daily readings of the moveable cycle, festal readings, and saints' day readings.", rationale: "The Apostolos (Epistle lectionary) and Evangelion (Gospel lectionary) are arranged to cover virtually the whole NT in a year, with significant repetition on weekdays during Lent and Bright Week." },
        { id: "b", text: "Around 52 — one for each Sunday of the year only.", rationale: "Wrong. Orthodox daily liturgies have appointed readings, not just Sundays." },
        { id: "c", text: "Around 100 — one for each major feast and saint commemorated in the calendar.", rationale: "Wrong. The number is much higher; daily readings, festal readings, and saints' commemorations together approach 360." },
        { id: "d", text: "Over 1000 — the entire Bible read aloud annually, OT and NT.", rationale: "Wrong. The OT is read in selections; the entire NT is not literally read every year. ~360 NT pericopae is the standard figure." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Apostolos and Evangelion (Orthodox lectionary books)" }],
    },
  ],
};
