import type { Topic } from "@/lib/types";

export const scriptureFactsPack: Topic = {
  id: "scripture-facts-pack",
  title: "Scripture — Quick Recall",
  summary: "MCQs on Scripture, canon, and key texts.",
  learningObjectives: ["Drill canon and key references."],
  primarySources: ["Standard biblical and canonical references"],
  items: [
    {
      id: "scr-fp-001",
      kind: "mcq",
      difficulty: 1,
      tags: ["nt-canon"],
      prompt: "How many books are in the New Testament?",
      choices: [
        { id: "a", text: "27", rationale: "Correct." },
        { id: "b", text: "39" },
        { id: "c", text: "73" },
        { id: "d", text: "66" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Athanasius, 39th Festal Letter (367)" }],
    },
    {
      id: "scr-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["ot-canon"],
      prompt: "How many books are in the Orthodox Old Testament (with the anaginōskomena)?",
      choices: [
        { id: "a", text: "Approximately 49 (39 Hebrew + ~10 anaginōskomena: Tobit, Judith, Wisdom, Sirach, Baruch, Letter of Jeremiah, 1-3 Maccabees, additions to Esther/Daniel, Prayer of Manasseh, Psalm 151)", rationale: "Correct." },
        { id: "b", text: "39 (Hebrew canon)" },
        { id: "c", text: "27" },
        { id: "d", text: "73 (Roman Catholic count)" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Confession of Dositheus (1672), Decree 3" }],
    },
    {
      id: "scr-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["gospels"],
      prompt: "Which is the Synoptic Gospel attributed to the disciple of Peter?",
      choices: [
        { id: "a", text: "Mark — preserving Peter's preaching", rationale: "Correct. Papias in Eusebius EH 3.39." },
        { id: "b", text: "Matthew" },
        { id: "c", text: "Luke" },
        { id: "d", text: "John" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Papias, in Eusebius EH 3.39" }],
    },
    {
      id: "scr-fp-004",
      kind: "mcq",
      difficulty: 2,
      tags: ["pauline-letters"],
      prompt: "How many epistles are attributed to St. Paul in the New Testament?",
      choices: [
        { id: "a", text: "Fourteen (Romans through Hebrews — the Eastern reception attributes Hebrews to Paul)", rationale: "Correct. Many modern scholars dispute Pauline authorship of Hebrews; East attributes to Paul; West often hesitant." },
        { id: "b", text: "Seven" },
        { id: "c", text: "Twelve" },
        { id: "d", text: "Twenty-one" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard NT canon" }],
    },
    {
      id: "scr-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["sinaiticus"],
      prompt: "Which 4th-century Greek codex of the entire Bible was discovered at the Monastery of St. Catherine on Mount Sinai by Tischendorf in the 19th century?",
      choices: [
        { id: "a", text: "Codex Sinaiticus", rationale: "Correct. Now in the British Library and St. Catherine's." },
        { id: "b", text: "Codex Vaticanus" },
        { id: "c", text: "Codex Alexandrinus" },
        { id: "d", text: "Codex Bezae" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Tischendorf, Codex Sinaiticus (1862 publication)" }],
    },
    {
      id: "scr-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["lxx"],
      prompt: "Approximately when was the Septuagint translated?",
      choices: [
        { id: "a", text: "3rd-2nd centuries BC, in Alexandria, beginning with the Torah under Ptolemy II Philadelphus.", rationale: "Correct (per Letter of Aristeas, with historical adjustments)." },
        { id: "b", text: "After the time of Christ" },
        { id: "c", text: "In the Middle Ages by Jerome" },
        { id: "d", text: "By the seventy Apostles" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Letter of Aristeas; Philo, Life of Moses II" }],
    },
    {
      id: "scr-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["chapter-verse"],
      prompt: "When were the Bible's chapter and verse divisions added?",
      choices: [
        { id: "a", text: "Chapters by Stephen Langton (~AD 1227); modern verse divisions by Robert Estienne (Stephanus) in 1551 (NT) and 1555 (OT).", rationale: "Correct." },
        { id: "b", text: "By the original authors" },
        { id: "c", text: "At the Council of Trent" },
        { id: "d", text: "By Luther in 1517" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard biblical scholarship" }],
    },
  ],
};
