import type { Topic } from "@/lib/types";

export const scriptureFactsPack: Topic = {
  id: "scripture-facts-pack",
  title: "Scripture — Quick Recall",
  summary: "MCQs on Scripture, canon, and key texts.",
  learningObjectives: ["Drill canon and key references."],
  primarySources: ["Standard biblical and canonical references"],
  items: [
    {
      id: "scr-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["nt-canon"],
      prompt: "How many books are in the New Testament canon?",
      choices: [
        { id: "a", text: "27 — four Gospels, Acts, fourteen Pauline epistles, seven Catholic epistles, Revelation.", rationale: "First listed in Athanasius's 39th Festal Letter (367), ratified at Carthage (397) and Trullo (692, canon 2)." },
        { id: "b", text: "39 — including the four Gospels and the books of the Old Testament prophets considered Christological.", rationale: "Wrong. 39 is the count of the Hebrew OT canon. The NT has 27." },
        { id: "c", text: "73 — counting the deuterocanonical books and the four Gospels together.", rationale: "Wrong. 73 is the Roman Catholic OT+NT total (46 OT + 27 NT); the NT alone is 27." },
        { id: "d", text: "66 — the total of the Protestant Bible (OT 39 + NT 27).", rationale: "Wrong. 66 is the Protestant OT+NT total, not the NT alone (which is 27)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Athanasius, 39th Festal Letter (367)" }],
    },
    {
      id: "scr-fp-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["ot-canon"],
      prompt: "How many books are in the Orthodox Old Testament (with the anaginōskomena)?",
      choices: [
        { id: "a", text: "About 49 — the 39 of the Hebrew canon plus the ~10 anaginōskomena (Tobit, Judith, Wisdom, Sirach, Baruch, Letter of Jeremiah, 1-3 Maccabees, additions to Esther/Daniel, Prayer of Manasseh, Psalm 151).", rationale: "Confession of Dositheus (1672), Decree 3. The exact count varies slightly across jurisdictions (Greek 49, Slavonic 50)." },
        { id: "b", text: "39 — the books accepted by the Hebrew Masoretic canon and by Protestants.", rationale: "Wrong. Orthodoxy includes the anaginōskomena (the books Reformers cut)." },
        { id: "c", text: "27 — the same number as the New Testament, by parallelism.", rationale: "Wrong. 27 is the NT count, not the OT." },
        { id: "d", text: "46 — the Roman Catholic count following Trent (1546).", rationale: "Wrong. Orthodox is approximately 49 (with some variation); Trent's 46 is similar but not identical (Orthodox includes 3 Maccabees and Psalm 151, which Trent does not)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Confession of Dositheus (1672), Decree 3" }],
    },
    {
      id: "scr-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["gospels", "mark"],
      prompt: "Which Synoptic Gospel is traditionally attributed to a disciple of Peter?",
      choices: [
        { id: "a", text: "Mark — preserving Peter's preaching at Rome.", rationale: "Papias of Hierapolis (early 2nd c., quoted in Eusebius EH 3.39): 'Mark, having become Peter's interpreter, wrote down accurately, though not in order, whatever he remembered of what was either said or done by the Lord.'" },
        { id: "b", text: "Matthew — written by the Apostle Matthew, formerly the tax collector.", rationale: "Wrong. Matthew is traditionally attributed to the APOSTLE Matthew himself (not a disciple of Peter). The Petrine-disciple Gospel is Mark." },
        { id: "c", text: "Luke — companion of Paul, not of Peter.", rationale: "Wrong. Luke is traditionally attributed to the COMPANION OF PAUL (see Col 4:14; 2 Tim 4:11), not a disciple of Peter." },
        { id: "d", text: "John — written by the youngest Apostle in his old age at Ephesus.", rationale: "Wrong. John is the Fourth Gospel, attributed to the Apostle John (the Theologian) himself — not a disciple of Peter." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Papias, in Eusebius EH 3.39" }],
    },
    {
      id: "scr-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["pauline-letters"],
      prompt: "How many epistles are attributed to St. Paul in the New Testament (per Eastern reception)?",
      choices: [
        { id: "a", text: "Fourteen — Romans through Philemon plus Hebrews (the East attributes Hebrews to Paul).", rationale: "Romans, 1-2 Cor, Galatians, Ephesians, Philippians, Colossians, 1-2 Thess, 1-2 Tim, Titus, Philemon, Hebrews. Critical scholarship disputes Hebrews and the Pastorals; the East assigns all fourteen to Paul." },
        { id: "b", text: "Seven — the 'undisputed' Pauline corpus per modern critical scholarship (Romans, 1-2 Cor, Gal, Phil, 1 Thess, Philemon).", rationale: "Wrong as the Eastern count. Modern criticism DOES distinguish disputed from undisputed Paulines, but the canonical Eastern count attributes 14." },
        { id: "c", text: "Twelve — excluding both Hebrews and the Pastoral Epistles as later forgeries.", rationale: "Wrong. The Orthodox East canonically receives all fourteen as Pauline." },
        { id: "d", text: "Twenty-one — counting all four Gospels' epistolary commendations along with Acts.", rationale: "Wrong. The Gospels and Acts are not epistles. The fourteen are Romans through Hebrews." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard NT canon (Eastern reception)" }],
    },
    {
      id: "scr-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["sinaiticus"],
      prompt:
        "Which 4th-century Greek codex of (nearly) the whole Bible was recovered at the Monastery of St. Catherine on Mount Sinai by Tischendorf in the 19th century?",
      choices: [
        { id: "a", text: "Codex Sinaiticus (Aleph, ℵ) — mid-4th century; portions now divided between the British Library, St. Catherine's, Leipzig, and St. Petersburg.", rationale: "Recovered by Constantin von Tischendorf in 1859 (with earlier fragments in 1844). Published photographically in 1862." },
        { id: "b", text: "Codex Vaticanus (B) — 4th century, held continuously in the Vatican Library since at least 1481.", rationale: "Wrong. Vaticanus IS a real 4th-c. codex but is from the Vatican (not Sinai) and was not recovered by Tischendorf." },
        { id: "c", text: "Codex Alexandrinus (A) — 5th century, held at the British Library since 1627.", rationale: "Wrong. Alexandrinus is 5th c., not 4th. It was a gift from Cyril Lucaris of Constantinople to Charles I in 1627 — recovered earlier than Sinaiticus and at a different location." },
        { id: "d", text: "Codex Bezae (D) — 5th-c. Greek-Latin bilingual, in Cambridge since 1581.", rationale: "Wrong. Bezae is 5th c., bilingual Greek-Latin, and was given to Cambridge by Theodore Beza. Different codex entirely." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Tischendorf, Bibliorum Codex Sinaiticus Petropolitanus (1862)" }],
    },
    {
      id: "scr-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["lxx"],
      prompt: "Approximately when was the Septuagint translated?",
      choices: [
        { id: "a", text: "3rd-2nd centuries BC, in Alexandria, Egypt — beginning with the Torah under Ptolemy II Philadelphus.", rationale: "Per the Letter of Aristeas (legendary in its narrative but accurate in its time-frame). The Prophets and Writings were translated subsequently." },
        { id: "b", text: "After the time of Christ — by the 70 disciples sent out in Luke 10.", rationale: "Wrong. The Septuagint predates Christ by 200+ years; it was the Bible quoted by the Apostles. The 'Seventy' in its title are the legendary translators, not the 70 of Luke 10." },
        { id: "c", text: "In the Middle Ages, by Jerome of Stridon under commission of Pope Damasus.", rationale: "Wrong. Jerome translated the LATIN VULGATE (~382-405) from Hebrew (OT) and Greek (NT). The Septuagint is a Greek translation OF THE HEBREW OT, made 700 years before Jerome." },
        { id: "d", text: "At the Council of Yavneh / Jamnia (~AD 90), by the surviving Pharisees after the Temple's destruction.", rationale: "Wrong. Jamnia is associated with the formation of the rabbinic / Masoretic Hebrew canon, not the Greek translation (LXX), which is older." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Letter of Aristeas; Philo, Life of Moses II.25-44" }],
    },
    {
      id: "scr-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["chapter-verse"],
      prompt: "When were the modern chapter and verse divisions added to the Bible?",
      choices: [
        { id: "a", text: "Chapters by Stephen Langton (~1227) at Paris; verse divisions by Robert Estienne (Stephanus) — NT 1551, full Bible 1555.", rationale: "Langton became Archbishop of Canterbury; his chapters were rapid pan-Western adoption. Estienne reportedly numbered verses on horseback between Paris and Lyon." },
        { id: "b", text: "Added by the original biblical authors as integral to the text.", rationale: "Wrong. Ancient Hebrew and Greek manuscripts had no chapter or verse numbers; they are medieval/early modern editorial additions." },
        { id: "c", text: "Imposed at the Council of Trent (1546) along with the canonization of the deuterocanon.", rationale: "Wrong. Trent received the Vulgate (which by then HAD chapter/verse numbers), but the numbering scheme itself predates Trent — Langton 1227, Estienne 1551." },
        { id: "d", text: "Devised by Luther in 1517 for his German translation, the basis of all subsequent vernacular Bibles.", rationale: "Wrong. Luther used existing chapter numbering. The modern verse divisions came LATER (1551, Estienne)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Bruce Metzger, The Text of the New Testament (4th ed., 2005)" }],
    },
  ],
};
