import type { Topic } from "@/lib/types";

export const protFinalPack: Topic = {
  id: "prot-final-pack",
  title: "Protestant Final Pack",
  summary: "Final MCQ pack on Protestantism vs. Orthodoxy.",
  learningObjectives: ["Drill remaining distinctives."],
  primarySources: ["Various Protestant confessional documents"],
  items: [
    {
      id: "prot-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["five-solas"],
      prompt: "What are the 'Five Solas' of the Reformation?",
      choices: [
        { id: "a", text: "Sola Scriptura, Sola Fide, Sola Gratia, Solus Christus, Soli Deo Gloria.", rationale: "Crystallized retrospectively (the phrase 'Five Solas' itself is 20th-c.); but each principle was central to Luther, Calvin, and the magisterial Reformers." },
        { id: "b", text: "Sola Ecclesia, Sola Petra, Sola Confessio, Sola Sacramentum, Sola Auctoritas.", rationale: "Wrong. These are not Reformation slogans; they sound vaguely Latin-Catholic but are not a real list." },
        { id: "c", text: "Sola Pater, Sola Filius, Sola Spiritus, Sola Maria, Sola Crux.", rationale: "Wrong. These do not correspond to any historical movement; the Reformation did NOT have a 'Sola Mary.'" },
        { id: "d", text: "Sola Lex, Sola Evangelium, Sola Promissio, Sola Sacramentum, Sola Fides.", rationale: "Wrong. Although some of these words (lex/evangelium/promissio) are real Lutheran categories (Law/Gospel/Promise), they are not the Five Solas." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Reformation historiography; cf. Sproul, What Is Reformed Theology?" }],
    },
    {
      id: "prot-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["luther-tabletalk"],
      prompt: "Luther's 'Tower Experience' (~1513-1518) led him to what key conviction about Romans 1:17?",
      choices: [
        { id: "a", text: "That the 'righteousness of God' is the righteousness GOD GIVES the believer (passive/imputed), not the righteousness God demands.", rationale: "The seed of his justification doctrine. Luther later wrote that this insight 'opened to me the gate of paradise.'" },
        { id: "b", text: "That salvation is by works of love alone, with faith as the seed.", rationale: "Wrong. This is closer to a synergistic position; Luther taught faith ALONE, not works alone." },
        { id: "c", text: "That the Mass must be sung in Latin to preserve the universal Catholic Church.", rationale: "Wrong. Luther moved in the OPPOSITE direction — vernacular liturgy. The Deutsche Messe (1526) is his German Mass." },
        { id: "d", text: "That the Pope is infallible when defining doctrine on faith and morals.", rationale: "Wrong. This is the Vatican I (1870) Catholic dogma. Luther rejected papal infallibility decisively." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Luther, Preface to Latin Writings (1545); Romans 1:17" }],
    },
    {
      id: "prot-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["zwingli", "marburg"],
      prompt: "Who debated Luther over the Eucharist at the Marburg Colloquy (1529)?",
      choices: [
        { id: "a", text: "Ulrich Zwingli (Zurich) — argued the Eucharist is symbolic memorial; Luther insisted on bodily presence.", rationale: "Marburg, October 1-4, 1529. Fourteen of fifteen articles agreed; the fifteenth (the Lord's Supper) ended in division. Zwingli died at Kappel two years later." },
        { id: "b", text: "John Calvin (Geneva) — argued his 'spiritual presence' against Luther's bodily presence.", rationale: "Wrong. Calvin came LATER (1536+); at Marburg in 1529 he was only twenty years old and not yet a Reformer." },
        { id: "c", text: "John Wesley (Oxford) — argued for entire sanctification against Luther's forensic justification.", rationale: "Wrong. Wesley is 18th-c.; Marburg is 1529, two centuries earlier." },
        { id: "d", text: "Martin Bucer (Strasbourg) — argued for adult baptism against Luther's paedobaptism.", rationale: "Wrong. Bucer was a real Reformer and attended Marburg, but the principal debater was Zwingli, on the Eucharist (not baptism)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Marburg Colloquy, October 1529 — Marburg Articles" }],
    },
    {
      id: "prot-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["anabaptists"],
      prompt: "Who were the Anabaptists?",
      choices: [
        { id: "a", text: "16th-c. radical Reformers (Conrad Grebel, Felix Manz, Menno Simons) who rejected infant baptism; ancestors of Mennonites, Amish, Hutterites.", rationale: "Schleitheim Confession (1527). Persecuted by both Catholics and magisterial Protestants; the Münster Rebellion (1534-35) discredited an apocalyptic wing." },
        { id: "b", text: "A faction of Reformed Calvinists who emphasized double predestination over the Lutheran view.", rationale: "Wrong. Reformed Calvinists baptized infants (paedobaptism); Anabaptists did not. They are distinct movements." },
        { id: "c", text: "A Lutheran apologetic society in Wittenberg that defended Luther against the Roman bull.", rationale: "Wrong. The Anabaptists were OPPONENTS of Lutheranism on baptism; they were not Lutheran apologists." },
        { id: "d", text: "Followers of George Fox, also called the Society of Friends or Quakers.", rationale: "Wrong. Quakers (founded by Fox, ~1650) are a different group, a century later than the Anabaptists." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Schleitheim Confession (1527); Mennonite Encyclopedia" }],
    },
    {
      id: "prot-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["puritans"],
      prompt: "Who were the Puritans?",
      choices: [
        { id: "a", text: "16th-17th c. English Calvinists seeking to 'purify' the Church of England of remaining Catholic ceremonial — produced John Owen, John Bunyan; emigrated to New England.", rationale: "Their political ascendancy under Cromwell (1649-1660) was followed by the Restoration. Their American descendants founded Massachusetts Bay Colony (1630)." },
        { id: "b", text: "A 14th-century English Reformation movement led by John Wycliffe and the Lollards.", rationale: "Wrong. Wycliffe (d. 1384) and the Lollards are earlier proto-Reformers; Puritans are 16th-17th c. and Calvinist." },
        { id: "c", text: "An early Pentecostal movement among Wesleyan Methodists in the American holiness revivals.", rationale: "Wrong. The Holiness movement (19th c.) and Pentecostalism (20th c.) are later and Wesleyan-Arminian, not Puritan-Calvinist." },
        { id: "d", text: "A 19th-century Russian Old Believer faction known for its ritual purity.", rationale: "Wrong. The Old Believers are real (split from the Russian Church 1666-67 over Nikon's reforms) — but distinct from English Puritans." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Coffey, Persecution and Toleration in Protestant England (2000)" }],
    },
    {
      id: "prot-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["pietism"],
      prompt: "What was Pietism, and who was its principal figure?",
      choices: [
        { id: "a", text: "A 17th-18th c. Lutheran reform movement led by Philip Spener (1635-1705) and August Hermann Francke — emphasized experiential religion, Bible study, and missions.", rationale: "Spener's Pia Desideria (1675) was the manifesto. Francke's University of Halle became its center. Influential on Wesley and the Moravians (Zinzendorf)." },
        { id: "b", text: "A medieval Catholic religious order founded by St. Pio of Pietrelcina in the 13th century.", rationale: "Wrong. Padre Pio (1887-1968) is a 20th-c. Capuchin friar, not a 13th-c. founder of an order called 'Pietism.'" },
        { id: "c", text: "A modern American megachurch movement led by Bill Hybels and Willow Creek.", rationale: "Wrong. Willow Creek (Bill Hybels, 1975+) is the seeker-sensitive movement, not Pietism." },
        { id: "d", text: "A Russian Old Believer movement of itinerant penitents in the 18th century.", rationale: "Wrong. The Stranniki (Wanderers) ARE a real 18th-c. Russian Bezpopovsy Old Believer branch — but not Pietism." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philip Spener, Pia Desideria (1675)" }],
    },
    {
      id: "prot-final-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["nicene-creed"],
      prompt: "Which Protestant confessions explicitly confess the Nicene Creed?",
      choices: [
        { id: "a", text: "Most magisterial confessions (Augsburg 1530, 39 Articles 1571, Westminster 1646) — usually with Filioque; many free-church and Bible-only traditions do not formally confess creeds.", rationale: "The magisterial Reformation (Lutheran, Reformed, Anglican) retained the Symbol; the Radical Reformation and later free-church traditions often rejected formal confession of creeds." },
        { id: "b", text: "None — the Reformation universally rejected post-biblical creeds.", rationale: "Wrong. The magisterial Reformers explicitly retained the Symbol (Augsburg Confession Article I; 39 Articles, Article VIII)." },
        { id: "c", text: "All Protestant traditions — confession of the Nicene Creed is universal in Protestantism.", rationale: "Wrong. Many Anabaptist, Quaker, Pentecostal, and non-denominational traditions do not formally confess any creed." },
        { id: "d", text: "Only Lutherans — the Reformed and Anglican confessions reject post-biblical doctrines.", rationale: "Wrong. Reformed (Westminster) and Anglican (39 Articles) both confess the Nicene faith." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Augsburg Confession Article I; 39 Articles Article VIII; Westminster Larger Catechism Q9" }],
    },
  ],
};
