import type { Topic } from "@/lib/types";

export const protFinalPack: Topic = {
  id: "prot-final-pack",
  title: "Protestant Final Pack",
  summary: "Final MCQ pack on Protestantism vs. Orthodoxy.",
  learningObjectives: ["Drill remaining distinctives."],
  primarySources: ["Various Protestant confessional documents"],
  items: [
    {
      id: "prot-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["five-solas"],
      prompt: "What are the 'Five Solas' of the Reformation?",
      choices: [
        { id: "a", text: "Sola Scriptura, Sola Fide, Sola Gratia, Solus Christus, Soli Deo Gloria", rationale: "Correct." },
        { id: "b", text: "Sola Mass, Sola Pope, Sola Saints, Sola Confession, Sola Indulgence" },
        { id: "c", text: "Sola Father, Sola Son, Sola Spirit, Sola Mary, Sola Cross" },
        { id: "d", text: "Sola Logos, Sola Sophia, Sola Trias, Sola Eikon, Sola Liturgia" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Reformation historiography" }],
    },
    {
      id: "prot-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["luther-tabletalk"],
      prompt: "Luther's TableTalk and Tower Experience (~1515) led him to which key conviction?",
      choices: [
        { id: "a", text: "That the 'righteousness of God' (Romans 1:17) is the righteousness GOD GIVES the believer (imputed), not the righteousness God demands.", rationale: "Correct. The seed of Lutheran justification doctrine." },
        { id: "b", text: "That works alone justify" },
        { id: "c", text: "That Mass should be in Latin only" },
        { id: "d", text: "That the Pope is infallible" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Luther, Tower Experience account; Romans 1:17" }],
    },
    {
      id: "prot-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["zwingli", "marburg"],
      prompt: "Who was the principal Reformed reformer at Zurich, and what did he debate with Luther at Marburg (1529)?",
      choices: [
        { id: "a", text: "Ulrich Zwingli; he debated Luther over the Real Presence. Luther affirmed bodily presence; Zwingli held the Eucharist is a memorial only. They failed to agree.", rationale: "Correct." },
        { id: "b", text: "Calvin; debated predestination" },
        { id: "c", text: "Wesley; debated sanctification" },
        { id: "d", text: "Bucer; debated baptism" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Marburg Colloquy, October 1529" }],
    },
    {
      id: "prot-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["anabaptists"],
      prompt: "Who were the Anabaptists?",
      choices: [
        { id: "a", text: "16th-c. radical Reformers (Conrad Grebel, Felix Manz, Menno Simons) who rejected infant baptism; persecuted by both Catholics and magisterial Protestants. Spiritual ancestors of Mennonites, Amish, Hutterites.", rationale: "Correct." },
        { id: "b", text: "Reformed Calvinists" },
        { id: "c", text: "Lutheran apologists" },
        { id: "d", text: "Quaker mystics" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Schleitheim Confession (1527); Various histories" }],
    },
    {
      id: "prot-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["puritans"],
      prompt: "Who were the Puritans?",
      choices: [
        { id: "a", text: "16th-17th c. English Calvinist reformers seeking to 'purify' the Church of England of remaining Catholic elements; produced figures like John Owen, John Bunyan; emigrated to New England.", rationale: "Correct." },
        { id: "b", text: "A Roman Catholic order" },
        { id: "c", text: "Early Pentecostals" },
        { id: "d", text: "Russian Orthodox reformers" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard English Reformation history" }],
    },
    {
      id: "prot-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["pietism"],
      prompt: "What was Pietism, and who was its principal figure?",
      choices: [
        { id: "a", text: "A 17th-18th c. Lutheran reform movement emphasizing personal experiential religion, study of Scripture, and missions, led by Philip Spener (1635-1705) and August Hermann Francke. Influential on Wesley and the Moravians.", rationale: "Correct." },
        { id: "b", text: "A medieval Catholic order" },
        { id: "c", text: "A modern megachurch movement" },
        { id: "d", text: "A Russian sectarian movement" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philip Spener, Pia Desideria (1675)" }],
    },
    {
      id: "prot-final-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["nicene-creed"],
      prompt: "Which Protestant confessions explicitly confess the Nicene Creed?",
      choices: [
        { id: "a", text: "Most magisterial confessions (Augsburg, 39 Articles, Westminster Larger Catechism Q9) — usually with the Filioque included. Many free-church and Bible-only traditions do not formally confess any creed.", rationale: "Correct." },
        { id: "b", text: "None" },
        { id: "c", text: "All Protestant traditions" },
        { id: "d", text: "Only Lutherans" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Various confessional documents" }],
    },
  ],
};
