import type { Topic } from "@/lib/types";

export const protestantFactsPack: Topic = {
  id: "protestant-facts-pack",
  title: "Protestant History — Quick Facts",
  summary: "Rapid-fire MCQs on Protestant history and confessions.",
  learningObjectives: ["Drill the key dates and figures."],
  primarySources: ["Standard church history references"],
  items: [
    {
      id: "prot-fp-001",
      kind: "mcq",
      difficulty: 1,
      tags: ["luther"],
      prompt: "When did Luther post the 95 Theses?",
      choices: [
        { id: "a", text: "October 31, 1517", rationale: "Correct. The Eve of All Saints." },
        { id: "b", text: "January 1, 1500" },
        { id: "c", text: "March 31, 1521" },
        { id: "d", text: "December 25, 1522" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Disputatio pro declaratione virtutis indulgentiarum, 31 October 1517" }],
    },
    {
      id: "prot-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["calvin"],
      prompt: "In what year did John Calvin first publish the Institutes of the Christian Religion?",
      choices: [
        { id: "a", text: "1536", rationale: "Correct. First Latin edition, Basel. Substantially expanded through 1559." },
        { id: "b", text: "1564" },
        { id: "c", text: "1500" },
        { id: "d", text: "1601" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Calvin, Institutio Christianae Religionis (1536)" }],
    },
    {
      id: "prot-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["wesley"],
      prompt: "Who founded the Methodist movement?",
      choices: [
        { id: "a", text: "John Wesley (and Charles Wesley) — 18th c. Anglican priests", rationale: "Correct." },
        { id: "b", text: "George Whitefield alone" },
        { id: "c", text: "John Wycliffe" },
        { id: "d", text: "Jonathan Edwards" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Wesley, Journal" }],
    },
    {
      id: "prot-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["evangelicalism"],
      prompt: "What is the 'Bebbington Quadrilateral' commonly used to define Evangelicalism?",
      choices: [
        { id: "a", text: "(1) Biblicism, (2) Crucicentrism, (3) Conversionism, (4) Activism", rationale: "Correct. From David Bebbington's 1989 typology." },
        { id: "b", text: "Apostolic, episcopal, conciliar, sacramental" },
        { id: "c", text: "Sola Scriptura, Sola Fide, Sola Gratia, Solus Christus" },
        { id: "d", text: "Confessional, liturgical, ecumenical, missional" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "David Bebbington, Evangelicalism in Modern Britain (1989)" }],
    },
    {
      id: "prot-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["azusa-street"],
      prompt: "What 1906 event is generally considered the birth of modern Pentecostalism?",
      choices: [
        { id: "a", text: "The Azusa Street Revival under William Seymour in Los Angeles", rationale: "Correct. April 1906 forward." },
        { id: "b", text: "The Lausanne Congress" },
        { id: "c", text: "The Edinburgh Missionary Conference" },
        { id: "d", text: "The Methodist General Conference" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "William J. Seymour, Apostolic Faith newspaper (1906-09)" }],
    },
    {
      id: "prot-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["sbc"],
      prompt: "When was the Southern Baptist Convention founded, and over what issue did it split from northern Baptists?",
      choices: [
        { id: "a", text: "1845, over slavery (the SBC supported it; the northern Baptists opposed appointing slave-holding missionaries).", rationale: "Correct. SBC formally apologized for this history in 1995." },
        { id: "b", text: "1925, over evolution" },
        { id: "c", text: "1700, over baptism mode" },
        { id: "d", text: "1979, over inerrancy" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "SBC Resolution on Racial Reconciliation (1995)" }],
    },
    {
      id: "prot-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["barth"],
      prompt: "Who was Karl Barth, and what is his Church Dogmatics?",
      choices: [
        { id: "a", text: "Swiss Reformed theologian (1886-1968); his thirteen-volume Church Dogmatics is the dominant 20th-c. Protestant systematic theology.", rationale: "Correct." },
        { id: "b", text: "An American Pentecostal televangelist" },
        { id: "c", text: "An Anglican bishop at Vatican II" },
        { id: "d", text: "A Lutheran patriarch of Constantinople" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Karl Barth, Kirchliche Dogmatik (Church Dogmatics), 1932-1967" }],
    },
  ],
};
