import type { Topic } from "@/lib/types";

export const protestantFactsPack: Topic = {
  id: "protestant-facts-pack",
  title: "Protestant History — Quick Facts",
  summary: "Rapid-fire MCQs on Protestant history and confessions.",
  learningObjectives: ["Drill the key dates and figures."],
  primarySources: ["Standard church history references"],
  items: [
    {
      id: "prot-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["luther"],
      prompt: "When did Luther reportedly post the 95 Theses?",
      choices: [
        { id: "a", text: "October 31, 1517 — the Eve of All Saints, at the Castle Church of Wittenberg.", rationale: "Disputatio pro declaratione virtutis indulgentiarum. Whether physically nailed to the door is debated, but the date and intent are clear." },
        { id: "b", text: "April 18, 1521 — at the Diet of Worms, where he was summoned before the Emperor.", rationale: "Wrong. April 18, 1521 IS the date of his 'Here I stand' speech at Worms — four years AFTER the 95 Theses." },
        { id: "c", text: "May 25, 1521 — when he was placed under imperial ban by the Edict of Worms.", rationale: "Wrong, although the Edict of Worms IS a real document from May 1521. The 95 Theses were earlier, in 1517." },
        { id: "d", text: "December 10, 1520 — when he publicly burned the papal bull Exsurge Domine in Wittenberg.", rationale: "Wrong, but Luther DID burn Exsurge Domine on December 10, 1520. That is three years after the 95 Theses." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Disputatio pro declaratione virtutis indulgentiarum, 31 October 1517" }],
    },
    {
      id: "prot-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["calvin"],
      prompt: "In what year did John Calvin first publish the Institutes of the Christian Religion?",
      choices: [
        { id: "a", text: "1536 — the first Latin edition, published in Basel.", rationale: "Calvin was 26. He continued to expand and revise the work through the final 1559 edition (four books, 80 chapters)." },
        { id: "b", text: "1559 — the final and most expanded Latin edition.", rationale: "Wrong. 1559 is the FINAL edition; the FIRST appeared in 1536." },
        { id: "c", text: "1564 — the year of Calvin's death, with the Institutes published posthumously.", rationale: "Wrong. Calvin died May 27, 1564, but the Institutes had been in print since 1536." },
        { id: "d", text: "1648 — at the close of the Thirty Years' War.", rationale: "Wrong. 1648 is the Peace of Westphalia; Calvin had been dead 84 years by then." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Calvin, Institutio Christianae Religionis (Basel, 1536)" }],
    },
    {
      id: "prot-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["wesley"],
      prompt: "Who founded the Methodist movement?",
      choices: [
        { id: "a", text: "John and Charles Wesley — 18th-century Anglican priests; John was the chief organizer, Charles the hymn-writer.", rationale: "Both remained Anglican clergy throughout their lives. Methodism only formally separated from the Church of England after John Wesley's death (1791)." },
        { id: "b", text: "George Whitefield — the powerful Calvinist field-preacher of the First Great Awakening.", rationale: "Wrong. Whitefield was a Calvinist and co-laborer with the Wesleys but separated from them over predestination; Methodism is Wesleyan-Arminian." },
        { id: "c", text: "John Wycliffe — the 14th-century Oxford theologian and 'morning star' of the Reformation.", rationale: "Wrong. Wycliffe died in 1384, four centuries before Methodism. He inspired the Lollards." },
        { id: "d", text: "Jonathan Edwards — the New England Puritan theologian of the First Great Awakening.", rationale: "Wrong. Edwards (1703-1758) was a contemporary of the Wesleys but a Puritan-Reformed Congregationalist, not a Methodist." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Wesley, Journal; Charles Wesley, Hymns" }],
    },
    {
      id: "prot-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["evangelicalism"],
      prompt: "What is the 'Bebbington Quadrilateral' commonly used to define Evangelicalism?",
      choices: [
        { id: "a", text: "Biblicism, Crucicentrism, Conversionism, Activism — David Bebbington's 1989 typology.", rationale: "From Bebbington's Evangelicalism in Modern Britain (1989). Widely adopted in sociology of religion as a working definition." },
        { id: "b", text: "Apostolic, Episcopal, Conciliar, Sacramental — the marks of the catholic Church in modern systematic theology.", rationale: "Wrong. Those marks (or close variants) describe Orthodoxy and high-church bodies, not the specific definition of Evangelicalism." },
        { id: "c", text: "Sola Scriptura, Sola Fide, Sola Gratia, Solus Christus — the 'Five Solas' minus Soli Deo Gloria.", rationale: "Wrong. The Solas are Reformation slogans; Bebbington's Quadrilateral describes modern (18th-c. onward) Evangelicalism specifically." },
        { id: "d", text: "Confessional, Liturgical, Ecumenical, Missional — the four marks of the magisterial Reformation.", rationale: "Wrong. That isn't an established taxonomy; the Bebbington Quadrilateral is the well-known framework." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "David Bebbington, Evangelicalism in Modern Britain (1989)" }],
    },
    {
      id: "prot-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["azusa-street"],
      prompt: "What 1906 event is generally considered the birth of modern Pentecostalism?",
      choices: [
        { id: "a", text: "The Azusa Street Revival in Los Angeles under William J. Seymour, from April 1906.", rationale: "Seymour was an African-American Holiness preacher influenced by Charles Parham. The revival lasted three years and seeded global Pentecostalism." },
        { id: "b", text: "The Topeka outpouring under Charles Parham at Bethel Bible College on January 1, 1901.", rationale: "Wrong. The Topeka event (1901) under Parham is the IMMEDIATE precursor (and Parham taught Seymour), but the BIRTH of modern Pentecostalism is usually placed at Azusa Street (1906)." },
        { id: "c", text: "The Edinburgh Missionary Conference of 1910 that launched the modern ecumenical movement.", rationale: "Wrong. Edinburgh 1910 is foundational for ECUMENISM, not Pentecostalism." },
        { id: "d", text: "The first General Council of the Assemblies of God at Hot Springs, Arkansas (1914).", rationale: "Wrong. The AG founding council in 1914 organized existing Pentecostals into a denomination, but Pentecostalism itself was born ~1906 at Azusa." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "William J. Seymour, Apostolic Faith newspaper (1906-1909)" }],
    },
    {
      id: "prot-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["sbc"],
      prompt:
        "When was the Southern Baptist Convention founded, and over what issue did it split from northern Baptists?",
      choices: [
        { id: "a", text: "1845, over slavery — Northern Baptists refused to appoint slave-holding missionaries; Southern Baptists separated.", rationale: "SBC formally apologized for this history in 1995. Today the largest Protestant denomination in the U.S." },
        { id: "b", text: "1925, over evolution — Southern Baptists rejected Darwinism after the Scopes Trial.", rationale: "Wrong. Southern Baptists DID reject evolution but the denominational split predates Scopes by 80 years." },
        { id: "c", text: "1707, over baptism — Northern Baptists permitted sprinkling; Southern Baptists insisted on immersion only.", rationale: "Wrong. The first Baptist Association (Philadelphia, 1707) and Charleston Association (1751) are 18th-c., but the SBC split was 1845 over slavery." },
        { id: "d", text: "1979, over biblical inerrancy — the conservative resurgence purged moderates from leadership.", rationale: "Wrong. The Conservative Resurgence IS a real intra-SBC 1979-onward struggle, but the FOUNDING of the SBC was 1845." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "SBC Resolution on Racial Reconciliation (1995)" }],
    },
    {
      id: "prot-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["barth"],
      prompt: "Who was Karl Barth, and what is his Church Dogmatics?",
      choices: [
        { id: "a", text: "Swiss Reformed theologian (1886-1968); his unfinished thirteen-volume Church Dogmatics is the principal 20th-c. Protestant systematic theology.", rationale: "Author of the Barmen Declaration (1934) against Nazi Christianity. His Christocentric revision of Reformed theology shaped much 20th-c. Protestantism." },
        { id: "b", text: "An American Pentecostal televangelist of the late 20th century.", rationale: "Wrong. Barth was a Swiss academic theologian, not a televangelist. The American televangelist tradition is a different movement (Oral Roberts, Robert Schuller, etc.)." },
        { id: "c", text: "An Anglican bishop who attended Vatican II as an ecumenical observer.", rationale: "Wrong. Barth was Swiss Reformed, not Anglican; he did attend Vatican II (1962-65) AS AN OBSERVER, but he was not Anglican." },
        { id: "d", text: "A Lutheran ethicist executed by the Nazis for involvement in the plot against Hitler.", rationale: "Wrong, but a real description of Dietrich BONHOEFFER (1906-1945). Barth was a different theologian — Swiss, Reformed, exiled to Basel rather than executed." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Karl Barth, Kirchliche Dogmatik (Church Dogmatics), 1932-1967" }],
    },
  ],
};
