// Builds the 13 stations of the Pilgrim Road from the 2D quest corpus.
// Only the base battle chapters form the road — one zone per chapter,
// in chronological order (the corpus' lesson chapters are not staged).

import { CHAPTERS } from "@/lib/quest/chapters";
import { PORTRAITS } from "@/lib/quest/portraits";
import type { ZoneDef, ZonePalette } from "./types";

/** The canonical pilgrimage arc, in road order. */
export const ROAD_CHAPTER_IDS = [
  "ch1-antioch",
  "ch2-catacombs",
  "ch3-nicaea",
  "ch4-desert",
  "ch5-chalcedon",
  "ch6-icons",
  "ch7-schism",
  "ch8-florence",
  "ch9-soviets",
  "ch10-modern",
  "ch10b-reformed",
  "ch10c-atheist",
  "ch11-doubt",
] as const;

// Each era keeps its own weather: golden-hour Mediterranean hills for the
// early Church, harsh desert noon, gray schism overcast, snowbound pine
// country for the Soviet years, deep dusk for the skeptic, and a starlit
// aurora night for the last adversary.
const PALETTES: Record<string, ZonePalette> = {
  "ch1-antioch": {
    sun: { elevation: 14, azimuth: 205, intensity: 2.7, color: "#ffd9a0" },
    turbidity: 8,
    rayleigh: 2.4,
    hemi: { sky: "#ffd2a0", ground: "#8a6a4a", intensity: 0.8 },
    fog: { color: "#e8c9a0", near: 55, far: 175 },
    exposure: 0.95,
    grass: "#97a058",
    dirt: "#b09064",
    rock: "#8a7a66",
    snowLine: 36,
    trees: "olive",
    treeDensity: 0.7,
    grassDensity: 0.8,
  },
  "ch2-catacombs": {
    sun: { elevation: 6, azimuth: 232, intensity: 1.8, color: "#ffaa66" },
    turbidity: 11,
    rayleigh: 3.2,
    hemi: { sky: "#d8985e", ground: "#5a4634", intensity: 0.6 },
    fog: { color: "#c08c64", near: 40, far: 130 },
    exposure: 0.85,
    grass: "#7a6e48",
    dirt: "#94785a",
    rock: "#6e6052",
    snowLine: 999,
    trees: "cypress",
    treeDensity: 0.5,
    grassDensity: 0.5,
    gloom: 0.45,
  },
  "ch3-nicaea": {
    sun: { elevation: 32, azimuth: 165, intensity: 3.0, color: "#fff2dc" },
    turbidity: 5,
    rayleigh: 1.6,
    hemi: { sky: "#bcd6e8", ground: "#7a8468", intensity: 0.85 },
    fog: { color: "#cfdde0", near: 70, far: 210 },
    exposure: 1.0,
    grass: "#76a055",
    dirt: "#b0a07c",
    rock: "#969ca4",
    snowLine: 30,
    trees: "cypress",
    treeDensity: 0.6,
    grassDensity: 0.9,
  },
  "ch4-desert": {
    sun: { elevation: 50, azimuth: 190, intensity: 3.4, color: "#fff6e0" },
    turbidity: 6,
    rayleigh: 1.1,
    hemi: { sky: "#f4e0b0", ground: "#b08a58", intensity: 0.9 },
    fog: { color: "#ecd9ae", near: 70, far: 220 },
    exposure: 1.05,
    grass: "#d2b178",
    dirt: "#ddbb80",
    rock: "#b08a58",
    snowLine: 999,
    trees: "palm",
    treeDensity: 0.35,
    grassDensity: 0.25,
  },
  "ch5-chalcedon": {
    sun: { elevation: 24, azimuth: 200, intensity: 2.8, color: "#ffe8c0" },
    turbidity: 7,
    rayleigh: 1.9,
    hemi: { sky: "#e8d2ac", ground: "#7e7458", intensity: 0.8 },
    fog: { color: "#ddc99e", near: 60, far: 190 },
    exposure: 0.98,
    grass: "#84985a",
    dirt: "#b49c74",
    rock: "#8e8492",
    snowLine: 32,
    trees: "cypress",
    treeDensity: 0.55,
    grassDensity: 0.8,
  },
  "ch6-icons": {
    sun: { elevation: 16, azimuth: 215, intensity: 2.9, color: "#ffd890" },
    turbidity: 8,
    rayleigh: 2.6,
    hemi: { sky: "#f0cf90", ground: "#7e6e4c", intensity: 0.85 },
    fog: { color: "#e6cf96", near: 60, far: 185 },
    exposure: 1.0,
    grass: "#8e9a54",
    dirt: "#bca374",
    rock: "#8e8068",
    snowLine: 34,
    trees: "cypress",
    treeDensity: 0.65,
    grassDensity: 0.85,
  },
  "ch7-schism": {
    sun: { elevation: 22, azimuth: 180, intensity: 1.2, color: "#cfd4dc" },
    turbidity: 16,
    rayleigh: 0.8,
    hemi: { sky: "#9aa4b2", ground: "#5a6058", intensity: 0.7 },
    fog: { color: "#a8b0ba", near: 38, far: 125 },
    exposure: 0.9,
    grass: "#647656",
    dirt: "#8c8270",
    rock: "#788088",
    snowLine: 24,
    trees: "pine",
    treeDensity: 0.6,
    grassDensity: 0.6,
    gloom: 0.25,
  },
  "ch8-florence": {
    sun: { elevation: 19, azimuth: 210, intensity: 2.6, color: "#ffdfae" },
    turbidity: 7,
    rayleigh: 2.1,
    hemi: { sky: "#ecd2a8", ground: "#7a6a50", intensity: 0.8 },
    fog: { color: "#dcc49c", near: 58, far: 180 },
    exposure: 0.97,
    grass: "#88a052",
    dirt: "#b29878",
    rock: "#94765c",
    snowLine: 34,
    trees: "olive",
    treeDensity: 0.65,
    grassDensity: 0.85,
  },
  "ch9-soviets": {
    sun: { elevation: 9, azimuth: 222, intensity: 1.5, color: "#e8eef8" },
    turbidity: 12,
    rayleigh: 0.6,
    hemi: { sky: "#c8d4e8", ground: "#e8ecf4", intensity: 0.8 },
    fog: { color: "#d4dde8", near: 32, far: 115 },
    exposure: 0.92,
    grass: "#edf1f7",
    dirt: "#cdd6e2",
    rock: "#6a7078",
    snowLine: 0,
    trees: "pine",
    treeDensity: 0.85,
    grassDensity: 0,
    snowfall: true,
    gloom: 0.35,
  },
  "ch10-modern": {
    sun: { elevation: 38, azimuth: 175, intensity: 2.5, color: "#fff4e2" },
    turbidity: 6,
    rayleigh: 1.7,
    hemi: { sky: "#bcd2e4", ground: "#74806a", intensity: 0.85 },
    fog: { color: "#c6d4da", near: 65, far: 195 },
    exposure: 1.0,
    grass: "#74945c",
    dirt: "#a09480",
    rock: "#8a8a8a",
    snowLine: 32,
    trees: "birch",
    treeDensity: 0.55,
    grassDensity: 0.85,
  },
  "ch10b-reformed": {
    sun: { elevation: 17, azimuth: 212, intensity: 2.4, color: "#ffd9a8" },
    turbidity: 8,
    rayleigh: 2.3,
    hemi: { sky: "#e8cfa6", ground: "#6e6e58", intensity: 0.8 },
    fog: { color: "#d8c2a0", near: 55, far: 175 },
    exposure: 0.95,
    grass: "#7e945a",
    dirt: "#a8987c",
    rock: "#8c8278",
    snowLine: 33,
    trees: "birch",
    treeDensity: 0.6,
    grassDensity: 0.8,
  },
  "ch10c-atheist": {
    sun: { elevation: 2.5, azimuth: 235, intensity: 0.9, color: "#ff9860" },
    turbidity: 10,
    rayleigh: 3.6,
    hemi: { sky: "#6a5a78", ground: "#3c3844", intensity: 0.55 },
    fog: { color: "#564e60", near: 30, far: 105 },
    exposure: 0.82,
    grass: "#4e5a46",
    dirt: "#6e6458",
    rock: "#52525c",
    snowLine: 999,
    trees: "pine",
    treeDensity: 0.45,
    grassDensity: 0.4,
    stars: true,
    gloom: 0.55,
  },
  "ch11-doubt": {
    sun: { elevation: -12, azimuth: 200, intensity: 0.3, color: "#9fb6e8" },
    turbidity: 10,
    rayleigh: 1,
    hemi: { sky: "#26304a", ground: "#0c0e16", intensity: 0.45 },
    fog: { color: "#0d1018", near: 24, far: 88 },
    exposure: 0.75,
    grass: "#2c3038",
    dirt: "#3a3a44",
    rock: "#22242c",
    snowLine: 999,
    trees: "dead",
    treeDensity: 0.5,
    grassDensity: 0.1,
    stars: true,
    aurora: true,
    gloom: 1,
  },
};

const FALLBACK: ZonePalette = PALETTES["ch1-antioch"];

export function buildZones(): ZoneDef[] {
  const byId = new Map(CHAPTERS.map((c) => [c.id, c]));
  const zones: ZoneDef[] = [];
  ROAD_CHAPTER_IDS.forEach((id, index) => {
    const chapter = byId.get(id);
    if (!chapter || !chapter.boss) return;
    const ally = chapter.ally;
    const allyLine = ally
      ? chapter.intro.find((l) => l.speaker === ally)?.text
      : undefined;
    const narratorLine = chapter.intro.find(
      (l) => l.speaker === "narrator"
    )?.text;
    zones.push({
      index,
      chapter,
      palette: PALETTES[id] ?? FALLBACK,
      bossId: chapter.boss.sprite,
      allyId: ally,
      allyName: ally ? PORTRAITS[ally]?.name ?? ally : undefined,
      allyLine,
      narratorLine,
    });
  });
  return zones;
}
