import type { Topic } from "@/lib/types";

export const fathersFinalPack: Topic = {
  id: "fathers-final-pack",
  title: "Fathers — Final Pack",
  summary: "Final MCQs on the Fathers, their disciples, and chains of transmission.",
  learningObjectives: ["Drill remaining patristic facts."],
  primarySources: ["Standard patrology"],
  items: [
    {
      id: "cf-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["ambrose-augustine"],
      prompt: "Which Father baptized Augustine of Hippo?",
      choices: [
        { id: "a", text: "St. Ambrose of Milan — at the Easter Vigil of 387.", rationale: "Augustine, Confessions IX.6. Ambrose's preaching had been the proximate human cause of Augustine's conversion." },
        { id: "b", text: "Pope Damasus of Rome — under whom Jerome served as secretary.", rationale: "Wrong. Damasus was a real bishop of Rome (366-384), but Augustine was baptized by Ambrose in Milan, not by Damasus in Rome." },
        { id: "c", text: "St. Jerome — under whose translation work Augustine had studied Scripture.", rationale: "Wrong. Augustine and Jerome corresponded but never met; Jerome did not baptize him." },
        { id: "d", text: "St. Hilary of Poitiers — Augustine's chief Latin Trinitarian source.", rationale: "Wrong. Hilary died in 367, twenty years before Augustine's baptism (387)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "St. Augustine, Confessions IX.6" }],
    },
    {
      id: "cf-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["polycarp-irenaeus"],
      prompt:
        "Polycarp of Smyrna was a disciple of John the Theologian. Which later Father claims to have heard Polycarp personally?",
      choices: [
        { id: "a", text: "St. Irenaeus of Lyon — recorded the meeting in his Letter to Florinus.", rationale: "Preserved in Eusebius EH 5.20. The famous two-link apostolic chain: John → Polycarp → Irenaeus." },
        { id: "b", text: "Tertullian of Carthage — author of the Apologeticus and Against Marcion.", rationale: "Wrong. Tertullian was Latin-speaking North Africa; he had no personal contact with Polycarp." },
        { id: "c", text: "St. Cyprian of Carthage — bishop and martyr under Valerian.", rationale: "Wrong. Cyprian was bishop of Carthage from c. 248; he could not have known Polycarp (martyred 156)." },
        { id: "d", text: "Origen of Alexandria — author of On First Principles.", rationale: "Wrong. Origen was born c. 185, 30 years after Polycarp's death; no contact possible." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Irenaeus, Letter to Florinus (in Eusebius EH 5.20)" }],
    },
    {
      id: "cf-final-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["nicholas-cabasilas"],
      prompt:
        "Who wrote the 14th-century Life in Christ and the Commentary on the Divine Liturgy?",
      choices: [
        { id: "a", text: "Nicholas Cabasilas (~1322-1392) — nephew of Nilus Cabasilas, lay theologian.", rationale: "Masterworks of sacramental theology. Often paired with Palamas as a 14th-century Byzantine renewal." },
        { id: "b", text: "St. Mark of Ephesus (1392-1444) — refused union at Florence in 1439.", rationale: "Wrong. Mark wrote polemics against the Latins at Florence; the Life in Christ is Cabasilas's." },
        { id: "c", text: "St. Gregory Palamas (1296-1359) — author of the Triads and the One Hundred and Fifty Chapters.", rationale: "Wrong. Palamas was the principal hesychast theologian; Cabasilas was his contemporary and admirer." },
        { id: "d", text: "St. Symeon of Thessalonica (~1381-1429) — wrote On the Sacred Liturgy.", rationale: "Wrong, but Symeon of Thessalonica DID write On the Sacred Liturgy and is a real 15th-c. liturgical commentator. Cabasilas is earlier." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Nicholas Cabasilas, The Life in Christ; A Commentary on the Divine Liturgy" }],
    },
    {
      id: "cf-final-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["evagrius"],
      prompt: "Who was Evagrius Ponticus (~345-399)?",
      choices: [
        { id: "a", text: "Pontic monk in the Egyptian desert, disciple of the Cappadocians; pioneer of monastic prayer-theology.", rationale: "Author of the Praktikos and Chapters on Prayer. Some of his more speculative positions were anathematized in 553 alongside Origen's; his ascetical writings remain foundational." },
        { id: "b", text: "Bishop of Antioch in the late 4th century, the major Antiochene exegete.", rationale: "Wrong. The Antiochene school is associated with Diodore of Tarsus and Theodore of Mopsuestia, not Evagrius." },
        { id: "c", text: "A martyr at Sebaste, one of the Forty Soldiers of the Twelfth Legion.", rationale: "Wrong. The Forty Martyrs of Sebaste were 320 AD soldiers; Evagrius is a different historical figure." },
        { id: "d", text: "A 6th-century church historian who continued the work of Eusebius.", rationale: "Wrong, BUT — Evagrius SCHOLASTICUS (~536-594) was a 6th-c. church historian (a different person from Evagrius PONTICUS the monk)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Evagrius Ponticus, Praktikos; Chapters on Prayer" }],
    },
    {
      id: "cf-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["seraphim-of-sarov"],
      prompt: "What was St. Seraphim of Sarov's signature ascetic feat?",
      choices: [
        { id: "a", text: "Praying on a stone outside his hermitage night and day for one thousand days.", rationale: "From 1804-1807. He stood on one rock by day, kneeled on another by night, reciting the publican's prayer continually." },
        { id: "b", text: "Living on a pillar (stylos) outside his monastery in the manner of Symeon the Stylite.", rationale: "Wrong. Stylite asceticism is real (Symeon, Daniel, Alypius), but Seraphim's distinctive practice was the stone vigil." },
        { id: "c", text: "Wandering as an itinerant fool-for-Christ through the cities of Russia.", rationale: "Wrong, but fool-for-Christ asceticism IS real (St. Xenia of Petersburg, St. Basil the Blessed). Seraphim was a monk-hermit, not a fool-for-Christ." },
        { id: "d", text: "Living in a sealed cave alone, communicating with visitors only through a small window.", rationale: "Wrong. Strict enclosure is real (recluse-asceticism), but Seraphim eventually opened his door widely to thousands of visitors." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Life of St. Seraphim of Sarov" }],
    },
    {
      id: "cf-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["khomiakov", "slavophile"],
      prompt: "Who were the principal Slavophile theologians of 19th-century Russia?",
      choices: [
        { id: "a", text: "Alexei Khomiakov (1804-1860) and Ivan Kireyevsky (1806-1856) — articulated 'sobornost' as the Orthodox principle.", rationale: "Their lay theological work shaped 19th and 20th c. Russian thought (Florensky, Bulgakov, Lossky). Khomiakov's The Church Is One is foundational." },
        { id: "b", text: "Leo Tolstoy and Fyodor Dostoevsky — the great Russian novelists with theological themes.", rationale: "Wrong. Tolstoy was excommunicated; Dostoevsky was Orthodox but a novelist, not a Slavophile theologian (though sympathetic)." },
        { id: "c", text: "Georges Florovsky and Alexander Schmemann — the 20th-c. Paris-school theologians.", rationale: "Wrong. Florovsky and Schmemann are 20th-c. émigré theologians, much later than the Slavophiles." },
        { id: "d", text: "Sergei Bulgakov and Nikolai Berdyaev — the religious philosophers of the early 20th c.", rationale: "Wrong. Bulgakov and Berdyaev are 20th-c. Silver Age figures; Slavophiles are early-to-mid 19th c." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Khomiakov, The Church Is One; Kireyevsky, On the Necessity and Possibility of New Principles of Philosophy" }],
    },
  ],
};
