import type { Topic } from "@/lib/types";

export const fathersFinalPack: Topic = {
  id: "fathers-final-pack",
  title: "Fathers — Final Pack",
  summary: "Final MCQs on the Fathers, their disciples, and chains of transmission.",
  learningObjectives: ["Drill remaining patristic facts."],
  primarySources: ["Standard patrology"],
  items: [
    {
      id: "cf-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["ambrose-augustine"],
      prompt: "Which Father baptized Augustine of Hippo?",
      choices: [
        { id: "a", text: "Ambrose of Milan, at the Easter Vigil 387.", rationale: "Correct. Augustine, Confessions IX.6." },
        { id: "b", text: "Pope Damasus" },
        { id: "c", text: "Jerome" },
        { id: "d", text: "Athanasius" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Augustine, Confessions IX" }],
    },
    {
      id: "cf-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["polycarp-irenaeus"],
      prompt: "Polycarp was a disciple of John the Theologian; whom did Polycarp instruct?",
      choices: [
        { id: "a", text: "Irenaeus of Lyon (per Irenaeus's Letter to Florinus)", rationale: "Correct. The famous two-link chain." },
        { id: "b", text: "Tertullian" },
        { id: "c", text: "Cyprian" },
        { id: "d", text: "Origen" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius EH 5.20 (Letter to Florinus)" }],
    },
    {
      id: "cf-final-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["nicholas-cabasilas"],
      prompt: "Who wrote The Life in Christ and the Commentary on the Divine Liturgy in the 14th century?",
      choices: [
        { id: "a", text: "Nicholas Cabasilas (~1322-1392)", rationale: "Correct. Nephew of Nilus Cabasilas; mystical-sacramental theologian." },
        { id: "b", text: "Mark of Ephesus" },
        { id: "c", text: "Gregory Palamas" },
        { id: "d", text: "Photios the Great" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Nicholas Cabasilas, The Life in Christ; A Commentary on the Divine Liturgy" }],
    },
    {
      id: "cf-final-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["evagrius"],
      prompt: "Who was Evagrius Ponticus (~345-399)?",
      choices: [
        { id: "a", text: "Pontic monk in the Egyptian desert; disciple of the Cappadocians; pioneer of monastic prayer theology; later anathematized along with Origen for some positions but his ascetical writings preserved much of the tradition (Praktikos, Chapters on Prayer).", rationale: "Correct." },
        { id: "b", text: "A martyr at Sebaste" },
        { id: "c", text: "A bishop of Antioch" },
        { id: "d", text: "A 6th-century historian" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Evagrius Ponticus, Praktikos; Chapters on Prayer" }],
    },
    {
      id: "cf-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["seraphim-of-sarov"],
      prompt: "What was St. Seraphim of Sarov's special form of asceticism?",
      choices: [
        { id: "a", text: "Praying on a stone night and day for 1000 days, eating wild grasses; later as a hermit and a starets (elder).", rationale: "Correct. His night-and-day stone vigil is famous." },
        { id: "b", text: "Stylite living on a pillar" },
        { id: "c", text: "Itinerant preacher with no fixed home" },
        { id: "d", text: "Hermit in a cave alone" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Life of St. Seraphim of Sarov" }],
    },
    {
      id: "cf-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["khomiakov-soloviev"],
      prompt: "Who were the principal Slavophile theologians of 19th-century Russia?",
      choices: [
        { id: "a", text: "Alexei Khomiakov (1804-60) and Ivan Kireyevsky (1806-56) — formulated Orthodox ecclesiology as 'sobornost' (catholicity, communion); influenced Florensky, Bulgakov, Lossky.", rationale: "Correct." },
        { id: "b", text: "Tolstoy and Dostoevsky alone" },
        { id: "c", text: "Florovsky and Schmemann" },
        { id: "d", text: "Bulgakov and Berdyaev" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Khomiakov, The Church Is One" }],
    },
  ],
};
