import type { Topic } from "@/lib/types";

export const fathersFactsPack: Topic = {
  id: "fathers-facts-pack",
  title: "Fathers — Quick Facts",
  summary: "MCQ pack on the Fathers and their works.",
  learningObjectives: ["Drill author-to-work matches."],
  primarySources: ["Standard patrology"],
  items: [
    {
      id: "cf-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["irenaeus"],
      prompt: "Which Father wrote Against Heresies in five books?",
      choices: [
        { id: "a", text: "Irenaeus of Lyon (~AD 180)", rationale: "Correct." },
        { id: "b", text: "Justin Martyr" },
        { id: "c", text: "Origen" },
        { id: "d", text: "Athanasius" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Irenaeus, Against Heresies (Adversus Haereses)" }],
    },
    {
      id: "cf-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["athanasius"],
      prompt: "Which Father wrote On the Incarnation?",
      choices: [
        { id: "a", text: "Athanasius of Alexandria", rationale: "Correct. Companion to Against the Heathen, c. AD 318." },
        { id: "b", text: "Cyril of Alexandria" },
        { id: "c", text: "Gregory of Nazianzus" },
        { id: "d", text: "Maximus the Confessor" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Athanasius, De Incarnatione Verbi Dei" }],
    },
    {
      id: "cf-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["john-damascus"],
      prompt: "Who wrote the Exact Exposition of the Orthodox Faith and the Three Treatises on Divine Images?",
      choices: [
        { id: "a", text: "John of Damascus (~AD 730)", rationale: "Correct." },
        { id: "b", text: "Symeon the New Theologian" },
        { id: "c", text: "Photios the Great" },
        { id: "d", text: "Gregory Palamas" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John of Damascus, Fount of Knowledge; On the Divine Images" }],
    },
    {
      id: "cf-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["gregory-palamas"],
      prompt: "Which Father is famous for the essence/energies distinction and the defense of hesychasm?",
      choices: [
        { id: "a", text: "Gregory Palamas (1296-1359)", rationale: "Correct. Triads in Defense of the Holy Hesychasts." },
        { id: "b", text: "Symeon the New Theologian" },
        { id: "c", text: "Nicholas Cabasilas" },
        { id: "d", text: "Mark of Ephesus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Gregory Palamas, Triads in Defense of the Holy Hesychasts" }],
    },
    {
      id: "cf-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["chrysostom"],
      prompt: "Which Father composed the Divine Liturgy used most often in Orthodox churches?",
      choices: [
        { id: "a", text: "John Chrysostom (the Liturgy bearing his name)", rationale: "Correct. The 'ordinary' Sunday Liturgy in Orthodoxy." },
        { id: "b", text: "Basil the Great (used 10 times per year)" },
        { id: "c", text: "James of Jerusalem" },
        { id: "d", text: "Gregory the Dialogist (Presanctified)" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Divine Liturgy of St. John Chrysostom" }],
    },
    {
      id: "cf-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["philokalia"],
      prompt: "Which 19th-century Russian saint translated the Philokalia into Russian?",
      choices: [
        { id: "a", text: "Theophan the Recluse (1815-1894)", rationale: "Correct. Five-volume Dobrotolyubie." },
        { id: "b", text: "Seraphim of Sarov" },
        { id: "c", text: "Ignatius Brianchaninov" },
        { id: "d", text: "John of Kronstadt" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Dobrotolyubie (Russian Philokalia), Theophan the Recluse trans." }],
    },
    {
      id: "cf-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["maximus", "ambigua"],
      prompt: "Which Father's Ambigua and Quaestiones ad Thalassium are masterpieces of patristic exegesis and synthesis?",
      choices: [
        { id: "a", text: "Maximus the Confessor (~580-662)", rationale: "Correct." },
        { id: "b", text: "Cyril of Alexandria" },
        { id: "c", text: "Anastasius of Sinai" },
        { id: "d", text: "Sophronius of Jerusalem" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Maximus the Confessor, Ambigua; Quaestiones ad Thalassium" }],
    },
  ],
};
