import type { Topic } from "@/lib/types";

export const heresiesFinalPack: Topic = {
  id: "heresies-final-pack",
  title: "Heresies — Final Pack",
  summary: "Final MCQs on heresies and refuters.",
  learningObjectives: ["Master the full heresy roster."],
  primarySources: ["Standard heresiology references"],
  items: [
    {
      id: "her-final-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["donatist-detail"],
      prompt: "Why did the Donatists reject the validity of sacraments performed by 'traditores'?",
      choices: [
        { id: "a", text: "They held the sacraments' validity depended on the moral worthiness of the minister; bishops who had handed over Scriptures during persecution were tainted, and their consecrations invalid.", rationale: "Correct. Refuted by Augustine in his works against the Donatists." },
        { id: "b", text: "They believed the Pope alone consecrates" },
        { id: "c", text: "They wanted liturgical reform" },
        { id: "d", text: "They denied infant baptism" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Augustine, Against the Donatists" }],
    },
    {
      id: "her-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["montanism"],
      prompt: "What is Montanism?",
      choices: [
        { id: "a", text: "A 2nd-c. apocalyptic charismatic movement (Montanus, Priscilla, Maximilla) claiming new prophetic revelations beyond the apostolic deposit. Rejected by the catholic Church; Tertullian joined it late in life.", rationale: "Correct." },
        { id: "b", text: "An Eastern monastic movement" },
        { id: "c", text: "A Gnostic school" },
        { id: "d", text: "An Arian sect" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius EH 5.16-19" }],
    },
    {
      id: "her-final-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["filioquism-modern"],
      prompt: "Has the Roman Catholic Church ever removed the Filioque from its officially published Symbol?",
      choices: [
        { id: "a", text: "No, but the Latin Mass since the 1995 'Greek and Latin Traditions Regarding the Procession of the Holy Spirit' (Vatican statement) and the 1965 Concordat-style gestures have begun to soften the issue; the Catholic Church has sometimes recited the Creed without Filioque (e.g., at JPII's Mass with Ecumenical Patriarch Demetrios).", rationale: "Correct. The dogmatic doctrine remains, but the liturgical insertion is sometimes omitted in inter-Christian settings." },
        { id: "b", text: "Yes, in 1054" },
        { id: "c", text: "Yes, in 1965" },
        { id: "d", text: "Yes, after Vatican II in all liturgy" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "PCPCU, 'The Greek and Latin Traditions Regarding the Procession of the Holy Spirit' (1995)" }],
    },
    {
      id: "her-final-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["liberalism"],
      prompt: "What is 'theological liberalism' as the Orthodox use the term?",
      choices: [
        { id: "a", text: "Post-Enlightenment Protestant accommodation of Christian doctrine to scientific naturalism, historical criticism, and modern moral sensibilities — leading to denial of miracles, the Resurrection's historicity, and traditional sexual ethics.", rationale: "Correct. From Schleiermacher and Harnack onward." },
        { id: "b", text: "A medieval movement" },
        { id: "c", text: "A type of Orthodox jurisdiction" },
        { id: "d", text: "An ascetic school" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Adolf von Harnack, Das Wesen des Christentums (1900)" }],
    },
    {
      id: "her-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["modalism-detail"],
      prompt: "Which 3rd-century Pope was perceived as soft on Modalism, leading to controversy with his Eastern namesake Dionysius of Alexandria?",
      choices: [
        { id: "a", text: "Pope Dionysius of Rome (~AD 260)", rationale: "Correct. Their correspondence helped clarify the East-West Trinitarian vocabulary." },
        { id: "b", text: "Pope Liberius" },
        { id: "c", text: "Pope Sylvester" },
        { id: "d", text: "Pope Julius" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Athanasius, On the Decrees of Nicaea; correspondence preserved in Athanasius" }],
    },
  ],
};
