import type { Topic } from "@/lib/types";

export const heresyFactsPack: Topic = {
  id: "heresy-facts-pack",
  title: "Heresy Quick-Recall",
  summary: "MCQ pack on heresies, dates, and refuters.",
  learningObjectives: ["Match each heresy to its date and principal opponent."],
  primarySources: ["Standard church history; conciliar acts"],
  items: [
    {
      id: "her-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["arius"],
      prompt: "Who was Arius, and what did he teach?",
      choices: [
        { id: "a", text: "An Alexandrian presbyter (~256-336) who taught that the Son is a creature: 'there was a time when He was not.'", rationale: "Condemned at Nicaea I (325). The Cappadocians completed the refutation at Constantinople I (381)." },
        { id: "b", text: "Bishop of Constantinople in the 320s, deposed at Nicaea for taking the Father's title for himself.", rationale: "Wrong. Arius was a presbyter (priest), not a bishop. He served in Alexandria, not Constantinople." },
        { id: "c", text: "A Roman senator and lay theologian who proposed a hierarchical Trinity to Constantine.", rationale: "Wrong. Arius was a Greek-speaking Alexandrian clergyman, not a Roman senator." },
        { id: "d", text: "Patriarch of Antioch who defended the divinity of the Son against early adoptionists.", rationale: "Wrong. Arius did the OPPOSITE — he denied the Son's divinity. And he was Alexandrian." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Athanasius, De Synodis 15-16; Acts of Nicaea I (325)" }],
    },
    {
      id: "her-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["nestorius"],
      prompt: "Who was Nestorius?",
      choices: [
        { id: "a", text: "Patriarch of Constantinople (consecrated 428) who refused the title Theotokos to Mary.", rationale: "Condemned at Ephesus (431). Cyril of Alexandria's Twelve Anathemas were ratified at the council." },
        { id: "b", text: "Bishop of Rome who supported Eutyches against Pope Leo's Tome.", rationale: "Wrong. No bishop of Rome ever supported Eutyches; Leo I wrote the Tome AGAINST Eutyches in 449." },
        { id: "c", text: "Bishop of Alexandria deposed by Cyril for monophysite tendencies.", rationale: "Wrong. Cyril deposed Nestorius (of Constantinople), not vice versa. And Nestorius's error was the opposite of Eutyches's." },
        { id: "d", text: "An Antiochene ascetic whose two-natures Christology was later vindicated at Chalcedon.", rationale: "Wrong. Chalcedon (451) vindicated CYRILLINE Christology against Eutyches, and rejected Nestorius's split-person reading." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Ephesus (431); Cyril of Alexandria, Twelve Anathemas" }],
    },
    {
      id: "her-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["pelagius"],
      prompt: "Who was Pelagius?",
      choices: [
        { id: "a", text: "A British monk (~360-420) who denied original sin and held that the human will is sufficient to choose good without grace.", rationale: "Condemned at Carthage (418) and Ephesus (431). Augustine's principal opponent in the West." },
        { id: "b", text: "A Spanish theologian whose semi-Pelagian writings were later corrected by John Cassian.", rationale: "Wrong. Cassian wrote AGAINST a particularly harsh Augustinianism, not against Pelagius (who was British). Cassian's own position is closer to Orthodox synergy than to Pelagius." },
        { id: "c", text: "An Egyptian hermit whose ascetical writings emphasized self-mortification over grace.", rationale: "Wrong. Egyptian desert fathers (Anthony, Macarius) emphasized synergy of grace and effort; Pelagius was British." },
        { id: "d", text: "An Armenian bishop whose anti-Augustinian writings were preserved in Ethiopian translation.", rationale: "Wrong. Pelagius wrote in Latin and resided in Rome and the Mediterranean; he is not Armenian." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "St. Augustine, Anti-Pelagian Writings; Carthage 418, Ephesus 431" }],
    },
    {
      id: "her-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["donatism"],
      prompt: "What was Donatism?",
      choices: [
        { id: "a", text: "A 4th-century North African schism refusing communion with clergy who had handed over the Scriptures during the Diocletianic persecution.", rationale: "Held that sacraments depend on the moral worthiness of the minister. Augustine wrote extensively against it." },
        { id: "b", text: "A 5th-century North African doctrine of double predestination, condemned at Orange (529).", rationale: "Wrong. Double-predestinarianism is associated with Gottschalk (9th c.), not with Donatus (4th c.)." },
        { id: "c", text: "A 3rd-century Egyptian movement that denied the validity of infant baptism.", rationale: "Wrong. Infant baptism was universally affirmed in the 3rd c. (Hippolytus, Origen, Cyprian). Donatism is a different controversy." },
        { id: "d", text: "A 6th-century Spanish liturgical reform under Bishop Donatus of Cordoba.", rationale: "Wrong. Donatism is a 4th-c. African schism, not a Spanish liturgical reform." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "St. Augustine, Against the Donatists; Letters 89, 93, 185" }],
    },
    {
      id: "her-fp-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["barlaam"],
      prompt: "Who was Barlaam, the principal opponent of Gregory Palamas?",
      choices: [
        { id: "a", text: "Barlaam of Calabria (~1290-1348), a Greek-Italian philosopher-monk who later joined the Latin Church.", rationale: "Criticized the Athonite hesychasts for claiming experiential knowledge of the divine Light. Palamas's Triads are the reply." },
        { id: "b", text: "A 13th-century Russian heretic associated with the Strigolniki movement of Novgorod.", rationale: "Wrong. The Strigolniki were a real 14th-c. Russian movement, but the controversy with Palamas is Greek-Italian, not Russian." },
        { id: "c", text: "A Bulgarian Bogomil priest exiled to Mt. Athos in the 12th century.", rationale: "Wrong. Bogomils were Bulgarian dualists (10th c. onward), but Barlaam-Palamas is a 14th-c. controversy about hesychasm." },
        { id: "d", text: "A Western Crusader-bishop installed at Constantinople after 1204.", rationale: "Wrong. Latin bishops were installed at Constantinople from 1204-1261, but Barlaam comes a century later and was a different figure." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "St. Gregory Palamas, Triads in Defense of the Holy Hesychasts" }],
    },
    {
      id: "her-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["iconoclast-emperors"],
      prompt: "Which emperor inaugurated the first wave of Byzantine iconoclasm (726)?",
      choices: [
        { id: "a", text: "Leo III the Isaurian (r. 717-741) — issued the first edict ordering icons removed.", rationale: "Theophanes the Confessor records the 726 act of breaking the Chalke gate icon of Christ in Constantinople." },
        { id: "b", text: "Constantine V Copronymos (r. 741-775) — son and successor of Leo III; intensified the persecution.", rationale: "Wrong. Constantine V DID intensify iconoclasm (Council of Hieria 754), but his father Leo III began it." },
        { id: "c", text: "Leo V the Armenian (r. 813-820) — inaugurated the SECOND wave of iconoclasm after Nicaea II.", rationale: "Wrong. Leo V began the second wave (815) AFTER icon-restoration by Nicaea II (787). The FIRST wave was Leo III in 726." },
        { id: "d", text: "Theophilus (r. 829-842) — the last iconoclast emperor, whose widow Theodora restored icons in 843.", rationale: "Wrong. Theophilus was the LAST iconoclast emperor; his death (842) led to the Triumph of Orthodoxy (843), but he did not begin iconoclasm." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Theophanes Confessor, Chronicle AM 6217-6218" }],
    },
    {
      id: "her-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["theophilanthropy"],
      prompt: "What was 'Theophilanthropy'?",
      choices: [
        { id: "a", text: "A short-lived deist religion promoted by the French Revolutionary Directory (1796-1801) as a Christianity-substitute.", rationale: "Held public ceremonies in former Catholic churches. Suppressed under Napoleon's Concordat with Pius VII (1801)." },
        { id: "b", text: "An early Christian heresy taught by the 2nd-c. apologist Theophilus of Antioch.", rationale: "Wrong. Theophilus of Antioch (~AD 180) was an orthodox apologist who first used the word Trinitas ('trias') — not the founder of a heresy." },
        { id: "c", text: "A 19th-century Russian sectarian movement of itinerant penitents (the 'Wanderers').", rationale: "Wrong, although Russian Wanderers (Stranniki) ARE a real 19th-c. movement (a branch of Bezpopovsy Old Believers). Different thing." },
        { id: "d", text: "A 12th-century Byzantine philosophical school synthesizing Plato with Trinitarian theology.", rationale: "Wrong. 12th-c. Byzantine philosophy included John Italos and Eustratios of Nicaea, but 'theophilanthropy' is a French-Revolutionary deist movement." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Various histories of the French Revolutionary religious policy (1796-1801)" }],
    },
  ],
};
