import type { Topic } from "@/lib/types";

export const heresyFactsPack: Topic = {
  id: "heresy-facts-pack",
  title: "Heresy Quick-Recall",
  summary: "MCQ pack on heresies, dates, and refuters.",
  learningObjectives: ["Match each heresy to its date and principal opponent."],
  primarySources: ["Standard church history; conciliar acts"],
  items: [
    {
      id: "her-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["arius"],
      prompt: "Who was Arius, and what did he teach?",
      choices: [
        { id: "a", text: "An Alexandrian presbyter (c. 256-336) who taught the Son is a creature: 'there was a time when He was not.'", rationale: "Correct." },
        { id: "b", text: "Bishop of Constantinople" },
        { id: "c", text: "A Roman senator" },
        { id: "d", text: "Patriarch of Antioch" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Athanasius, De Synodis 15-16" }],
    },
    {
      id: "her-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["nestorius"],
      prompt: "Who was Nestorius?",
      choices: [
        { id: "a", text: "Patriarch of Constantinople (consecrated 428), who refused the title Theotokos to Mary. Condemned at Ephesus 431.", rationale: "Correct." },
        { id: "b", text: "Bishop of Rome" },
        { id: "c", text: "Bishop of Alexandria" },
        { id: "d", text: "An ascetic of the desert" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Ephesus (431)" }],
    },
    {
      id: "her-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["pelagius"],
      prompt: "Who was Pelagius?",
      choices: [
        { id: "a", text: "A British monk (~360-420) who denied original sin and held human will sufficient to choose good without grace.", rationale: "Correct. Condemned at Carthage 418 and Ephesus 431." },
        { id: "b", text: "A Spanish theologian" },
        { id: "c", text: "An Egyptian hermit" },
        { id: "d", text: "An Armenian bishop" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Augustine, Anti-Pelagian Writings" }],
    },
    {
      id: "her-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["donatism"],
      prompt: "What was Donatism, and what is the Orthodox response?",
      choices: [
        { id: "a", text: "A 4th-century North African schism that refused communion with clergy who had handed over Scriptures during the Diocletianic persecution; held that sacraments depended on the worthiness of the minister.", rationale: "Correct. Augustine wrote extensively against Donatism." },
        { id: "b", text: "A doctrine of original sin" },
        { id: "c", text: "A monastic reform" },
        { id: "d", text: "A view on the Filioque" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Augustine, Against the Donatists" }],
    },
    {
      id: "her-fp-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["barlaam"],
      prompt: "Who was Barlaam, the principal opponent of Gregory Palamas?",
      choices: [
        { id: "a", text: "Barlaam of Calabria (~1290-1348), a Greek-speaking philosopher-monk who later joined the Latin Church; criticized hesychasts for claiming experiential knowledge of the divine Light.", rationale: "Correct." },
        { id: "b", text: "A Russian heretic" },
        { id: "c", text: "A Bulgarian Bogomil" },
        { id: "d", text: "A Western Crusader-bishop" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Gregory Palamas, Triads — written against Barlaam" }],
    },
    {
      id: "her-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["iconoclast-emperors"],
      prompt: "Which emperor began the first wave of Byzantine iconoclasm (726)?",
      choices: [
        { id: "a", text: "Leo III the Isaurian", rationale: "Correct." },
        { id: "b", text: "Constantine V" },
        { id: "c", text: "Leo V the Armenian" },
        { id: "d", text: "Theophilus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Theophanes Confessor, Chronicle AM 6217-6218" }],
    },
    {
      id: "her-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["theophilanthropy"],
      prompt: "What was 'Theophilanthropy'?",
      choices: [
        { id: "a", text: "A short-lived deist religion of the French Revolution (1796-1801) promoted by the Directory as a replacement for Christianity.", rationale: "Correct." },
        { id: "b", text: "An early Christian heresy" },
        { id: "c", text: "A Russian sectarian movement" },
        { id: "d", text: "A Byzantine philosophical school" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "French Revolutionary religious policies (1796-1801)" }],
    },
  ],
};
