import type { Topic } from "@/lib/types";

export const foundationFactsPack: Topic = {
  id: "foundation-facts-pack",
  title: "Foundational Doctrine — Quick Recall",
  summary: "MCQ pack on foundational dogma.",
  learningObjectives: ["Drill central definitions."],
  primarySources: ["Symbol of Faith; Acts of the Councils"],
  items: [
    {
      id: "ft-fp-001",
      kind: "mcq",
      difficulty: 1,
      tags: ["creed"],
      prompt: "How many articles are in the Niceno-Constantinopolitan Symbol?",
      choices: [
        { id: "a", text: "Twelve", rationale: "Correct. Often divided into 12 articles for catechesis." },
        { id: "b", text: "Ten" },
        { id: "c", text: "Seven" },
        { id: "d", text: "Three" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Niceno-Constantinopolitan Symbol (381), traditional division" }],
    },
    {
      id: "ft-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["theotokos"],
      prompt: "What does 'Theotokos' literally mean in Greek?",
      choices: [
        { id: "a", text: "God-Bearer (the one who gave birth to God)", rationale: "Correct." },
        { id: "b", text: "Mother of Christ only" },
        { id: "c", text: "All-Holy One" },
        { id: "d", text: "Ever-Virgin" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Ephesus (431)" }],
    },
    {
      id: "ft-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["hypostasis"],
      prompt: "How many hypostases are there in the Holy Trinity?",
      choices: [
        { id: "a", text: "Three — Father, Son, Holy Spirit, each fully God, of one essence.", rationale: "Correct." },
        { id: "b", text: "One — different modes of the same divine Person" },
        { id: "c", text: "Two" },
        { id: "d", text: "Four" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Symbol of Faith; Cappadocian writings" }],
    },
    {
      id: "ft-fp-004",
      kind: "mcq",
      difficulty: 2,
      tags: ["natures-of-christ"],
      prompt: "How many natures does Christ have?",
      choices: [
        { id: "a", text: "Two — divine and human — fully united in one Person.", rationale: "Correct. Chalcedon (451)." },
        { id: "b", text: "One — divine only after the Resurrection" },
        { id: "c", text: "One — a divine-human hybrid (the Monophysite view, rejected)" },
        { id: "d", text: "Three" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Definition of Chalcedon (451)" }],
    },
    {
      id: "ft-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["wills-of-christ"],
      prompt: "How many wills does Christ have?",
      choices: [
        { id: "a", text: "Two — divine and human — corresponding to His two natures (Constantinople III, 681).", rationale: "Correct." },
        { id: "b", text: "One — only the divine, with the human will absorbed (Monothelite view, condemned)" },
        { id: "c", text: "One — a hybrid divine-human will" },
        { id: "d", text: "Three — one for each Person and one shared" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople III (680-681)" }],
    },
    {
      id: "ft-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["divine-energies"],
      prompt: "In Orthodox theology, what do creatures share by participation?",
      choices: [
        { id: "a", text: "God's uncreated energies — never His essence.", rationale: "Correct. Palamite distinction." },
        { id: "b", text: "God's essence directly, by grace" },
        { id: "c", text: "Nothing — created grace mediates" },
        { id: "d", text: "Different parts of God depending on the saint" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synodal Tome of 1351" }],
    },
    {
      id: "ft-fp-007",
      kind: "mcq",
      difficulty: 2,
      tags: ["theosis"],
      prompt: "What is the Orthodox final goal (telos) of human salvation?",
      choices: [
        { id: "a", text: "Theosis — to become 'partakers of the divine nature' (2 Pet 1:4), deified by grace.", rationale: "Correct." },
        { id: "b", text: "Forensic justification only" },
        { id: "c", text: "The cessation of bodily existence" },
        { id: "d", text: "Reincarnation into a higher being" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "2 Peter 1:4; Athanasius, De Incarnatione 54.3" }],
    },
  ],
};
