import type { Topic } from "@/lib/types";

export const foundationFactsPack: Topic = {
  id: "foundation-facts-pack",
  title: "Foundational Doctrine — Quick Recall",
  summary: "MCQ pack on foundational dogma.",
  learningObjectives: ["Drill central definitions."],
  primarySources: ["Symbol of Faith; Acts of the Councils"],
  items: [
    {
      id: "ft-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["creed"],
      prompt: "How many articles is the Niceno-Constantinopolitan Symbol traditionally divided into?",
      choices: [
        { id: "a", text: "Twelve — for catechetical division and recitation.", rationale: "Common division: 1) one God Father; 2) one Lord Jesus Christ; 3) incarnation; 4) crucifixion; 5) resurrection; 6) ascension; 7) judgment; 8) Holy Spirit; 9) Church; 10) baptism; 11) resurrection of dead; 12) life of age to come." },
        { id: "b", text: "Ten — by analogy with the Ten Commandments.", rationale: "Wrong. The traditional Christian division of the Creed is twelve articles, not ten." },
        { id: "c", text: "Seven — corresponding to the Seven Ecumenical Councils.", rationale: "Wrong. There are seven Councils, but the Symbol is divided into twelve articles." },
        { id: "d", text: "Three — corresponding to the three Persons of the Trinity.", rationale: "Wrong. The Symbol can be divided macro-structurally into three Trinitarian sections, but the traditional CATECHETICAL division is twelve." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Niceno-Constantinopolitan Symbol (381), traditional catechetical division" }],
    },
    {
      id: "ft-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["theotokos"],
      prompt: "What does the Greek title 'Theotokos' literally mean?",
      choices: [
        { id: "a", text: "God-Bearer — the one who bore God in the flesh.", rationale: "From theos (God) + tokos (bearer/begetter). Dogmatically affirmed at Ephesus (431) against Nestorius." },
        { id: "b", text: "Christ-Bearer (Christotokos) — Nestorius's preferred alternative title.", rationale: "Wrong. Nestorius proposed CHRISTOTOKOS as a substitute, but Theotokos was affirmed against him." },
        { id: "c", text: "All-Holy One (Panagia) — referring to Mary's complete sanctity.", rationale: "Wrong. Panagia is a separate Marian title (All-Holy); Theotokos specifically means God-Bearer." },
        { id: "d", text: "Ever-Virgin (Aeiparthenos) — referring to her perpetual virginity.", rationale: "Wrong. Aeiparthenos is yet another Marian title (Ever-Virgin, defined at Constantinople II); Theotokos means God-Bearer." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Ephesus (431)" }],
    },
    {
      id: "ft-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["hypostasis"],
      prompt: "How many Hypostases are there in the Holy Trinity?",
      choices: [
        { id: "a", text: "Three — Father, Son, and Holy Spirit; each fully God; of one essence (ousia).", rationale: "The Cappadocian formula: mia ousia, treis hypostaseis. Each Person is distinct in personal relations, identical in essence." },
        { id: "b", text: "One — three modes (Father, Son, Spirit) of a single divine Person.", rationale: "Wrong. This is Modalism / Sabellianism, condemned in the 3rd century. The Trinity is THREE Hypostases, not one Hypostasis in three modes." },
        { id: "c", text: "Two — the Father and the Word who proceeds from Him (the Spirit being an impersonal divine energy).", rationale: "Wrong. This is binitarianism, condemned by the Pneumatomachi controversy at Constantinople I (381). The Spirit is a third Hypostasis." },
        { id: "d", text: "Four — adding Sophia (Wisdom) as a fourth Hypostasis after the Cappadocian model.", rationale: "Wrong. Sophiology (Bulgakov, Florensky) is a contested 20th-c. Russian speculation; traditional Triadology is three Hypostases." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Symbol of Faith; Basil, Letter 38; Gregory the Theologian, Oration 31" }],
    },
    {
      id: "ft-fp-004",
      kind: "mcq",
      difficulty: 2,
      tags: ["natures-of-christ"],
      prompt: "How many natures does Christ have, per Chalcedon (451)?",
      choices: [
        { id: "a", text: "Two — divine and human — united in one Person without confusion or separation.", rationale: "Chalcedonian Definition. Two natures (physeis) in one Person (hypostasis) — against both Eutyches (one mixed nature) and Nestorius (two persons)." },
        { id: "b", text: "One — the human absorbed by the divine after the Resurrection.", rationale: "Wrong. This is Monophysitism (Eutyches), condemned at Chalcedon." },
        { id: "c", text: "One — a 'theandric' (divine-human) hybrid nature created by the Incarnation.", rationale: "Wrong. This too is monophysite; Chalcedon rejected any 'mixture' or 'confusion' of natures." },
        { id: "d", text: "Three — a divine, a human, and a sanctified angelic 'mediator' nature.", rationale: "Wrong. No tradition has taught this. Two natures, one Person." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Definition of Chalcedon (451)" }],
    },
    {
      id: "ft-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["wills-of-christ"],
      prompt: "How many wills does Christ have, per Constantinople III (681)?",
      choices: [
        { id: "a", text: "Two — divine and human — corresponding to His two natures, the human freely conforming to the divine.", rationale: "Dyothelitism. In Gethsemane the human will submits: 'not my will but Thine be done' (Lk 22:42). What is not assumed is not healed (Gregory the Theologian)." },
        { id: "b", text: "One — the divine will, with the human will absorbed in the union.", rationale: "Wrong. This is Monothelitism, condemned at Constantinople III. It denies the integrity of Christ's human nature." },
        { id: "c", text: "One — a 'theandric' (divine-human) hybrid will.", rationale: "Wrong. Pseudo-Dionysius once used 'theandric' loosely, but the conciliar dogma is TWO distinct wills united in one Person without confusion." },
        { id: "d", text: "Three — one for the divine nature, one for the human nature, and one for the personal subject.", rationale: "Wrong. Wills (natural wills, thelēmata physika) follow natures, not persons. Two natures = two wills." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople III (680-681)" }],
    },
    {
      id: "ft-fp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["divine-energies"],
      prompt:
        "In Orthodox theology (per Palamas), what does the creature share with God by participation?",
      choices: [
        { id: "a", text: "God's uncreated energies — never His essence, which is unparticipable.", rationale: "Palamite distinction, dogmatized at the Hesychast councils 1341-51. Roots in Basil (Letter 234), Maximus, the Cappadocians." },
        { id: "b", text: "God's essence itself, by direct sharing through sanctifying grace.", rationale: "Wrong. The essence is incommunicable. To share the essence would make creatures into gods by nature (Mormonism's exaltation, Hindu absorption). Orthodoxy: by GRACE (energies), not BY NATURE (essence)." },
        { id: "c", text: "Nothing of God Himself — only created grace, a medium gift sufficient for salvation.", rationale: "Wrong. This is the Thomist 'created grace' position. Orthodoxy holds that we partake of UNCREATED energies, real participation in God Himself." },
        { id: "d", text: "Different aspects of God depending on which saint participates and to what degree.", rationale: "Wrong. The same uncreated energies are shared by all saints; degrees vary by capacity, not by what is shared." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synodal Tome of 1351; Basil, Letter 234; Palamas, Triads" }],
    },
    {
      id: "ft-fp-007",
      kind: "mcq",
      difficulty: 3,
      tags: ["theosis"],
      prompt: "What is the Orthodox final goal (telos) of human salvation?",
      choices: [
        { id: "a", text: "Theosis — becoming 'partakers of the divine nature' (2 Pet 1:4), deified by grace.", rationale: "Athanasius: 'God became man that man might become god' (On the Incarnation 54.3). Maximus, Palamas, the Cappadocians — the patristic mainstream." },
        { id: "b", text: "Forensic justification — being declared righteous, with sin's penalty paid in Christ's death.", rationale: "Wrong. Forensic-imputative justification is the Lutheran-Reformed model; Orthodoxy is participatory and transformative." },
        { id: "c", text: "Cessation of bodily existence in disembodied beatific contemplation of God.", rationale: "Wrong. This is a Platonic or Origenist tendency, condemned at Constantinople II (553). Orthodox eschatology confesses bodily resurrection." },
        { id: "d", text: "Reincarnation into ever higher orders of being until ontological union with God.", rationale: "Wrong. Reincarnation has no place in Christian eschatology (Heb 9:27 — appointed once to die). Theosis is by grace, not by transmigration." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "2 Peter 1:4; Athanasius, On the Incarnation 54.3" }],
    },
  ],
};
