import type { Topic } from "@/lib/types";

export const foundationsFinalPack: Topic = {
  id: "foundations-final-pack",
  title: "Foundations — Final Pack",
  summary: "Final MCQs on foundational doctrine.",
  learningObjectives: ["Drill remaining foundational vocabulary."],
  primarySources: ["Symbol of Faith; conciliar texts"],
  items: [
    {
      id: "ft-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["jesus-name"],
      prompt: "What does the name 'Jesus' mean in Hebrew?",
      choices: [
        { id: "a", text: "'Yeshua' / 'Yehoshua' — 'The Lord saves' (Mt 1:21)", rationale: "Correct." },
        { id: "b", text: "'Anointed One'" },
        { id: "c", text: "'Holy Father'" },
        { id: "d", text: "'Son of Man'" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Matthew 1:21" }],
    },
    {
      id: "ft-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["christ-title"],
      prompt: "What does 'Christ' mean?",
      choices: [
        { id: "a", text: "Christos — 'Anointed One' (Greek for the Hebrew 'Messiah')", rationale: "Correct." },
        { id: "b", text: "'Son of Man'" },
        { id: "c", text: "A personal name" },
        { id: "d", text: "'Teacher'" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 1:41" }],
    },
    {
      id: "ft-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["seven-fold-gifts-spirit"],
      prompt: "Where in Scripture are the seven gifts of the Holy Spirit enumerated?",
      choices: [
        { id: "a", text: "Isaiah 11:2-3 — wisdom, understanding, counsel, might, knowledge, fear of the Lord, piety (Greek septuagint adds piety; the Hebrew has six, the LXX seven).", rationale: "Correct." },
        { id: "b", text: "1 Corinthians 12" },
        { id: "c", text: "Galatians 5:22-23" },
        { id: "d", text: "Revelation 1" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Isaiah 11:2-3 (LXX)" }],
    },
    {
      id: "ft-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["sermon-on-mount"],
      prompt: "How many Beatitudes does the Lord pronounce in Matthew 5?",
      choices: [
        { id: "a", text: "Nine (or eight, depending on whether vv. 11-12 are counted as one or two)", rationale: "Correct. Mt 5:3-12." },
        { id: "b", text: "Four" },
        { id: "c", text: "Ten" },
        { id: "d", text: "Seven" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Matthew 5:3-12" }],
    },
    {
      id: "ft-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["love"],
      prompt: "What three Greek words for love does the New Testament use?",
      choices: [
        { id: "a", text: "Agape (self-giving love), philia (brotherly affection), eros (used twice in LXX, not in NT)", rationale: "Correct. Agape is the dominant NT word; philia (Jn 21:15-17 contrast); eros not used. C.S. Lewis added storge (familial affection) from broader Greek." },
        { id: "b", text: "Caritas, dilectio, amor" },
        { id: "c", text: "Hesed, ahavah, racham" },
        { id: "d", text: "Agape, eros, charitas" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 21:15-17; Romans 12; C.S. Lewis, The Four Loves" }],
    },
  ],
};
