import type { Topic } from "@/lib/types";

export const foundationsFinalPack: Topic = {
  id: "foundations-final-pack",
  title: "Foundations — Final Pack",
  summary: "Final MCQs on foundational doctrine.",
  learningObjectives: ["Drill remaining foundational vocabulary."],
  primarySources: ["Symbol of Faith; conciliar texts"],
  items: [
    {
      id: "ft-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["jesus-name"],
      prompt: "What does the name 'Jesus' (Hebrew: Yeshua / Yehoshua) literally mean?",
      choices: [
        { id: "a", text: "'The Lord saves' (Yahweh-shua) — explained by the angel in Mt 1:21.", rationale: "Same name as Joshua son of Nun. The angel: 'thou shalt call his name JESUS: for he shall save his people from their sins.'" },
        { id: "b", text: "'Anointed One' — equivalent to the Hebrew Mashiach.", rationale: "Wrong. That is the meaning of CHRISTOS / Messiah, not Jesus. Jesus is the personal name; Christ is the title." },
        { id: "c", text: "'Holy Father' — the Aramaic Abba used by the early Christians.", rationale: "Wrong. Abba ('Father') is used in Mk 14:36, Rom 8:15, Gal 4:6, but is not the meaning of Jesus." },
        { id: "d", text: "'Son of Man' (bar enasha) — Daniel's title used by Christ Himself.", rationale: "Wrong. 'Son of Man' is a title Christ uses for Himself (Mk 8:31 etc.), but it is not the meaning of His name Jesus." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Matthew 1:21" }],
    },
    {
      id: "ft-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["christ-title"],
      prompt: "What does the title 'Christ' (Greek Christos) literally mean?",
      choices: [
        { id: "a", text: "'Anointed One' — the Greek translation of the Hebrew Mashiach (Messiah).", rationale: "Used for kings (Saul, David), priests, and prophets in the OT. Jesus is THE Anointed because He is King, Priest, and Prophet." },
        { id: "b", text: "'Son of Man' — Daniel 7's apocalyptic figure.", rationale: "Wrong. 'Son of Man' (bar enasha / huios tou anthrōpou) is a different title; Christos = Anointed One." },
        { id: "c", text: "Jesus's surname or family name in Roman style.", rationale: "Wrong. 'Christ' is a TITLE, not a surname. Jewish names did not work that way in the 1st century." },
        { id: "d", text: "'Teacher' — equivalent to the Hebrew Rabbi.", rationale: "Wrong. Rabbi is a title for teacher; Christos means Anointed One." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 1:41; Acts 4:26 (Ps 2:2)" }],
    },
    {
      id: "ft-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["seven-fold-gifts-spirit"],
      prompt: "Where in Scripture are the seven gifts of the Holy Spirit enumerated?",
      choices: [
        { id: "a", text: "Isaiah 11:2-3 — wisdom, understanding, counsel, might, knowledge, fear of the Lord, and (LXX) piety.", rationale: "The Hebrew lists six; the Septuagint divides 'fear of the Lord' into 'piety + fear,' giving seven. Foundational for both Eastern and Western pneumatology." },
        { id: "b", text: "1 Corinthians 12 — the charismatic gifts (apostles, prophets, teachers, miracles, healings, helps, governments, tongues).", rationale: "Wrong. 1 Cor 12 lists charismatic GIFTS, but they number more than seven and are different from the SEVEN GIFTS of the Spirit traditionally drawn from Is 11." },
        { id: "c", text: "Galatians 5:22-23 — love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.", rationale: "Wrong. That is the FRUIT of the Spirit, nine virtues — a different list from the SEVEN gifts of Is 11." },
        { id: "d", text: "Revelation 1 — the seven spirits before the throne.", rationale: "Wrong. Rev 1:4 mentions 'seven spirits before the throne' (interpreted by some as the seven gifts), but the source LIST is Isaiah 11." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Isaiah 11:2-3 (LXX)" }],
    },
    {
      id: "ft-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["sermon-on-mount"],
      prompt: "How many Beatitudes does the Lord pronounce in Matthew 5:3-12?",
      choices: [
        { id: "a", text: "Nine — sometimes counted as eight, depending on whether vv. 11-12 are taken as one or two.", rationale: "The standard count is nine: poor in spirit, mourn, meek, hunger and thirst, merciful, pure in heart, peacemakers, persecuted, reviled (vv. 11-12)." },
        { id: "b", text: "Four — corresponding to the four Beatitudes in Luke 6:20-22.", rationale: "Wrong, BUT Luke's parallel HAS four (Lk 6:20-22, with four woes). The question asks about MATTHEW, which has nine." },
        { id: "c", text: "Ten — by analogy with the Ten Commandments.", rationale: "Wrong. Matthew has nine Beatitudes, not ten. The analogy to the Decalogue is interpretive, not numerical." },
        { id: "d", text: "Seven — corresponding to the seven gifts of the Spirit and the seven petitions of the Lord's Prayer.", rationale: "Wrong. Augustine famously aligned seven Beatitudes with the seven gifts, but the actual count in Mt 5 is nine (or eight)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Matthew 5:3-12" }],
    },
    {
      id: "ft-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["love"],
      prompt: "Which three Greek words for love appear in the New Testament?",
      choices: [
        { id: "a", text: "Agape (self-giving), philia (brotherly affection), and storge (in compounds like astorgos in Rom 1:31).", rationale: "Eros, while a common Greek word, does not appear in NT Greek; storge appears only as the compound astorgos ('without natural affection') in Rom 1:31; 2 Tim 3:3. Agape and philia are the principal NT words." },
        { id: "b", text: "Caritas, dilectio, and amor — three Latin terms used in the Vulgate.", rationale: "Wrong. The NT was written in Greek; Latin translations came later. Caritas/dilectio/amor are Vulgate translations." },
        { id: "c", text: "Hesed (covenant loyalty), ahavah (love), and racham (compassion) — Hebrew OT terms.", rationale: "Wrong. These are Hebrew OT terms, not NT Greek. The NT uses Greek words for love." },
        { id: "d", text: "Agape, eros, and charitas — the Lewis triad popularized in The Four Loves.", rationale: "Wrong on two counts: eros does NOT appear in the NT; charitas is Latin (= caritas), not Greek; and C.S. Lewis's FOUR loves include storge as well." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Romans 1:31; 2 Timothy 3:3; standard NT Greek lexica" }],
    },
  ],
};
