import type { Topic } from "@/lib/types";

export const mcqPackEarly: Topic = {
  id: "early-mcq-pack",
  title: "Quick MCQ Pack — Early Church",
  summary: "Rapid-fire factual MCQs for warmup drilling.",
  learningObjectives: ["Drill core facts to mastery."],
  primarySources: ["Standard patristic and historical references"],
  items: [
    {
      id: "ae-020",
      kind: "mcq",
      difficulty: 1,
      tags: ["acts"],
      prompt: "In what city were the disciples first called 'Christians'?",
      choices: [
        { id: "a", text: "Jerusalem" },
        { id: "b", text: "Antioch", rationale: "Correct. Acts 11:26." },
        { id: "c", text: "Rome" },
        { id: "d", text: "Ephesus" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Acts 11:26" }],
    },
    {
      id: "ae-021",
      kind: "mcq",
      difficulty: 2,
      tags: ["paul", "missionary-journeys"],
      prompt: "How many missionary journeys does Acts record for St. Paul?",
      choices: [
        { id: "a", text: "Two" },
        { id: "b", text: "Three (plus the final journey to Rome)", rationale: "Correct. Acts 13-14; 15:36-18:22; 18:23-21:17; voyage to Rome 27-28." },
        { id: "c", text: "Four" },
        { id: "d", text: "Five" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Acts 13-28" }],
    },
    {
      id: "ae-022",
      kind: "mcq",
      difficulty: 2,
      tags: ["apostles"],
      prompt: "Who replaced Judas Iscariot among the Twelve?",
      choices: [
        { id: "a", text: "Matthias", rationale: "Correct. Acts 1:23-26." },
        { id: "b", text: "Joseph called Barsabbas, surnamed Justus" },
        { id: "c", text: "Paul" },
        { id: "d", text: "Stephen" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts 1:23-26" }],
    },
    {
      id: "ae-023",
      kind: "mcq",
      difficulty: 2,
      tags: ["polycarp"],
      prompt: "Who was the bishop of Smyrna who appears in Ignatius's letters and was later martyred?",
      choices: [
        { id: "a", text: "Polycarp", rationale: "Correct. Bishop of Smyrna; martyred c. AD 155." },
        { id: "b", text: "Onesimus" },
        { id: "c", text: "Damas" },
        { id: "d", text: "Hierax" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Ignatius, Letter to Polycarp; Martyrdom of Polycarp" }],
    },
    {
      id: "ae-024",
      kind: "mcq",
      difficulty: 3,
      tags: ["didache", "structure"],
      prompt: "Which is NOT in the Didache?",
      choices: [
        { id: "a", text: "The Two Ways catechetical material" },
        { id: "b", text: "Trinitarian baptismal formula" },
        { id: "c", text: "Eucharistic prayers" },
        { id: "d", text: "Detailed list of papal succession", rationale: "Correct. The Didache deals with apostles and prophets, not Roman succession." },
      ],
      correctChoiceId: "d",
      citations: [{ source: "Didache (full text)" }],
    },
    {
      id: "ae-025",
      kind: "mcq",
      difficulty: 3,
      tags: ["dura-europos"],
      prompt: "What is significant about the house church at Dura-Europos (c. AD 235)?",
      choices: [
        { id: "a", text: "It is the earliest known purpose-adapted Christian church building, with frescoes including the Good Shepherd and biblical scenes.", rationale: "Correct. Excavated in Syria 1932." },
        { id: "b", text: "It was Constantine's family chapel." },
        { id: "c", text: "It is the original see of St. Peter." },
        { id: "d", text: "It was the first Christian basilica." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Dura-Europos archaeology (Yale-French excavations, 1932)" }],
    },
    {
      id: "ae-026",
      kind: "mcq",
      difficulty: 2,
      tags: ["constantine", "vision"],
      prompt: "What date is the Battle of the Milvian Bridge, after which Constantine attributed his victory to the Christian sign?",
      choices: [
        { id: "a", text: "October 28, 312", rationale: "Correct. Eve of the feast of Sts. Cyprian and Justina; Constantine defeated Maxentius." },
        { id: "b", text: "May 11, 330" },
        { id: "c", text: "April 23, 311" },
        { id: "d", text: "September 14, 326" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Lactantius, On the Deaths of the Persecutors 44" }],
    },
    {
      id: "ae-027",
      kind: "mcq",
      difficulty: 3,
      tags: ["catechumenate"],
      prompt: "What was the 'disciplina arcani' in the early Church?",
      choices: [
        { id: "a", text: "The discipline of secrecy by which the deepest mysteries (Eucharist, baptismal forms) were kept from the unbaptized and only revealed in stages to catechumens.", rationale: "Correct. Cyril of Jerusalem's Mystagogical Catecheses are addressed only to the newly baptized." },
        { id: "b", text: "The schedule of monastic fasting." },
        { id: "c", text: "The episcopal succession lists." },
        { id: "d", text: "The order of the Mass." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Cyril of Jerusalem, Mystagogical Catecheses I-V" }],
    },
  ],
};
