import type { Topic } from "@/lib/types";

export const finalEarlyPack: Topic = {
  id: "final-early-pack",
  title: "Final Early Church Pack",
  summary: "Additional early-history items: martyrs, persecutions, key councils-before-Nicaea.",
  learningObjectives: ["Drill more early-church facts."],
  primarySources: ["Eusebius EH; Acts of the Martyrs"],
  items: [
    {
      id: "ae-030",
      kind: "mcq",
      difficulty: 2,
      tags: ["paul-conversion"],
      prompt: "Where was Saul of Tarsus converted, and what was he doing?",
      choices: [
        { id: "a", text: "On the road to Damascus, bearing letters from the high priest to arrest Christians there.", rationale: "Acts 9:1-2. The first of three accounts of his conversion in Acts (9; 22; 26)." },
        { id: "b", text: "In Jerusalem, after witnessing the stoning of Stephen and being struck with remorse.", rationale: "Wrong. Saul consented to Stephen's death (Acts 7:58; 8:1), but his conversion came later on the Damascus road." },
        { id: "c", text: "In Tarsus, his hometown, after a dream in which Christ appeared to him.", rationale: "Wrong. He returned to Tarsus only AFTER his conversion (Acts 9:30)." },
        { id: "d", text: "In Antioch, where the disciples were first called Christians (Acts 11:26).", rationale: "Wrong. Saul came to Antioch only later, brought by Barnabas (Acts 11:25-26)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts 9:1-22; 22:6-16; 26:12-18" }],
    },
    {
      id: "ae-031",
      kind: "mcq",
      difficulty: 2,
      tags: ["mary-magdalene"],
      prompt: "Whom do the Gospels primarily name as the first witness of the risen Christ?",
      choices: [
        { id: "a", text: "Mary Magdalene — explicitly in John 20 and Mark 16:9.", rationale: "Mary Magdalene, sometimes with the other myrrh-bearing women. Honored as 'Equal-to-the-Apostles' for being the apostle to the Apostles." },
        { id: "b", text: "Peter and John — they ran to the tomb together and Peter entered first.", rationale: "Wrong. Peter and John ran to the tomb (Jn 20:3-9), but Mary had already arrived and seen it empty." },
        { id: "c", text: "The Theotokos — to whom Christ appeared first, kept silent by John's Gospel for her sake.", rationale: "Wrong. A pious tradition exists that He appeared to her, but the Gospels themselves name Mary Magdalene." },
        { id: "d", text: "The two disciples on the road to Emmaus, who recognized Him in the breaking of bread.", rationale: "Wrong. The Emmaus appearance (Lk 24:13-35) is later that day; Mary's vision in the garden is the first named." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 20:11-18; Mark 16:9; Matthew 28:9-10" }],
    },
    {
      id: "ae-032",
      kind: "mcq",
      difficulty: 3,
      tags: ["thecla"],
      prompt: "Who was St. Thecla?",
      choices: [
        { id: "a", text: "A 1st-century virgin disciple of St. Paul known from the Acts of Paul and Thecla; venerated as the first female martyr.", rationale: "Commemorated September 24 as 'Protomartyr and Equal-to-the-Apostles.' Her shrine at Seleucia was a major pilgrimage site." },
        { id: "b", text: "The unnamed wife of St. Peter, traditionally identified through Clement of Alexandria's writings.", rationale: "Wrong. Clement of Alexandria does mention Peter's wife (Strom. VII.11.63), but not by the name Thecla." },
        { id: "c", text: "An abbess of Constantinople in the 4th century, commemorated alongside St. Macrina the Younger.", rationale: "Wrong. Macrina the Younger (~327-379) IS a real saint, but Thecla is the 1st-c. disciple of Paul." },
        { id: "d", text: "A virgin-martyr of Carthage who appears in the Passion of Perpetua and Felicity (203).", rationale: "Wrong. Perpetua and Felicity were Carthaginian martyrs of 203, but Thecla is a different earlier figure." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Paul and Thecla (~AD 180); Synaxarion, September 24" }],
    },
    {
      id: "ae-033",
      kind: "mcq",
      difficulty: 3,
      tags: ["edict-of-milan"],
      prompt: "What did the Edict of Milan (313) actually decree?",
      choices: [
        { id: "a", text: "Universal religious liberty plus the restoration of all property confiscated from Christians during the persecutions.", rationale: "Lactantius preserves the full Latin. The Edict was jointly issued by Constantine and Licinius at Mediolanum (Milan)." },
        { id: "b", text: "Christianity as the sole permitted religion of the Empire; the closing of pagan temples.", rationale: "Wrong. That step was taken by Theodosius I in 380 (Cunctos populos) and 391-392, not Constantine in 313." },
        { id: "c", text: "Sunday as a mandatory civil day of rest throughout the Empire.", rationale: "Wrong. Constantine's Sunday legislation came in 321, after Milan, and as separate civil law." },
        { id: "d", text: "Imperial construction of basilicas at all five ancient patriarchates.", rationale: "Wrong. Constantine did sponsor basilicas (Holy Sepulchre, St. Peter's, etc.), but that was a separate policy, not the Edict of Milan." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Lactantius, On the Deaths of the Persecutors 48" }],
    },
    {
      id: "ae-034",
      kind: "mcq",
      difficulty: 4,
      tags: ["theodosius"],
      prompt: "Which Roman emperor declared Christianity the state religion in 380?",
      choices: [
        { id: "a", text: "Constantine I, in his deathbed edict of 337.", rationale: "Wrong. Constantine legalized Christianity (313) but did not make it the state religion. He died in 337 without such a decree." },
        { id: "b", text: "Theodosius I, in the Edict of Thessalonica ('Cunctos populos'), February 27, 380.", rationale: "Issued jointly with Gratian and Valentinian II; required all subjects to confess the Nicene faith." },
        { id: "c", text: "Constantius II, the Arian son of Constantine, in 361 just before his death.", rationale: "Wrong. Constantius II was Arian and died in 361; he made no such Nicene declaration." },
        { id: "d", text: "Justinian I, alongside his closing of the Athenian Academy in 529.", rationale: "Wrong. Justinian closed the Athenian Academy in 529 but did not establish Christianity as state religion — Theodosius had done so 150 years before." },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Codex Theodosianus 16.1.2 — Edict of Thessalonica (380)" }],
    },
    {
      id: "ae-035",
      kind: "mcq",
      difficulty: 4,
      tags: ["constantine-baptism"],
      prompt: "When was Constantine the Great baptized?",
      choices: [
        { id: "a", text: "On his deathbed in 337, by Eusebius of Nicomedia (an Arian-leaning bishop).", rationale: "Eusebius of Caesarea, Life of Constantine IV.61-62. He had postponed baptism, hoping to be baptized in the Jordan, but died in Nicomedia." },
        { id: "b", text: "Before the Battle of the Milvian Bridge in 312, at the urging of his mother Helena.", rationale: "Wrong. He saw the vision before Milvian Bridge but was not baptized until 337." },
        { id: "c", text: "At the Council of Nicaea in 325, by Sylvester of Rome.", rationale: "Wrong. This is the legend of the 'Donation of Constantine' — a medieval forgery. He was not baptized at Nicaea." },
        { id: "d", text: "He was never baptized, dying as an unbaptized catechumen with a deathbed wish.", rationale: "Wrong. He WAS baptized on his deathbed (Eusebius EH IV.61-62 is explicit); he died still wearing his white baptismal robes." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius, Life of Constantine IV.61-62" }],
    },
    {
      id: "ae-036",
      kind: "mcq",
      difficulty: 4,
      tags: ["roman-catacombs"],
      prompt: "Approximately how many Christian catacombs are known in and around Rome?",
      choices: [
        { id: "a", text: "Over sixty — including Domitilla, Priscilla, Callixtus, San Sebastiano, and many smaller ones.", rationale: "Maintained today by the Pontifical Commission for Sacred Archaeology. Roman catacombs span 1st-5th centuries." },
        { id: "b", text: "Six — the cemeteries used during the major persecutions of Nero, Trajan, Decius, Valerian, Diocletian, and Julian.", rationale: "Wrong. The number is far higher than six; persecutions did not map onto separate burial sites." },
        { id: "c", text: "Three — corresponding to the three principal early Roman dioceses of the Apostolic age.", rationale: "Wrong. Rome was a single diocese; the catacombs are many and span centuries." },
        { id: "d", text: "Two — the catacombs of St. Peter (the Vatican) and St. Paul (Outside the Walls).", rationale: "Wrong. St. Peter's tomb is under the Vatican basilica, but there are dozens of catacombs across Rome." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pontifical Commission for Sacred Archaeology, Rome" }],
    },
    {
      id: "ae-037",
      kind: "mcq",
      difficulty: 3,
      tags: ["apostles", "thomas"],
      prompt: "Where did the Apostle Thomas reportedly preach the Gospel?",
      choices: [
        { id: "a", text: "Parthia, Persia, and India — the Mar Thoma Christians of Kerala trace apostolic succession from him.", rationale: "Eusebius EH 3.1.1; the Acts of Thomas (3rd c.); ancient and continuous Mar Thoma tradition. Martyred at Mylapore." },
        { id: "b", text: "Britain and Gaul — he is the traditional founder of the see of Lyon, where Irenaeus later served.", rationale: "Wrong. Irenaeus was bishop of Lyon (~AD 180), but the see of Lyon was not founded by Thomas." },
        { id: "c", text: "Ethiopia and Nubia, baptizing the eunuch of Acts 8 and his royal house.", rationale: "Wrong. Acts 8 places Philip the Deacon, not Thomas, with the Ethiopian eunuch." },
        { id: "d", text: "Scythia and the Black Sea region, founding the see of Byzantium.", rationale: "Wrong. That tradition belongs to St. Andrew the First-Called (Eusebius EH 3.1.1)." },
      ],
      correctChoiceId: "a",
      citations: [
        { source: "Eusebius EH 3.1.1" },
        { source: "Acts of Thomas (3rd c.); Mar Thoma tradition" },
      ],
    },
  ],
};
