import type { Topic } from "@/lib/types";

export const finalEarlyPack: Topic = {
  id: "final-early-pack",
  title: "Final Early Church Pack",
  summary: "Additional early-history items: martyrs, persecutions, key councils-before-Nicaea.",
  learningObjectives: ["Drill more early-church facts."],
  primarySources: ["Eusebius EH; Acts of the Martyrs"],
  items: [
    {
      id: "ae-030",
      kind: "mcq",
      difficulty: 2,
      tags: ["paul-conversion"],
      prompt: "Where was Saul converted, and what was he doing?",
      choices: [
        { id: "a", text: "On the road to Damascus, while pursuing Christians.", rationale: "Correct. Acts 9; 22; 26." },
        { id: "b", text: "In Jerusalem, while praying" },
        { id: "c", text: "In Tarsus, his hometown" },
        { id: "d", text: "In Rome, before Caesar" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts 9:1-22" }],
    },
    {
      id: "ae-031",
      kind: "mcq",
      difficulty: 2,
      tags: ["mary-magdalene"],
      prompt: "Whom does each Gospel name as the first witness of the Resurrection?",
      choices: [
        { id: "a", text: "Mary Magdalene (each Gospel; explicitly named Jn 20).", rationale: "Correct." },
        { id: "b", text: "Peter and John" },
        { id: "c", text: "The Theotokos" },
        { id: "d", text: "Joseph of Arimathea" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 20:11-18; Mark 16:9; Matthew 28:9-10" }],
    },
    {
      id: "ae-032",
      kind: "mcq",
      difficulty: 3,
      tags: ["thecla"],
      prompt: "Who was St. Thecla, and why is she called 'Equal-to-the-Apostles'?",
      choices: [
        { id: "a", text: "A 1st-century virgin disciple of St. Paul (per the Acts of Paul and Thecla), legendary first female Christian martyr.", rationale: "Correct. Commemorated September 24." },
        { id: "b", text: "A wife of one of the Twelve Apostles" },
        { id: "c", text: "The first abbess of Constantinople" },
        { id: "d", text: "A bishop of Carthage" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Paul and Thecla (~AD 180); Synaxarion, September 24" }],
    },
    {
      id: "ae-033",
      kind: "mcq",
      difficulty: 3,
      tags: ["edict-of-milan"],
      prompt: "Which provision is in the Edict of Milan (313)?",
      choices: [
        { id: "a", text: "Restoration of all confiscated Christian property and full religious liberty for all subjects.", rationale: "Correct." },
        { id: "b", text: "Christianity as the sole religion of the empire" },
        { id: "c", text: "Sunday as a legal day of rest" },
        { id: "d", text: "Construction of churches at imperial expense" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Lactantius, On the Deaths of the Persecutors 48" }],
    },
    {
      id: "ae-034",
      kind: "mcq",
      difficulty: 4,
      tags: ["mavrid-history"],
      prompt: "Which Roman emperor declared Christianity the state religion in 380?",
      choices: [
        { id: "a", text: "Constantine I" },
        { id: "b", text: "Theodosius I, in the Edict of Thessalonica (Cunctos populos), February 27, 380.", rationale: "Correct." },
        { id: "c", text: "Constantius II" },
        { id: "d", text: "Julian the Apostate" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Codex Theodosianus 16.1.2 — Edict of Thessalonica (380)" }],
    },
    {
      id: "ae-035",
      kind: "mcq",
      difficulty: 3,
      tags: ["constantine-baptism"],
      prompt: "When was Constantine the Great baptized?",
      choices: [
        { id: "a", text: "On his deathbed, by Eusebius of Nicomedia, in 337.", rationale: "Correct. Eusebius of Caesarea, Life of Constantine IV.61-62." },
        { id: "b", text: "Before the Milvian Bridge (312)" },
        { id: "c", text: "At the Council of Nicaea (325)" },
        { id: "d", text: "He was never baptized." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius, Life of Constantine IV.61-62" }],
    },
    {
      id: "ae-036",
      kind: "mcq",
      difficulty: 4,
      tags: ["roman-catacombs"],
      prompt: "How many known Christian catacombs are in Rome?",
      choices: [
        { id: "a", text: "Over 60 (the catacombs of Domitilla, Priscilla, Callixtus, San Sebastiano, and others)", rationale: "Correct." },
        { id: "b", text: "Six total" },
        { id: "c", text: "One — the Vatican" },
        { id: "d", text: "Twelve" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pontifical Commission for Sacred Archaeology, Rome" }],
    },
    {
      id: "ae-037",
      kind: "mcq",
      difficulty: 3,
      tags: ["apostles", "thomas"],
      prompt: "Where did Apostle Thomas reportedly preach the Gospel?",
      choices: [
        { id: "a", text: "Parthia, Persia, and India (Mar Thoma Church in Kerala traces apostolic succession from him; martyred at Mylapore).", rationale: "Correct." },
        { id: "b", text: "Spain only" },
        { id: "c", text: "Britain only" },
        { id: "d", text: "Ethiopia only" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius EH 3.1; Acts of Thomas (3rd c.); Mar Thoma tradition" }],
    },
  ],
};
