import type { Topic } from "@/lib/types";

export const finalEarlyPack2: Topic = {
  id: "final-early-pack-2",
  title: "Early Church — Final Pack",
  summary: "Last round of MCQs on the apostolic and sub-apostolic era.",
  learningObjectives: ["Drill remaining facts to mastery."],
  primarySources: ["Various standard references"],
  items: [
    {
      id: "ae-040",
      kind: "mcq",
      difficulty: 2,
      tags: ["seven-deacons"],
      prompt: "How many Deacons did the Apostles appoint in Acts 6 to serve tables?",
      choices: [
        { id: "a", text: "Seven — Stephen, Philip, Prochorus, Nicanor, Timon, Parmenas, and Nicolas.", rationale: "Correct." },
        { id: "b", text: "Twelve" },
        { id: "c", text: "Three" },
        { id: "d", text: "Seventy" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts 6:5" }],
    },
    {
      id: "ae-041",
      kind: "mcq",
      difficulty: 2,
      tags: ["seventy"],
      prompt: "How many disciples did the Lord send out in Luke 10?",
      choices: [
        { id: "a", text: "Seventy (or seventy-two, depending on textual witness)", rationale: "Correct. Lk 10:1." },
        { id: "b", text: "Twelve" },
        { id: "c", text: "One hundred" },
        { id: "d", text: "Three" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Luke 10:1" }],
    },
    {
      id: "ae-042",
      kind: "mcq",
      difficulty: 3,
      tags: ["ignatius-letters"],
      prompt: "Where was St. Ignatius of Antioch martyred?",
      choices: [
        { id: "a", text: "Rome — devoured by lions in the Coliseum, c. AD 107.", rationale: "Correct." },
        { id: "b", text: "Antioch" },
        { id: "c", text: "Smyrna" },
        { id: "d", text: "Ephesus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius, EH 3.36" }],
    },
    {
      id: "ae-043",
      kind: "mcq",
      difficulty: 4,
      tags: ["clement-of-rome-name"],
      prompt: "Eusebius EH 3.15 names St. Clement of Rome as the bishop after Anencletus. Who is identified as the first bishop of Rome by Irenaeus's succession list (AH III.3.3)?",
      choices: [
        { id: "a", text: "Linus (mentioned in 2 Tim 4:21), with Anencletus second and Clement third.", rationale: "Correct. Irenaeus AH III.3.3." },
        { id: "b", text: "Peter (as bishop)" },
        { id: "c", text: "Paul" },
        { id: "d", text: "Cletus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Irenaeus, AH III.3.3; 2 Tim 4:21" }],
    },
    {
      id: "ae-044",
      kind: "mcq",
      difficulty: 3,
      tags: ["passover"],
      prompt: "What is the Quartodeciman controversy?",
      choices: [
        { id: "a", text: "2nd-c. dispute over Pascha: the Asian churches (Polycrates of Ephesus) kept Pascha on the 14th of Nisan, the day of crucifixion; the Roman/Alexandrian churches kept it on the Sunday after. Settled at Nicaea (325) in favor of the Sunday computus.", rationale: "Correct. Eusebius EH 5.23-25." },
        { id: "b", text: "The Filioque" },
        { id: "c", text: "Iconoclasm" },
        { id: "d", text: "Monophysitism" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius EH 5.23-25; Acts of Nicaea (325)" }],
    },
    {
      id: "ae-045",
      kind: "mcq",
      difficulty: 4,
      tags: ["aleph-codex"],
      prompt: "What is the approximate date of the earliest complete extant manuscript of the New Testament?",
      choices: [
        { id: "a", text: "4th century (Codex Sinaiticus, mid-4th c.; Codex Vaticanus, 4th c.)", rationale: "Correct. Earlier papyri contain partial texts (e.g. P52 of John, c. AD 125)." },
        { id: "b", text: "1st century" },
        { id: "c", text: "8th century" },
        { id: "d", text: "13th century" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard NT textual criticism" }],
    },
    {
      id: "ae-046",
      kind: "mcq",
      difficulty: 4,
      tags: ["fragment-p52"],
      prompt: "What is P52, and why is it significant?",
      choices: [
        { id: "a", text: "Rylands Library Papyrus P52 — a small fragment of John 18 dated c. AD 125-150. The earliest extant NT manuscript fragment, evidence that John was in circulation in Egypt by the early 2nd century.", rationale: "Correct." },
        { id: "b", text: "A complete Bible" },
        { id: "c", text: "A book of Hebrew prophets" },
        { id: "d", text: "A Gnostic gospel" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Rylands University Library, Papyrus 52 (Greek fragment of John 18)" }],
    },
  ],
};
