import type { Topic } from "@/lib/types";

export const saintsFinalPack: Topic = {
  id: "saints-final-pack",
  title: "Saints — Final Pack",
  summary: "Final MCQs on saints.",
  learningObjectives: ["Drill remaining important saints."],
  primarySources: ["Synaxarion"],
  items: [
    {
      id: "saint-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["james-just"],
      prompt:
        "How did St. James the Just, brother of the Lord and first bishop of Jerusalem, die?",
      choices: [
        { id: "a", text: "Thrown from the pinnacle of the Temple and clubbed to death (~AD 62).", rationale: "Eusebius EH 2.23 (citing Hegesippus) and Josephus Antiquities 20.9.1 both attest this. He preached from the parapet before being thrown." },
        { id: "b", text: "Beheaded outside Rome under Nero, alongside St. Paul (~AD 67).", rationale: "Wrong. That is the manner of Paul's death, not James the Just. James the Just was killed in Jerusalem ~AD 62." },
        { id: "c", text: "Crucified upside-down in Jerusalem at his own request.", rationale: "Wrong. That is St. Peter's traditional manner of death (Eusebius EH 3.1.2, citing Origen). James the Just was thrown from the Temple." },
        { id: "d", text: "Natural causes in his old age at the See of Jerusalem.", rationale: "Wrong. James was martyred; he did not die of natural causes." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius EH 2.23; Josephus, Antiquities 20.9.1" }],
    },
    {
      id: "saint-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["mark-evangelist"],
      prompt: "How did St. Mark the Evangelist die?",
      choices: [
        { id: "a", text: "Dragged with a rope around his neck through the streets of Alexandria until dead (April 25, AD 68).", rationale: "Coptic and Greek traditions agree. Buried at Alexandria; relics translated to Venice in the 9th century." },
        { id: "b", text: "Died peacefully of natural causes in Rome after writing his Gospel under Peter's direction.", rationale: "Wrong. Mark wrote his Gospel in Rome (per Papias and Irenaeus), but tradition is unanimous that he was martyred in Alexandria, not died peacefully in Rome." },
        { id: "c", text: "Beheaded under Diocletian in 304, the last of the apostolic generation's commemorated companions.", rationale: "Wrong. Mark died in the 60s AD, not 304 (Diocletian was 250 years later)." },
        { id: "d", text: "Stoned to death in Jerusalem by the same mob that killed James the Just.", rationale: "Wrong. James the Just was killed in Jerusalem, but Mark died in Alexandria." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, April 25; Eusebius EH 2.16" }],
    },
    {
      id: "saint-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["andrew"],
      prompt: "How did St. Andrew the First-Called die?",
      choices: [
        { id: "a", text: "Crucified on an X-shaped cross at Patras in Achaia (~AD 60-70).", rationale: "Tradition assigns this form of crucifixion as a sign of his unworthiness to die as Christ did. The 'St. Andrew's Cross' is the saltire used on the Scottish flag." },
        { id: "b", text: "Beheaded at Rome under Nero alongside St. Paul.", rationale: "Wrong. Paul (not Andrew) was beheaded outside Rome under Nero. Andrew died at Patras, Greece." },
        { id: "c", text: "Stoned to death in Jerusalem during the persecution that scattered the Apostles.", rationale: "Wrong. Stephen the Protomartyr was stoned in Jerusalem (Acts 7), but Andrew was crucified in Achaia." },
        { id: "d", text: "Died of natural causes at Constantinople, where he had founded the See of Byzantium.", rationale: "Wrong. Andrew DID found the See of Byzantium (consecrating Stachys), but he was martyred at Patras, not died peacefully in Constantinople." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, November 30" }],
    },
    {
      id: "saint-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["relics"],
      prompt: "What is the Orthodox basis for the veneration of relics?",
      choices: [
        { id: "a", text: "The bodies (or fragments) of saints are venerated as sanctified by the Holy Spirit who dwelt in them; affirmed at Nicaea II (787).", rationale: "Scripture precedents: Elisha's bones raise the dead (2 Kgs 13:21); Paul's handkerchiefs heal (Acts 19:11-12). Patristic and conciliar witness universal." },
        { id: "b", text: "Forbidden by the Orthodox canons; veneration is reserved for icons and the Cross alone.", rationale: "Wrong. Relics ARE venerated alongside icons. Every Orthodox altar contains relics within or beneath the antimension." },
        { id: "c", text: "Only allowed for the Twelve Apostles and Mary the Theotokos; other saints' bodies are buried.", rationale: "Wrong. Relics of countless saints (martyrs, confessors, hierarchs, monastics) are venerated, not just Apostles." },
        { id: "d", text: "Limited to monastic communities; lay veneration is canonically discouraged.", rationale: "Wrong. Lay veneration of relics is universal Orthodox practice, especially on saints' feast days." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "2 Kings 13:21; Acts 19:11-12; Definition of Nicaea II (787)" }],
    },
    {
      id: "saint-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["synaxarion"],
      prompt: "How does the Orthodox liturgical calendar organize commemorations of saints?",
      choices: [
        { id: "a", text: "Each day of the year commemorates one or more saints. The Synaxarion is the calendar book; major feasts take precedence over the saint of the day.", rationale: "The Menaion contains the hymnography for each day. Movable feasts (Lent, Pascha, Pentecost) follow the Triodion and Pentecostarion." },
        { id: "b", text: "Saints are commemorated only on the anniversary of their death; if none died on a given day, that day is unassigned.", rationale: "Wrong. Saints are commemorated on death-days (typically) but many also have additional feasts (e.g., translation of relics)." },
        { id: "c", text: "Only feasts of the Lord and the Theotokos are observed; saints' feasts are private devotions.", rationale: "Wrong. Saints' feasts are public liturgical commemorations in the daily and weekly cycles." },
        { id: "d", text: "All saints are commemorated together on a single All Saints Day; individual feasts are abandoned.", rationale: "Wrong. All Saints Sunday (first Sunday after Pentecost in Orthodoxy) IS observed, but it does not replace individual saints' feast days." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion of the Great Church (annual cycle)" }],
    },
  ],
};
