import type { Topic } from "@/lib/types";

export const saintsFinalPack: Topic = {
  id: "saints-final-pack",
  title: "Saints — Final Pack",
  summary: "Final MCQs on saints.",
  learningObjectives: ["Drill remaining important saints."],
  primarySources: ["Synaxarion"],
  items: [
    {
      id: "saint-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["james-just"],
      prompt: "How did St. James, brother of the Lord and first bishop of Jerusalem, die?",
      choices: [
        { id: "a", text: "Thrown from the pinnacle of the Temple and clubbed to death (~AD 62)", rationale: "Correct. Eusebius EH 2.23, citing Hegesippus." },
        { id: "b", text: "Beheaded under Nero" },
        { id: "c", text: "Crucified upside-down" },
        { id: "d", text: "Natural causes" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Eusebius EH 2.23; Josephus, Antiquities 20.9" }],
    },
    {
      id: "saint-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["mark-evangelist"],
      prompt: "How did St. Mark the Evangelist die?",
      choices: [
        { id: "a", text: "Dragged through the streets of Alexandria until dead (April 25, AD 68)", rationale: "Correct." },
        { id: "b", text: "Natural causes in Rome" },
        { id: "c", text: "Beheaded" },
        { id: "d", text: "Stoned in Jerusalem" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, April 25; Eusebius EH 2.16" }],
    },
    {
      id: "saint-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["andrew"],
      prompt: "How did St. Andrew the First-Called die?",
      choices: [
        { id: "a", text: "Crucified on an X-shaped cross (the 'St. Andrew's Cross') at Patras in Achaia (~AD 60-70)", rationale: "Correct." },
        { id: "b", text: "Beheaded at Rome" },
        { id: "c", text: "Stoned in Jerusalem" },
        { id: "d", text: "Natural causes in Constantinople" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, November 30" }],
    },
    {
      id: "saint-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["matrona-mtsire"],
      prompt: "What is the relics-veneration tradition in Orthodoxy?",
      choices: [
        { id: "a", text: "The bodies (or fragments) of saints are venerated as sanctified by the Holy Spirit who dwelt in them; many remain incorrupt or work miracles. Cf. 2 Kgs 13:21 (Elisha's bones raise the dead) and Acts 19:11-12 (Paul's handkerchiefs heal).", rationale: "Correct." },
        { id: "b", text: "Forbidden by Orthodox canons" },
        { id: "c", text: "Only allowed for the Apostles" },
        { id: "d", text: "Limited to monastic communities" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "2 Kings 13:21; Acts 19:11-12; Nicaea II (787)" }],
    },
    {
      id: "saint-final-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["isaiah-of-rostov"],
      prompt: "How does the Orthodox calendar order its commemorations?",
      choices: [
        { id: "a", text: "Each day commemorates one or more saints; the Synaxarion is the calendar book. Major feasts of the Lord and Theotokos take precedence; saints of the day after.", rationale: "Correct." },
        { id: "b", text: "Saints rotate randomly" },
        { id: "c", text: "Only feasts of the Lord are observed" },
        { id: "d", text: "All saints celebrated on All Saints Day only" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion (annual cycle of saints)" }],
    },
  ],
};
