import type { Topic } from "@/lib/types";

export const saintsFactsPack: Topic = {
  id: "saints-facts-pack",
  title: "Saints — Quick Recall Pack",
  summary: "MCQs on major saints, their feasts, and titles.",
  learningObjectives: ["Match each saint to feast and title."],
  primarySources: ["Synaxarion; Lives of the Saints"],
  items: [
    {
      id: "saint-fp-001",
      kind: "mcq",
      difficulty: 1,
      tags: ["theotokos"],
      prompt: "On what date is the Dormition of the Theotokos celebrated?",
      choices: [
        { id: "a", text: "August 15", rationale: "Correct. Preceded by the Dormition Fast (Aug 1-14)." },
        { id: "b", text: "September 8" },
        { id: "c", text: "March 25" },
        { id: "d", text: "November 21" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion, August 15" }],
    },
    {
      id: "saint-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["theotokos", "annunciation"],
      prompt: "On what date is the Annunciation celebrated?",
      choices: [
        { id: "a", text: "March 25 (exactly nine months before Nativity, December 25)", rationale: "Correct." },
        { id: "b", text: "August 15" },
        { id: "c", text: "September 8" },
        { id: "d", text: "December 25" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion, March 25" }],
    },
    {
      id: "saint-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["forerunner"],
      prompt: "Who is the 'Forerunner'?",
      choices: [
        { id: "a", text: "St. John the Baptist", rationale: "Correct. 'The Forerunner of the Lord.' Multiple feasts: Conception (Sep 23), Nativity (Jun 24), Beheading (Aug 29), Synaxis (Jan 7), Finding of his Honored Head." },
        { id: "b", text: "Elijah the Prophet" },
        { id: "c", text: "Isaiah" },
        { id: "d", text: "Stephen the Protomartyr" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Various Menaia entries" }],
    },
    {
      id: "saint-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["spyridon"],
      prompt: "Which 4th-century bishop, a former shepherd, attended Nicaea and demonstrated the Trinity using a brick (which separately released fire, water, and clay)?",
      choices: [
        { id: "a", text: "St. Spyridon of Tremithus, Cyprus", rationale: "Correct. Feast: December 12." },
        { id: "b", text: "St. Nicholas of Myra" },
        { id: "c", text: "St. Basil the Great" },
        { id: "d", text: "St. Athanasius" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, December 12" }],
    },
    {
      id: "saint-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["macrina-elder"],
      prompt: "Who is St. Macrina the Elder?",
      choices: [
        { id: "a", text: "Grandmother of Basil the Great and Gregory of Nyssa; disciple of St. Gregory the Wonderworker; transmitted the faith through her family.", rationale: "Correct. Feast: January 14." },
        { id: "b", text: "The sister of Basil" },
        { id: "c", text: "A 5th-century abbess" },
        { id: "d", text: "Mother of John Chrysostom" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, January 14" }],
    },
    {
      id: "saint-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["catherine"],
      prompt: "Which 4th-century virgin-martyr of Alexandria, an intellectual prodigy, is patroness of philosophers and the Sinai monastery?",
      choices: [
        { id: "a", text: "St. Catherine of Alexandria", rationale: "Correct. Feast: November 25. Monastery of St. Catherine on Mount Sinai contains her relics." },
        { id: "b", text: "St. Barbara" },
        { id: "c", text: "St. Anastasia" },
        { id: "d", text: "St. Theodora" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, November 25" }],
    },
    {
      id: "saint-fp-007",
      kind: "mcq",
      difficulty: 3,
      tags: ["paraskeva"],
      prompt: "Who is St. Paraskeva (Petka) of the Balkans?",
      choices: [
        { id: "a", text: "11th-century Bulgarian-born ascetic, much venerated across the Balkans (Bulgaria, Romania, Serbia); feast: October 14.", rationale: "Correct." },
        { id: "b", text: "An early martyr of the 2nd century only" },
        { id: "c", text: "A Russian fool-for-Christ" },
        { id: "d", text: "A monastery on Mount Athos" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, October 14" }],
    },
    {
      id: "saint-fp-008",
      kind: "mcq",
      difficulty: 4,
      tags: ["arsenios-cappadocian"],
      prompt: "Who was St. Arsenios the Cappadocian, and what is his connection to St. Paisios?",
      choices: [
        { id: "a", text: "Arsenios (1840-1924) was a Cappadocian priest-monk-wonderworker; he baptized the future St. Paisios in 1924. Glorified 1986.", rationale: "Correct." },
        { id: "b", text: "An ancient martyr" },
        { id: "c", text: "An Anglican convert" },
        { id: "d", text: "A fictional figure" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Elder Paisios, Arsenios the Cappadocian (vita)" }],
    },
  ],
};
