import type { Topic } from "@/lib/types";

export const saintsFactsPack: Topic = {
  id: "saints-facts-pack",
  title: "Saints — Quick Recall Pack",
  summary: "MCQs on major saints, their feasts, and titles.",
  learningObjectives: ["Match each saint to feast and title."],
  primarySources: ["Synaxarion; Lives of the Saints"],
  items: [
    {
      id: "saint-fp-001",
      kind: "mcq",
      difficulty: 1,
      tags: ["theotokos"],
      prompt: "On what date is the Dormition of the Theotokos celebrated?",
      choices: [
        { id: "a", text: "August 15 — preceded by the two-week Dormition Fast (August 1-14).", rationale: "The 'falling-asleep' of the Mother of God. One of the Twelve Great Feasts." },
        { id: "b", text: "September 8 — the Nativity of the Theotokos.", rationale: "Wrong. September 8 IS a major Marian feast (Nativity of the Theotokos), but it is her BIRTH, not her DORMITION." },
        { id: "c", text: "November 21 — the Entrance of the Theotokos into the Temple.", rationale: "Wrong. Nov 21 IS a major Marian feast (Entry of the Theotokos), but it is her childhood presentation, not the Dormition." },
        { id: "d", text: "March 25 — the Annunciation by the Archangel Gabriel.", rationale: "Wrong. March 25 IS a major Marian feast (Annunciation), nine months before Christmas, but is not the Dormition." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion, August 15" }],
    },
    {
      id: "saint-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["theotokos", "annunciation"],
      prompt: "On what date is the Annunciation celebrated?",
      choices: [
        { id: "a", text: "March 25 — exactly nine months before the Nativity on December 25.", rationale: "Set by this calculation. Conjoined with the Annunciation Liturgy of St. Basil if it falls within Great Lent." },
        { id: "b", text: "August 15 — the Dormition of the Theotokos.", rationale: "Wrong. The Dormition is Aug 15; the Annunciation is March 25." },
        { id: "c", text: "September 8 — the Nativity of the Theotokos.", rationale: "Wrong. The Theotokos's own nativity is Sept 8; the Annunciation (conception of Christ) is March 25." },
        { id: "d", text: "December 25 — the Nativity of Christ itself.", rationale: "Wrong. Dec 25 is the BIRTH of Christ; the Annunciation (conception) is nine months earlier on March 25." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion, March 25" }],
    },
    {
      id: "saint-fp-003",
      kind: "mcq",
      difficulty: 2,
      tags: ["forerunner"],
      prompt: "Who is honored in Orthodox usage as 'the Forerunner' (Prodromos)?",
      choices: [
        { id: "a", text: "St. John the Baptist — 'Voice of one crying in the wilderness, prepare ye the way of the Lord' (Is 40:3).", rationale: "Multiple feasts: Conception (Sep 23), Nativity (Jun 24), Beheading (Aug 29), Synaxis (Jan 7), Three Findings of his Honored Head." },
        { id: "b", text: "St. Elijah the Prophet — the prophet who anointed kings and ascended in the chariot of fire.", rationale: "Wrong. Elijah is the great OT prophet (feast July 20) but is not 'the Forerunner' of Christ; that title belongs to John the Baptist." },
        { id: "c", text: "St. Isaiah the Prophet — author of the longest OT prophetic book.", rationale: "Wrong. Isaiah's prophecies (especially Is 40:3, 53) preceded Christ but he is not titled 'the Forerunner.'" },
        { id: "d", text: "St. Stephen the Protomartyr — first Christian martyr.", rationale: "Wrong. Stephen is the first MARTYR (Dec 27), not the Forerunner. He followed Christ in martyrdom, not preceding His ministry." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion entries for January 7 (Synaxis of the Forerunner)" }],
    },
    {
      id: "saint-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["spyridon"],
      prompt:
        "Which 4th-century bishop, a former shepherd, attended Nicaea and demonstrated the Trinity by squeezing a brick into fire, water, and clay?",
      choices: [
        { id: "a", text: "St. Spyridon of Tremithus (Cyprus) — feast December 12.", rationale: "His relics on Corfu are reputed to wear out a new pair of slippers each year. Patron of Corfu and of Cyprus." },
        { id: "b", text: "St. Nicholas of Myra — feast December 6.", rationale: "Wrong. Nicholas of Myra attended Nicaea but the brick miracle is attributed to Spyridon, not Nicholas." },
        { id: "c", text: "St. Basil the Great — Cappadocian father.", rationale: "Wrong. Basil (~330-379) was born after Nicaea (325) and is a later Trinitarian defender at Constantinople I (381)." },
        { id: "d", text: "St. Athanasius the Great — Pope of Alexandria.", rationale: "Wrong. Athanasius DID attend Nicaea (as a young deacon) but is not the source of the brick story; that is Spyridon." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, December 12" }],
    },
    {
      id: "saint-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["macrina-elder"],
      prompt: "Who is St. Macrina the Elder?",
      choices: [
        { id: "a", text: "Grandmother of Basil the Great and Gregory of Nyssa; disciple of St. Gregory the Wonderworker; transmitted the faith to her family through the Diocletianic persecution.", rationale: "Feast January 14. To be distinguished from her granddaughter Macrina the Younger (~327-379), sister of Basil." },
        { id: "b", text: "The elder sister of Basil and Gregory of Nyssa, who founded a female monastic community at Annesi.", rationale: "Wrong. That is MACRINA THE YOUNGER, the granddaughter. Macrina the Elder is the GRANDMOTHER." },
        { id: "c", text: "A 5th-century Egyptian abbess associated with the Wadi Natrun monasteries.", rationale: "Wrong. Macrina the Elder is 3rd-c. Cappadocian, not 5th-c. Egyptian." },
        { id: "d", text: "Mother of John Chrysostom, famed for raising her son as a single mother in Antioch.", rationale: "Wrong. Chrysostom's mother is St. Anthusa (4th c. Antioch) — also a real saint. Macrina the Elder is a different woman, the Cappadocian grandmother." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, January 14; Gregory the Theologian's funeral oration on Basil mentions her" }],
    },
    {
      id: "saint-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["catherine"],
      prompt:
        "Which 4th-century virgin-martyr of Alexandria is patroness of philosophers and of the Sinai monastery that bears her name?",
      choices: [
        { id: "a", text: "St. Catherine of Alexandria — feast November 25.", rationale: "Legendarily debated fifty pagan philosophers and converted them; martyred by the wheel. Her relics are kept at St. Catherine's Monastery on Mt. Sinai." },
        { id: "b", text: "St. Barbara of Heliopolis — feast December 4.", rationale: "Wrong. Barbara IS a real virgin-martyr (~3rd-4th c.) but martyred by her own father (per the legend), not associated with philosophers or Sinai." },
        { id: "c", text: "St. Anastasia the Pharmacolytria — feast December 22.", rationale: "Wrong. Anastasia ('the Deliverer from Potions') is a real martyr (4th c.) but lived in Sirmium / Rome, not Alexandria, and is patroness of healing, not philosophy." },
        { id: "d", text: "St. Theodora of Alexandria — feast September 11.", rationale: "Wrong. There is a St. Theodora of Alexandria (5th c. disguised-as-monk ascetic), but Catherine is the philosopher-martyr." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, November 25" }],
    },
    {
      id: "saint-fp-007",
      kind: "mcq",
      difficulty: 3,
      tags: ["paraskeva"],
      prompt: "Who is St. Paraskeva (Petka) of the Balkans?",
      choices: [
        { id: "a", text: "An 11th-century Bulgarian-born ascetic widely venerated across Bulgaria, Romania, and Serbia; feast October 14.", rationale: "Her relics now rest at the Three Hierarchs Cathedral in Iași, Romania. To be distinguished from earlier saints of the same name (Paraskeva of Iconium, etc.)." },
        { id: "b", text: "An early 2nd-century Iconian virgin-martyr beheaded under Antoninus Pius.", rationale: "Wrong. That IS a real saint — Paraskeva of Iconium (feast July 26). But the Balkan Paraskeva is the 11th-c. Bulgarian ascetic." },
        { id: "c", text: "A Russian fool-for-Christ (Yurodivaya) commemorated alongside St. Xenia of Petersburg.", rationale: "Wrong. Yurodstvo IS a real Russian category (Xenia, Basil the Blessed, etc.), but Paraskeva of the Balkans is a different category." },
        { id: "d", text: "A monastery on Mount Athos founded by Athanasios the Athonite in the 10th century.", rationale: "Wrong. The Athonite monasteries are real (Great Lavra etc.) but no major Athonite monastery is named Paraskeva." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Synaxarion, October 14" }],
    },
    {
      id: "saint-fp-008",
      kind: "mcq",
      difficulty: 4,
      tags: ["arsenios-cappadocian"],
      prompt: "Who was St. Arsenios the Cappadocian, and how is he connected to St. Paisios?",
      choices: [
        { id: "a", text: "A Cappadocian priest-monk-wonderworker (1840-1924); baptized the future St. Paisios in 1924; glorified 1986.", rationale: "Paisios's biography of Arsenios is the principal source. The two are commemorated together in Athonite tradition." },
        { id: "b", text: "An ancient martyr of the Diocletianic persecution venerated in Cappadocia.", rationale: "Wrong. Many Cappadocian martyrs exist (Forty of Sebaste, etc.), but THIS Arsenios is 19th-20th c., not ancient." },
        { id: "c", text: "An Anglican convert to Orthodoxy who served as Paisios's spiritual father on Athos.", rationale: "Wrong. Arsenios was native Greek Orthodox, not an Anglican convert. He was Paisios's geographical compatriot, not Athonite mentor." },
        { id: "d", text: "A literary character in a contemporary Greek novel, sometimes mistaken for a real saint.", rationale: "Wrong. He is a real, glorified saint (1986) — not fictional." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Elder Paisios, Arsenios the Cappadocian (vita); Synaxarion, Nov 10" }],
    },
  ],
};
