import type { Topic } from "@/lib/types";

export const practicesFinalPack: Topic = {
  id: "practices-final-pack",
  title: "Practices — Final Pack",
  summary: "Final MCQs on Orthodox practices.",
  learningObjectives: ["Drill final details."],
  primarySources: ["Typikon; Trebnik"],
  items: [
    {
      id: "prac-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["sign-of-cross"],
      prompt: "How does an Orthodox Christian make the sign of the cross?",
      choices: [
        { id: "a", text: "Right hand, three fingers joined (Trinity) with the other two folded into the palm (two natures of Christ); forehead, belly, right shoulder, left shoulder.", rationale: "Correct." },
        { id: "b", text: "Left-to-right (Western Catholic order)" },
        { id: "c", text: "Two fingers (the Russian Old Believer practice)" },
        { id: "d", text: "One finger only" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Eastern liturgical practice" }],
    },
    {
      id: "prac-final-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["epiphany-blessing"],
      prompt: "Why does the Theophany water reportedly not spoil?",
      choices: [
        { id: "a", text: "By the prayers of the Church and the blessing of the Holy Spirit at the Great Blessing of Waters; the phenomenon has been observed for centuries in many places.", rationale: "Correct (tradition; some scientific commentary exists)." },
        { id: "b", text: "It is mixed with vinegar" },
        { id: "c", text: "It is boiled" },
        { id: "d", text: "It is sealed in vacuum" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Trebnik — Great Blessing of Waters; traditional reports" }],
    },
    {
      id: "prac-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["sticheron"],
      prompt: "What is a sticheron in Orthodox liturgical use?",
      choices: [
        { id: "a", text: "A short hymn-stanza, typically sung with a refrain or psalm verse, in Vespers and Matins.", rationale: "Correct." },
        { id: "b", text: "A type of vestment" },
        { id: "c", text: "A pilgrimage" },
        { id: "d", text: "A fast day" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Octoechos and Menaion — service hymnography" }],
    },
    {
      id: "prac-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["bow-prostration"],
      prompt: "What are the two principal physical postures of Orthodox prayer?",
      choices: [
        { id: "a", text: "Bow (metaniyu — at the waist) and prostration (zemnoy poklon — to the ground)", rationale: "Correct. Made at various moments of prayer and Liturgy." },
        { id: "b", text: "Sitting and kneeling" },
        { id: "c", text: "Walking and standing" },
        { id: "d", text: "Lying prone and squatting" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Orthodox liturgical practice" }],
    },
    {
      id: "prac-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["five-loaves"],
      prompt: "What is the 'blessing of the five loaves' (Artoklasia)?",
      choices: [
        { id: "a", text: "An evening service of blessing five loaves of bread, wheat, wine, and oil, often included at festal vigils. Symbolizes the multiplication of loaves; the blessed bread is distributed.", rationale: "Correct." },
        { id: "b", text: "A baptismal ritual" },
        { id: "c", text: "An ordination rite" },
        { id: "d", text: "A funeral service" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion — Order of the Blessing of Loaves" }],
    },
    {
      id: "prac-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["chrism-myrrh"],
      prompt: "How is Holy Chrism (myron) produced and used?",
      choices: [
        { id: "a", text: "Olive oil with up to 40 aromatic spices, consecrated by an autocephalous synod (typically every several years), then distributed to all parishes for chrismation of newly-baptized.", rationale: "Correct." },
        { id: "b", text: "Pure olive oil with no additives" },
        { id: "c", text: "Wine alone" },
        { id: "d", text: "Synthetic perfume" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Trebnik; Hieratikon — Order of the Consecration of Holy Chrism" }],
    },
    {
      id: "prac-final-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["typikon"],
      prompt: "What is the Typikon?",
      choices: [
        { id: "a", text: "The book of rules governing Orthodox liturgical services — order, hymns, readings — coordinating the fixed and movable cycles.", rationale: "Correct. The Typikon of St. Sabbas (Jerusalem) is the foundational text; the Russian and Greek typika are variants." },
        { id: "b", text: "A theological treatise" },
        { id: "c", text: "A devotional manual" },
        { id: "d", text: "A vestment" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Typikon of St. Sabbas (the Jerusalem-Sabbaite typikon)" }],
    },
  ],
};
