import type { Topic } from "@/lib/types";

export const practicesFinalPack: Topic = {
  id: "practices-final-pack",
  title: "Practices — Final Pack",
  summary: "Final MCQs on Orthodox practices.",
  learningObjectives: ["Drill final details."],
  primarySources: ["Typikon; Trebnik"],
  items: [
    {
      id: "prac-final-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["sign-of-cross"],
      prompt: "How does an Orthodox Christian make the sign of the cross?",
      choices: [
        { id: "a", text: "Right hand, three fingers joined (Trinity), the other two folded into the palm (two natures of Christ); forehead, belly, right shoulder, then left shoulder.", rationale: "The triple-finger configuration and right-to-left order distinguish Orthodox from Roman Catholic practice and from the Old Believer two-finger configuration." },
        { id: "b", text: "Left hand only — to reserve the right hand for the priestly blessing.", rationale: "Wrong. The Orthodox cross themselves with the RIGHT hand; the priestly blessing is also with the right hand." },
        { id: "c", text: "Left-to-right shoulder, in the Roman Catholic Latin order.", rationale: "Wrong. Orthodox cross themselves RIGHT-TO-LEFT shoulder; Roman Catholics cross LEFT-TO-RIGHT. The orders are deliberately opposite." },
        { id: "d", text: "Two fingers extended (index and middle), as the Russian Old Believer practice.", rationale: "Wrong. Two fingers was the older Russian practice before the Nikonian reforms (1666-67). Modern Orthodox use three fingers; Old Believers retain two." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Eastern liturgical practice; Pedalion notes on the sign of the cross" }],
    },
    {
      id: "prac-final-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["epiphany-blessing"],
      prompt: "Why is the Theophany water (blessed January 6) reputed not to spoil?",
      choices: [
        { id: "a", text: "By the prayers of the Church and the sanctifying action of the Holy Spirit; a phenomenon observed and reported for centuries.", rationale: "Trebnik, Great Blessing of Waters. Some modern scientific analyses have noted reduced bacterial growth in the water for extended periods, but the traditional explanation is theological." },
        { id: "b", text: "Because it is mixed with consecrated vinegar from the Holy Friday vigil.", rationale: "Wrong. No vinegar is added. The Theophany water is simply blessed water." },
        { id: "c", text: "Because it is boiled and sealed in airtight vessels during the blessing.", rationale: "Wrong. The water is blessed cold and stored in open vessels in many homes." },
        { id: "d", text: "Because the priest adds a fragment of consecrated antimension to each container.", rationale: "Wrong. The antimension is a consecrated cloth, not a substance added to water." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Trebnik — Great Blessing of Waters; traditional reports across many jurisdictions" }],
    },
    {
      id: "prac-final-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["sticheron"],
      prompt: "What is a sticheron in Orthodox liturgical use?",
      choices: [
        { id: "a", text: "A short hymn-stanza, typically alternated with a psalm verse, in Vespers and Matins.", rationale: "From Greek stichos ('verse'). Different stichera are appointed for each tone of the Octoechos cycle and each feast in the Menaion." },
        { id: "b", text: "A type of priestly vestment worn during the Liturgy.", rationale: "Wrong. Vestments include sticharion (the under-tunic), but a sticheron is a hymn, not a vestment." },
        { id: "c", text: "A pilgrimage to a major shrine, undertaken once in a lifetime.", rationale: "Wrong. Pilgrimage (proskynitis) is a real Orthodox practice but is not called a sticheron." },
        { id: "d", text: "A specific fasting day appointed by the Typikon during the Lenten cycle.", rationale: "Wrong. Lenten fasting is governed by the Triodion typikon; sticheron is a hymn." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Octoechos and Menaion — service hymnography" }],
    },
    {
      id: "prac-final-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["bow-prostration"],
      prompt: "What are the two principal physical postures of Orthodox prayer (beyond standing)?",
      choices: [
        { id: "a", text: "A waist-bow (metania) and a full prostration to the ground (zemnoy poklon / megale metania).", rationale: "Used at various points in Liturgy, Vespers, and especially during the Lenten Prayer of St. Ephrem the Syrian (with prostrations at each petition)." },
        { id: "b", text: "Sitting cross-legged and kneeling on one knee.", rationale: "Wrong. Orthodox prayer normally stands or prostrates; kneeling is not the principal posture (in fact, on Sundays kneeling is canonically forbidden — canon 20 of Nicaea I)." },
        { id: "c", text: "Walking in procession and standing with arms outstretched.", rationale: "Wrong. Processions occur, but the principal postures are bow and prostration, not walking." },
        { id: "d", text: "Lying flat on the back and squatting on the heels.", rationale: "Wrong. Lying-flat prostration (lying full-length face down) is part of some monastic practices but is not the standard pair with bowing." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Triodion — Lenten Prayer of St. Ephrem with three prostrations" }],
    },
    {
      id: "prac-final-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["five-loaves"],
      prompt: "What is the 'Blessing of the Five Loaves' (Artoklasia)?",
      choices: [
        { id: "a", text: "An evening service blessing five loaves of bread, wheat, wine, and oil — typically at festal vigils; the blessed bread is distributed.", rationale: "Symbolizes the multiplication of the loaves in the Gospel feeding miracle. Inserted between Vespers and Matins on great feasts in the all-night vigil." },
        { id: "b", text: "A baptismal ritual in which the catechumen receives five loaves before immersion.", rationale: "Wrong. Baptism includes anointing with oil, exorcism, and water, but no five-loaves ritual." },
        { id: "c", text: "An ordination rite in which the candidate offers five loaves to the bishop.", rationale: "Wrong. Ordination involves the laying on of hands, not a five-loaves offering." },
        { id: "d", text: "A funeral service in which five loaves are distributed to the poor in memory of the deceased.", rationale: "Wrong. Funeral and memorial services involve koliva (boiled wheat with honey/raisins), not five-loaves." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion — Order of the Blessing of Loaves (Artoklasia)" }],
    },
    {
      id: "prac-final-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["chrism-myrrh"],
      prompt: "How is Holy Chrism (myron) produced and used?",
      choices: [
        { id: "a", text: "Olive oil compounded with up to 40 aromatic spices and consecrated by an autocephalous synod, then distributed to all parishes for use in Chrismation.", rationale: "Consecrated approximately every decade by the Ecumenical Patriarch and other autocephalous primates. Used at the seal of the Holy Spirit immediately after baptism." },
        { id: "b", text: "Pure olive oil with no additives, blessed by the local parish priest each Holy Saturday.", rationale: "Wrong. Pure olive oil blessed at the parish IS used for Holy Unction (Anointing of the Sick), but the CHRISM is a different consecration — done by a synod with aromatic spices." },
        { id: "c", text: "Wine alone, used for the anointing of the sick by elderly clergy.", rationale: "Wrong. Wine is used at the Eucharist, not as Chrism." },
        { id: "d", text: "Synthetic perfume manufactured commercially and blessed for liturgical use.", rationale: "Wrong. Holy Chrism is olive oil and natural spices, not synthetic perfume." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Trebnik; Hieratikon — Order of the Consecration of Holy Chrism" }],
    },
    {
      id: "prac-final-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["typikon"],
      prompt: "What is the Typikon?",
      choices: [
        { id: "a", text: "The Orthodox liturgical rulebook coordinating the fixed-calendar (Menaion), Lenten (Triodion), and Pentecost-to-Lent (Pentecostarion) cycles.", rationale: "The Typikon of St. Sabbas (Jerusalem-Sabbaite) is the foundational text; Russian and Greek variants exist. Without it, the day's services cannot be correctly assembled from the books." },
        { id: "b", text: "A patristic theological treatise on the spiritual life, attributed to Pseudo-Dionysius.", rationale: "Wrong. Pseudo-Dionysius's works (Divine Names, Mystical Theology, Celestial Hierarchy, Ecclesiastical Hierarchy) are theological — not the Typikon (a liturgical book)." },
        { id: "c", text: "A lay devotional manual for the prayer rule and Jesus Prayer.", rationale: "Wrong. Devotional manuals exist (prayer books, Theophan the Recluse's letters) but are not the Typikon." },
        { id: "d", text: "A specific type of priestly vestment worn at the Liturgy of St. Basil.", rationale: "Wrong. Vestments are sticharion, epitrachelion, etc. The Typikon is a book of liturgical rules." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Typikon of St. Sabbas (Jerusalem-Sabbaite Typikon)" }],
    },
  ],
};
