import type { Topic } from "@/lib/types";

export const practicesFactsPack: Topic = {
  id: "practices-facts-pack",
  title: "Practices — Quick Recall",
  summary: "MCQ pack on liturgical and ascetical practice.",
  learningObjectives: ["Drill the details of practice."],
  primarySources: ["Typikon; Trebnik; Pedalion"],
  items: [
    {
      id: "prac-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["liturgy", "chrysostom"],
      prompt: "Which Liturgy is served on most Sundays of the year in Orthodox parishes?",
      choices: [
        { id: "a", text: "The Liturgy of St. John Chrysostom", rationale: "Correct. St. Basil is used 10 times/year; Presanctified during Lent." },
        { id: "b", text: "The Liturgy of St. Basil" },
        { id: "c", text: "The Liturgy of St. James" },
        { id: "d", text: "The Liturgy of St. Mark" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Sunday Liturgical Cycle" }],
    },
    {
      id: "prac-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["presanctified"],
      prompt: "When is the Liturgy of the Presanctified Gifts served?",
      choices: [
        { id: "a", text: "Weekdays of Great Lent (typically Wed and Fri), and the first three days of Holy Week.", rationale: "Correct. The Eucharistic gifts are consecrated on the previous Sunday and distributed at this Vesperal Liturgy." },
        { id: "b", text: "Every Sunday" },
        { id: "c", text: "Only on Pascha" },
        { id: "d", text: "Christmas Eve only" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Triodion — Lenten typikon" }],
    },
    {
      id: "prac-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["epiphany"],
      prompt: "On Theophany (Jan 6), what major liturgical act takes place after Liturgy?",
      choices: [
        { id: "a", text: "The Great Blessing of Waters, often at a body of water — sea, river, lake — outdoors.", rationale: "Correct." },
        { id: "b", text: "A procession with the Cross" },
        { id: "c", text: "The Akathist to the Theotokos" },
        { id: "d", text: "The reading of the Synodikon" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion, January 6 — Great Blessing of Waters" }],
    },
    {
      id: "prac-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["pascha", "trisagion"],
      prompt: "What is the Paschal greeting in Greek?",
      choices: [
        { id: "a", text: "'Christos Anesti!' — 'Alithos Anesti!' (Christ is risen! — Truly He is risen!)", rationale: "Correct. Greeting throughout the Paschal season." },
        { id: "b", text: "'Kyrie eleison!'" },
        { id: "c", text: "'Agios o Theos!'" },
        { id: "d", text: "'Doxa soi!'" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pentecostarion" }],
    },
    {
      id: "prac-fp-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["iconostasis"],
      prompt: "What is on the iconostasis (icon screen)?",
      choices: [
        { id: "a", text: "Standard arrangement: Christ to the right of the Holy Doors, Theotokos to the left; deesis row; festal row; prophets row.", rationale: "Correct." },
        { id: "b", text: "Only modern art" },
        { id: "c", text: "Only the Crucifix" },
        { id: "d", text: "Nothing — it is a plain veil" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Standard Russian / Greek iconographic typika" }],
    },
    {
      id: "prac-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["prosphora"],
      prompt: "What is the prosphora?",
      choices: [
        { id: "a", text: "The leavened wheaten bread baked for the Eucharist, stamped with a cross and the letters IC XC NIKA.", rationale: "Correct." },
        { id: "b", text: "The communion cup" },
        { id: "c", text: "The chalice cover" },
        { id: "d", text: "The reader's tonsure" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Order of the Proskomedia" }],
    },
  ],
};
