import type { Topic } from "@/lib/types";

export const practicesFactsPack: Topic = {
  id: "practices-facts-pack",
  title: "Practices — Quick Recall",
  summary: "MCQ pack on liturgical and ascetical practice.",
  learningObjectives: ["Drill the details of practice."],
  primarySources: ["Typikon; Trebnik; Pedalion"],
  items: [
    {
      id: "prac-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["liturgy", "chrysostom"],
      prompt: "Which Liturgy is served on most Sundays of the year in Orthodox parishes?",
      choices: [
        { id: "a", text: "The Liturgy of St. John Chrysostom — the ordinary Sunday liturgy.", rationale: "St. Basil is used on appointed days (5 Sundays of Lent, Holy Thursday/Saturday, Eves of Nativity and Theophany, Jan 1); the Presanctified is used on Lenten weekdays." },
        { id: "b", text: "The Liturgy of St. Basil the Great — the ancient Cappadocian rite.", rationale: "Wrong. Basil's Liturgy IS used in the Orthodox Church, but on ten appointed days a year, not on most Sundays." },
        { id: "c", text: "The Liturgy of St. James, brother of the Lord — the most ancient extant Liturgy.", rationale: "Wrong. The Liturgy of St. James IS the most ancient extant text, but it is used only on October 23 (his feast day) and occasionally elsewhere — not weekly." },
        { id: "d", text: "The Liturgy of St. Mark — the ancient Alexandrian rite.", rationale: "Wrong. The Liturgy of St. Mark is a real ancient Alexandrian Liturgy but is not used regularly in current Orthodox practice (chiefly Coptic and Ethiopian)." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Sunday Liturgical Cycle" }],
    },
    {
      id: "prac-fp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["presanctified"],
      prompt: "When is the Liturgy of the Presanctified Gifts served?",
      choices: [
        { id: "a", text: "On weekdays of Great Lent (typically Wednesday and Friday) and on the first three days of Holy Week.", rationale: "Attributed to St. Gregory the Dialogist (Pope Gregory the Great). The gifts are consecrated on the previous Sunday and reserved." },
        { id: "b", text: "On every Sunday of the year as a more solemn alternative to Chrysostom's Liturgy.", rationale: "Wrong. Presanctified is reserved for LENTEN WEEKDAYS, never Sundays (Sundays have full Liturgies, since they are not strict-fast days)." },
        { id: "c", text: "Only on Pascha (Easter) night, as the culmination of Holy Saturday.", rationale: "Wrong. Pascha has the full Paschal Liturgy of St. Chrysostom, not Presanctified. Holy Saturday morning is St. Basil's." },
        { id: "d", text: "On the Eve of Christmas (Theophany) as a Eucharistic vigil.", rationale: "Wrong. Christmas Eve and Theophany Eve have the Liturgy of St. BASIL, not Presanctified." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Triodion — Lenten typikon" }],
    },
    {
      id: "prac-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["epiphany"],
      prompt:
        "On Theophany (January 6), what major liturgical act follows the Divine Liturgy?",
      choices: [
        { id: "a", text: "The Great Blessing of Waters — often performed at an open body of water (sea, river, lake).", rationale: "Sanctifies water for the year. The Greek tradition includes the priest throwing the Cross into the water and swimmers diving to retrieve it. Theophany water reportedly does not spoil." },
        { id: "b", text: "A procession with the Cross around the outside of the church, similar to Pascha.", rationale: "Wrong. The Paschal procession occurs at midnight on Holy Saturday-Pascha. Theophany has the WATER blessing, not a Cross procession." },
        { id: "c", text: "The chanting of the Akathist Hymn to the Theotokos.", rationale: "Wrong. The Akathist Hymn is chanted on Fridays of Lent and on Akathist Saturday, not at Theophany." },
        { id: "d", text: "The reading of the Synodikon of Orthodoxy.", rationale: "Wrong. The Synodikon is read on the FIRST SUNDAY OF LENT (Triumph of Orthodoxy), not at Theophany." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Festal Menaion, January 6 — Great Blessing of Waters" }],
    },
    {
      id: "prac-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["pascha"],
      prompt: "What is the Paschal greeting in Greek?",
      choices: [
        { id: "a", text: "'Christos Anesti!' — answered 'Alithos Anesti!' (Christ is risen! — Truly He is risen!)", rationale: "Greeting throughout the forty days of the Paschal season until Ascension. Equivalent in Slavonic: Christos Voskrese / Voistinu Voskrese." },
        { id: "b", text: "'Kyrie eleison!' — the universal Eastern Christian prayer used throughout the year.", rationale: "Wrong. Kyrie eleison (Lord have mercy) is the constant liturgical refrain, not the Paschal greeting." },
        { id: "c", text: "'Agios o Theos!' — the opening line of the Trisagion hymn.", rationale: "Wrong. 'Holy God, Holy Mighty, Holy Immortal' is the Trisagion, a normal liturgical hymn, not the Paschal greeting." },
        { id: "d", text: "'Doxa soi, Kyrie, doxa soi!' — the response after the Gospel reading.", rationale: "Wrong. 'Glory to Thee, O Lord, glory to Thee' is sung after the Gospel, not as a Paschal greeting." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pentecostarion; Paschal Hours" }],
    },
    {
      id: "prac-fp-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["iconostasis"],
      prompt: "What is the standard arrangement of icons on the iconostasis?",
      choices: [
        { id: "a", text: "Christ to the right of the Holy Doors, Theotokos to the left, with rows of Deesis, festal, and prophet icons above.", rationale: "Russian iconostases tend to be tall with five rows; Greek tend to be shorter. The local saint or patron is often beside Christ." },
        { id: "b", text: "Only modern art icons, since traditional icons are considered too ancient for ordinary parish use.", rationale: "Wrong. Traditional Byzantine-style icons are universal in Orthodoxy. 'Modern art' is foreign to Orthodox liturgical iconography." },
        { id: "c", text: "Only a single crucifix at the center, in conformity with the early Byzantine tradition.", rationale: "Wrong. The Cross is often above the iconostasis (the 'Calvary group'), but full iconographic programs are the norm." },
        { id: "d", text: "Nothing — the iconostasis is a plain veil dividing the altar from the nave.", rationale: "Wrong. The pre-iconostasis tradition (early Christian altar rails, veils) WAS plain in places, but the developed iconostasis is iconographically populated." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Russian and Greek iconographic typika; Symeon of Thessalonica on the templon" }],
    },
    {
      id: "prac-fp-006",
      kind: "mcq",
      difficulty: 3,
      tags: ["prosphora"],
      prompt: "What is the prosphora?",
      choices: [
        { id: "a", text: "Leavened wheaten bread baked for the Eucharist, stamped with a cross and the letters IC XC NIKA ('Jesus Christ conquers').", rationale: "Used at the Proskomedia (preparation) where the priest cuts the Lamb from the larger prosphora and places particles for the Theotokos, saints, living, and departed around it." },
        { id: "b", text: "The chalice (potirion) used to hold the consecrated wine.", rationale: "Wrong. The chalice is a sacred vessel; prosphora is the bread." },
        { id: "c", text: "The veil that covers the chalice during the Great Entrance.", rationale: "Wrong. The chalice cover (aer/podizhda) is a separate liturgical textile, not the prosphora." },
        { id: "d", text: "The ceremony of reader's tonsure performed for a young man entering minor orders.", rationale: "Wrong. Tonsure is a sacramental rite; prosphora is the Eucharistic bread." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Order of the Proskomedia" }],
    },
  ],
};
