import type { Topic } from "@/lib/types";

export const rccFinalPack: Topic = {
  id: "rcc-final-pack",
  title: "RCC Final Drill Pack",
  summary: "Final MCQ pack on EO vs RCC distinctives.",
  learningObjectives: ["Drill the full landscape of distinctions."],
  primarySources: ["Catechism of the Catholic Church; conciliar documents"],
  items: [
    {
      id: "rcc-fp-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["catechism"],
      prompt: "What is the current authoritative summary of Roman Catholic doctrine?",
      choices: [
        { id: "a", text: "The Catechism of the Catholic Church (1992, revised 1997, currently in 4-Part format)", rationale: "Correct." },
        { id: "b", text: "The 39 Articles" },
        { id: "c", text: "The Westminster Confession" },
        { id: "d", text: "The Confession of Dositheus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Paul II, Fidei Depositum (1992)" }],
    },
    {
      id: "rcc-fp-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["pope-john-paul-ii"],
      prompt: "How long was John Paul II's pontificate?",
      choices: [
        { id: "a", text: "Over 26 years (1978-2005) — the second longest in history.", rationale: "Correct. Only Pius IX served longer (1846-78, 31+ years)." },
        { id: "b", text: "Less than a year" },
        { id: "c", text: "About 10 years" },
        { id: "d", text: "About 50 years" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Vatican biographical records" }],
    },
    {
      id: "rcc-fp-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["vatican-i", "infallibility-criteria"],
      prompt: "According to Vatican I's Pastor Aeternus, what conditions must be met for a papal statement to be considered infallible (ex cathedra)?",
      choices: [
        { id: "a", text: "The Pope must be (1) speaking as 'pastor and teacher of all Christians,' (2) defining a doctrine concerning faith or morals, (3) by his supreme apostolic authority, (4) to be held by the whole Church.", rationale: "Correct." },
        { id: "b", text: "Any statement by any Pope" },
        { id: "c", text: "Statements signed by all Cardinals" },
        { id: "d", text: "Statements made on Holy Thursday only" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Vatican I, Pastor Aeternus (1870), Chapter 4" }],
    },
    {
      id: "rcc-fp-004",
      kind: "mcq",
      difficulty: 4,
      tags: ["pope-pius-x"],
      prompt: "Which early-20th-century Pope crushed the 'Modernist' movement in Roman Catholic theology?",
      choices: [
        { id: "a", text: "Pius X (1903-14) — Pascendi Dominici Gregis (1907) condemned Modernism; the Oath Against Modernism (1910).", rationale: "Correct." },
        { id: "b", text: "Pius XII" },
        { id: "c", text: "John XXIII" },
        { id: "d", text: "Paul VI" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pius X, Pascendi Dominici Gregis (1907)" }],
    },
    {
      id: "rcc-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["jesuits"],
      prompt: "What is the Society of Jesus (Jesuits)?",
      choices: [
        { id: "a", text: "A Roman Catholic religious order founded by St. Ignatius of Loyola in 1540, taking vows of obedience to the Pope.", rationale: "Correct." },
        { id: "b", text: "An Orthodox monastic order" },
        { id: "c", text: "A Protestant denomination" },
        { id: "d", text: "A medieval crusading order" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Ignatius of Loyola, Spiritual Exercises; Constitutions" }],
    },
    {
      id: "rcc-fp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["uniate"],
      prompt: "What is 'Uniatism,' from an Orthodox standpoint?",
      choices: [
        { id: "a", text: "The 16th-c. and later Roman strategy of accepting Eastern Christians into full communion with Rome while preserving Byzantine rite (e.g. Brest 1596 for Ukrainian Greek Catholics). Orthodox view: a missionary tactic against Orthodoxy.", rationale: "Correct. Balamand 1993 between Catholic and Orthodox theologians repudiated uniatism as a model for unity." },
        { id: "b", text: "A monastic reform" },
        { id: "c", text: "A medieval war" },
        { id: "d", text: "A council in 1962" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Balamand Statement (1993), §§ 12-13" }],
    },
    {
      id: "rcc-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["assisi"],
      prompt: "What was the 1986 Assisi Day of Prayer for Peace, and what controversy surrounded it?",
      choices: [
        { id: "a", text: "John Paul II's gathering of religious leaders (Christian, Muslim, Buddhist, Hindu, Animist) to pray for peace; criticized within and outside Catholicism as religious indifferentism.", rationale: "Correct. The 1986 image of the Pope alongside the Dalai Lama and a statue of Buddha became a flashpoint." },
        { id: "b", text: "A canonization ceremony" },
        { id: "c", text: "A liturgical reform" },
        { id: "d", text: "A papal funeral" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Coverage in Osservatore Romano, October 1986" }],
    },
  ],
};
