import type { Topic } from "@/lib/types";

export const rcMassQuestions: Topic = {
  id: "rcc-mass-pack",
  title: "RCC Distinctives — Quick Pack",
  summary: "Rapid-fire MCQ on Roman Catholic distinctives and history.",
  learningObjectives: ["Drill the key facts of Catholic history and doctrine."],
  primarySources: ["Catechism of the Catholic Church; conciliar documents"],
  items: [
    {
      id: "rcc-mp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["councils-of-rome"],
      prompt: "How many ecumenical councils does the Roman Catholic Church count?",
      choices: [
        { id: "a", text: "Seven" },
        { id: "b", text: "Fourteen" },
        { id: "c", text: "Twenty-one (counting through Vatican II)", rationale: "Correct. Orthodox count seven; Rome counts 21 (with the medieval Western councils and the Vatican Councils)." },
        { id: "d", text: "Twenty-five" },
      ],
      correctChoiceId: "c",
      citations: [{ source: "Catechism of the Catholic Church §§ 884-885" }],
    },
    {
      id: "rcc-mp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["pope-francis"],
      prompt: "Who was elected Pope in March 2013?",
      choices: [
        { id: "a", text: "Benedict XVI" },
        { id: "b", text: "Francis (Jorge Mario Bergoglio)", rationale: "Correct. The first Jesuit Pope; first from the Americas." },
        { id: "c", text: "John Paul II" },
        { id: "d", text: "Pius XII" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Habemus papam announcement, 13 March 2013" }],
    },
    {
      id: "rcc-mp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["trent"],
      prompt: "The Council of Trent (1545-1563) was convened primarily to:",
      choices: [
        { id: "a", text: "Reform the liturgy" },
        { id: "b", text: "Respond to the Protestant Reformation by defining Catholic doctrine on Scripture, tradition, sacraments, justification, etc.", rationale: "Correct." },
        { id: "c", text: "Define papal infallibility (that was Vatican I, 1870)" },
        { id: "d", text: "Make peace with the East" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Acts of the Council of Trent (1545-1563)" }],
    },
    {
      id: "rcc-mp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["sacrament-of-confession"],
      prompt: "After Lateran IV (1215), what minimum requirement did Roman Catholic faithful have to satisfy yearly?",
      choices: [
        { id: "a", text: "Confess sins to a priest at least once a year and receive communion at Easter.", rationale: "Correct. The 'Easter duty' from Omnis utriusque sexus, Lateran IV, canon 21." },
        { id: "b", text: "Tithe to the parish" },
        { id: "c", text: "Make pilgrimage to Rome" },
        { id: "d", text: "Recite the Rosary daily" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Lateran IV (1215), canon 21" }],
    },
    {
      id: "rcc-mp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["vatican-i"],
      prompt: "What dogma was definitively defined at Vatican I (1870) by Pope Pius IX?",
      choices: [
        { id: "a", text: "Papal infallibility ex cathedra", rationale: "Correct (Pastor Aeternus, ch. 4). Also defined: universal jurisdiction (ch. 3)." },
        { id: "b", text: "Immaculate Conception (that was 1854)" },
        { id: "c", text: "Bodily Assumption (that was 1950)" },
        { id: "d", text: "Co-redemptrix (not formally defined)" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Pastor Aeternus, Vatican I (1870)" }],
    },
    {
      id: "rcc-mp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["latin-mass"],
      prompt: "When did the Roman Mass shift from Latin to vernacular as the ordinary form?",
      choices: [
        { id: "a", text: "Trent (1563)" },
        { id: "b", text: "Vatican II / Novus Ordo Missae of Paul VI (1969-70)", rationale: "Correct." },
        { id: "c", text: "Vatican I (1870)" },
        { id: "d", text: "Council of Florence (1439)" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Paul VI, Missale Romanum (1969)" }],
    },
    {
      id: "rcc-mp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["papal-states"],
      prompt: "When did the Pope cease to be a temporal monarch ruling over the Papal States?",
      choices: [
        { id: "a", text: "1789 (French Revolution)" },
        { id: "b", text: "1870 — Italian unification under Victor Emmanuel II; the Papal States annexed.", rationale: "Correct. Pius IX retreated to the Vatican; the 'Prisoner of the Vatican' era began. Settled by the Lateran Treaty of 1929 creating Vatican City." },
        { id: "c", text: "1929 (Lateran Treaty)" },
        { id: "d", text: "1958 (death of Pius XII)" },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Italian Unification (1870); Lateran Treaty (1929)" }],
    },
    {
      id: "rcc-mp-008",
      kind: "mcq",
      difficulty: 3,
      tags: ["sspx"],
      prompt: "Who was Marcel Lefebvre, and what movement did he lead?",
      choices: [
        { id: "a", text: "A French archbishop who rejected Vatican II's liturgical and ecumenical reforms; founded the Society of Saint Pius X (SSPX) in 1970.", rationale: "Correct. He consecrated bishops without papal permission in 1988 and was declared excommunicated; status now ambiguous under Francis." },
        { id: "b", text: "A Spanish theologian at Vatican II" },
        { id: "c", text: "An Italian saint of the 19th century" },
        { id: "d", text: "A founder of the Society of Jesus" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Paul II, Ecclesia Dei (2 July 1988)" }],
    },
  ],
};

export const rcSpiritualityTopics: Topic = {
  id: "rcc-spirituality",
  title: "RC Spirituality — Distinctives",
  summary: "Rosary, Stations of the Cross, Sacred Heart, devotions to Mary, novenas — comparison with Orthodox practices.",
  learningObjectives: ["Note RC devotional distinctives.", "Compare with Orthodox practice."],
  primarySources: ["Catechism of the Catholic Church Part Four"],
  items: [
    {
      id: "rcc-sp-001",
      kind: "qa",
      difficulty: 3,
      tags: ["rosary"],
      prompt: "What is the Rosary, and is there an Orthodox equivalent?",
      expectedAnswer: "The Rosary is a Roman Catholic devotion: 15 (or 20 since John Paul II added the Luminous Mysteries in 2002) decades of Hail Marys, each decade preceded by an Our Father and followed by a Gloria, meditating on Joyful, Sorrowful, Glorious (and Luminous) Mysteries of Christ and the Virgin. Origin: traditionally attributed to St. Dominic (13th c.), though it developed organically. The Orthodox have the prayer rope (chotki / komboskini) — 50, 100, or 150 knots used with the Jesus Prayer, NOT with Marian repetitions. The akathist hymns to the Theotokos and to specific saints serve a function comparable to the Rosary's Marian meditation, but with a very different theological accent.",
      citations: [{ source: "Catechism of the Catholic Church §§ 2678, 2708" }],
    },
    {
      id: "rcc-sp-002",
      kind: "qa",
      difficulty: 3,
      tags: ["sacred-heart"],
      prompt: "What is the Sacred Heart devotion, and is it received in Orthodoxy?",
      expectedAnswer: "A Roman Catholic devotion that emerged in 17th-century France through the visions of Margaret Mary Alacoque (1647-90). The Sacred Heart of Jesus is depicted as a physical organ, often crowned with thorns and aflame, exposed outside His chest. The image is foreign to Orthodox iconography, which never depicts a body part in isolation. The Orthodox icon of Christ shows the whole Person (typically Christ Pantokrator, Christ the Good Shepherd, etc.). The Orthodox do not receive the Sacred Heart devotion; it represents a sentimental-physiological piety alien to the patristic tradition.",
      citations: [{ source: "Catechism of the Catholic Church § 2669; Margaret Mary Alacoque, Autobiography" }],
    },
    {
      id: "rcc-sp-003",
      kind: "qa",
      difficulty: 3,
      tags: ["stigmata"],
      prompt: "What are the stigmata, and how do Orthodoxy and Roman Catholicism differ on this phenomenon?",
      expectedAnswer: "Stigmata are bodily wounds (typically on hands, feet, side, brow) mirroring Christ's crucifixion wounds, claimed by certain Western mystics (Francis of Assisi 1224, Padre Pio 1918, Catherine of Siena, etc.). The Roman Catholic Church has recognized stigmata as a charism of identification with the suffering Christ. Orthodoxy regards this phenomenon as deeply suspect — a form of bodily mysticism foreign to the patristic tradition, often signaling spiritual delusion (prelest). The genuine union with the suffering Christ in Orthodox tradition is INTERIOR, manifested in tears of repentance and growing love, not in visible bodily wounds.",
      citations: [
        { source: "Ignatius Brianchaninov, On Prelest" },
        { source: "Bonaventure, Major Life of St. Francis 13" },
      ],
    },
    {
      id: "rcc-sp-004",
      kind: "qa",
      difficulty: 3,
      tags: ["fatima"],
      prompt: "What are the Marian apparitions at Fatima, and what is the Orthodox response?",
      expectedAnswer: "From May to October 1917, three Portuguese shepherd children (Lucia, Francisco, Jacinta) reported apparitions of the Virgin Mary at Fatima, Portugal, culminating in the 'Miracle of the Sun' on October 13. The Roman Catholic Church investigated and approved the apparitions in 1930. Three 'secrets' were communicated, the third only published in 2000. The Orthodox response: caution. We do not have a doctrine that rules out post-apostolic appearances of the Theotokos (many Orthodox saints have reported them), but the discernment of such phenomena belongs to the Church, and a confessionally Roman Catholic context is not the Orthodox sphere of discernment. Many Orthodox treat Fatima with theological reserve.",
      citations: [{ source: "Lucia dos Santos, Memoirs" }],
    },
  ],
};
