import type { Topic } from "@/lib/types";

export const rcMassQuestions: Topic = {
  id: "rcc-mass-pack",
  title: "RCC Distinctives — Quick Pack",
  summary: "Rapid-fire MCQ on Roman Catholic distinctives and history.",
  learningObjectives: ["Drill the key facts of Catholic history and doctrine."],
  primarySources: ["Catechism of the Catholic Church; conciliar documents"],
  items: [
    {
      id: "rcc-mp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["councils-of-rome"],
      prompt: "How many ecumenical councils does the Roman Catholic Church count?",
      choices: [
        { id: "a", text: "Seven — agreeing with the Orthodox count from Nicaea I to Nicaea II.", rationale: "Wrong. The Orthodox count seven; Rome counts twenty-one, adding medieval Western councils and the two Vatican Councils." },
        { id: "b", text: "Fourteen — adding Trent and the medieval Western general councils only.", rationale: "Wrong. The number is twenty-one, not fourteen. Trent IS counted (as the 19th), but the Vatican Councils bring the total higher." },
        { id: "c", text: "Twenty-one — including the medieval Lateran/Lyon/Constance/Florence councils, Trent, and Vatican I & II.", rationale: "Catechism §884-885. Vatican II is reckoned as the 21st." },
        { id: "d", text: "Twenty-five — adding the Council of Constance (1414-1418) and the Synods of Pisa.", rationale: "Wrong. Constance IS the 16th in the Roman count; Pisa is not counted ecumenical. Total is twenty-one." },
      ],
      correctChoiceId: "c",
      citations: [{ source: "Catechism of the Catholic Church §§ 884-885" }],
    },
    {
      id: "rcc-mp-002",
      kind: "mcq",
      difficulty: 2,
      tags: ["pope-francis"],
      prompt: "Who was elected Pope on 13 March 2013?",
      choices: [
        { id: "a", text: "Benedict XVI (Joseph Ratzinger) — the German theologian and former prefect of the CDF.", rationale: "Wrong. Benedict was elected in 2005 and RESIGNED in February 2013. The 2013 conclave that followed his resignation elected Francis." },
        { id: "b", text: "Francis (Jorge Mario Bergoglio) — Argentine Jesuit, first pope from the Americas.", rationale: "Elected March 13, 2013 following Benedict XVI's resignation. The first non-European pope since Gregory III (731-741, Syrian)." },
        { id: "c", text: "John Paul II (Karol Wojtyła) — the Polish pope of the late 20th century.", rationale: "Wrong. JPII died in 2005, eight years before the 2013 conclave." },
        { id: "d", text: "Pius XII (Eugenio Pacelli) — the WWII-era pope.", rationale: "Wrong. Pius XII died in 1958." },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Habemus papam announcement, 13 March 2013" }],
    },
    {
      id: "rcc-mp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["trent"],
      prompt: "The Council of Trent (1545-1563) was convened primarily to:",
      choices: [
        { id: "a", text: "Define the Catholic position on Eastern reunion after Florence's failure of reception.", rationale: "Wrong. Trent's principal target was the Protestant Reformation, not the Eastern question (which Florence had already addressed)." },
        { id: "b", text: "Respond to the Protestant Reformation — defining the canon, justification, sacraments, the Mass, and indulgences.", rationale: "Twenty-five sessions over 18 years. Produced the Tridentine Profession of Faith and the Tridentine Missal (1570)." },
        { id: "c", text: "Define papal infallibility ex cathedra against Gallican and conciliarist tendencies.", rationale: "Wrong. Papal infallibility was defined at Vatican I (1870), three centuries after Trent." },
        { id: "d", text: "Reform the Mass into the vernacular and simplify the rite.", rationale: "Wrong. Trent did the OPPOSITE — it fixed the Latin Mass in the Tridentine form. Vernacular reform came at Vatican II (1969)." },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Acts of the Council of Trent (1545-1563)" }],
    },
    {
      id: "rcc-mp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["sacrament-of-confession"],
      prompt:
        "After Lateran IV (1215), what minimum yearly religious duty did Roman Catholic faithful have to satisfy?",
      choices: [
        { id: "a", text: "Annual confession to a priest plus reception of communion at Easter ('the Easter duty').", rationale: "Lateran IV (1215), canon 21 ('Omnis utriusque sexus'). The minimum has remained in Catholic canon law ever since (current CIC c. 989)." },
        { id: "b", text: "Annual tithe of one tenth of income to the parish, enforced by ecclesiastical court.", rationale: "Wrong. Tithing was a real medieval institution but not the specific Lateran IV minimum requirement." },
        { id: "c", text: "Pilgrimage to Rome at least once every seven years.", rationale: "Wrong. There was no such universal requirement; jubilee pilgrimages (from Boniface VIII in 1300) were voluntary." },
        { id: "d", text: "Daily recitation of the Rosary, codified at Lateran IV under Innocent III.", rationale: "Wrong. The Rosary developed in the 13th-15th c. but was never imposed as a universal requirement by Lateran IV." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Lateran IV (1215), canon 21" }],
    },
    {
      id: "rcc-mp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["vatican-i"],
      prompt: "Which dogma was definitively defined at Vatican I (1870) by Pope Pius IX?",
      choices: [
        { id: "a", text: "Papal infallibility ex cathedra (and papal universal jurisdiction).", rationale: "Defined in Pastor Aeternus, chapters 3 (jurisdiction) and 4 (infallibility). The decisive innovation rejected by Orthodoxy." },
        { id: "b", text: "The Immaculate Conception of the Theotokos.", rationale: "Wrong. The Immaculate Conception was defined in 1854 (Ineffabilis Deus), sixteen years before Vatican I." },
        { id: "c", text: "The Bodily Assumption of Mary.", rationale: "Wrong. The Assumption was defined in 1950 (Munificentissimus Deus), eighty years after Vatican I." },
        { id: "d", text: "Mary as Co-Redemptrix.", rationale: "Wrong. 'Co-redemptrix' is a Marian title petitioned for definition but never formally promulgated as dogma." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Vatican I, Pastor Aeternus (1870)" }],
    },
    {
      id: "rcc-mp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["latin-mass"],
      prompt: "When did the Roman Mass shift to the vernacular as the ordinary form?",
      choices: [
        { id: "a", text: "After Trent (1563), with the Tridentine Missal of Pius V (1570).", rationale: "Wrong. The Tridentine Missal FIXED the Latin Mass; the vernacular reform came centuries later." },
        { id: "b", text: "After Vatican II — with the Novus Ordo Missae of Paul VI (1969-70).", rationale: "Vatican II's Sacrosanctum Concilium (1963) opened the door; Paul VI's Missale Romanum (1969) implemented the New Order of the Mass." },
        { id: "c", text: "At Vatican I (1870), as part of the Italian unification reforms.", rationale: "Wrong. Vatican I addressed papal infallibility and ecclesiology, not the liturgy." },
        { id: "d", text: "After the Council of Florence (1439) for unity with the Greeks.", rationale: "Wrong. Florence ended unsuccessfully; the Latin Mass continued in Latin for another 500 years." },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Vatican II, Sacrosanctum Concilium (1963); Paul VI, Missale Romanum (1969)" }],
    },
    {
      id: "rcc-mp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["papal-states"],
      prompt: "When did the Pope cease to be a temporal monarch over the Papal States?",
      choices: [
        { id: "a", text: "1798 — when Napoleon's troops took Rome and proclaimed the Roman Republic.", rationale: "Wrong. Napoleon's occupation was temporary; the Papal States were restored at the Congress of Vienna (1815) and continued until 1870." },
        { id: "b", text: "1870 — Italian unification under Victor Emmanuel II annexed the Papal States.", rationale: "Pius IX retreated to the Vatican as 'Prisoner of the Vatican.' Resolved by the Lateran Treaty of 1929 creating Vatican City State." },
        { id: "c", text: "1929 — when the Lateran Treaty formally abolished papal temporal sovereignty.", rationale: "Wrong. The Lateran Treaty CREATED Vatican City and resolved the Roman Question — it didn't abolish papal sovereignty (Vatican City is itself a state)." },
        { id: "d", text: "1958 — at the death of Pius XII and the election of John XXIII.", rationale: "Wrong. The papal-states question was resolved decades before John XXIII." },
      ],
      correctChoiceId: "b",
      citations: [{ source: "Italian Unification (1870); Lateran Treaty (1929)" }],
    },
    {
      id: "rcc-mp-008",
      kind: "mcq",
      difficulty: 3,
      tags: ["sspx"],
      prompt: "Who was Marcel Lefebvre, and what movement did he lead?",
      choices: [
        { id: "a", text: "A French archbishop who rejected Vatican II's reforms and founded the Society of St. Pius X (SSPX) in 1970.", rationale: "Consecrated four bishops without papal permission in 1988 and was declared excommunicated. The status of SSPX remains in flux." },
        { id: "b", text: "A Spanish Dominican theologian who served as a peritus at Vatican II under Cardinal Ottaviani.", rationale: "Wrong. Lefebvre was French (a Holy Ghost Father), not Spanish or Dominican; he attended Vatican II but as a critic, not a peritus." },
        { id: "c", text: "A 19th-century Italian saint, founder of a missionary congregation in Africa.", rationale: "Wrong. Lefebvre IS associated with African missions (Senegal), but he is a 20th-c. archbishop, not a 19th-c. saint, and is not glorified." },
        { id: "d", text: "A founder of the Society of Jesus (Jesuits) in the 16th century.", rationale: "Wrong. The Society of Jesus was founded by Ignatius of Loyola in 1540, not by Lefebvre." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John Paul II, Ecclesia Dei (2 July 1988)" }],
    },
  ],
};

export const rcSpiritualityTopics: Topic = {
  id: "rcc-spirituality",
  title: "RC Spirituality — Distinctives",
  summary: "Rosary, Stations of the Cross, Sacred Heart, devotions to Mary, novenas — comparison with Orthodox practices.",
  learningObjectives: ["Note RC devotional distinctives.", "Compare with Orthodox practice."],
  primarySources: ["Catechism of the Catholic Church Part Four"],
  items: [
    {
      id: "rcc-sp-001",
      kind: "qa",
      difficulty: 3,
      tags: ["rosary"],
      prompt: "What is the Rosary, and is there an Orthodox equivalent?",
      expectedAnswer: "The Rosary is a Roman Catholic devotion: 15 (or 20 since John Paul II added the Luminous Mysteries in 2002) decades of Hail Marys, each decade preceded by an Our Father and followed by a Gloria, meditating on Joyful, Sorrowful, Glorious (and Luminous) Mysteries of Christ and the Virgin. Origin: traditionally attributed to St. Dominic (13th c.), though it developed organically. The Orthodox have the prayer rope (chotki / komboskini) — 50, 100, or 150 knots used with the Jesus Prayer, NOT with Marian repetitions. The akathist hymns to the Theotokos and to specific saints serve a function comparable to the Rosary's Marian meditation, but with a very different theological accent.",
      citations: [{ source: "Catechism of the Catholic Church §§ 2678, 2708" }],
    },
    {
      id: "rcc-sp-002",
      kind: "qa",
      difficulty: 3,
      tags: ["sacred-heart"],
      prompt: "What is the Sacred Heart devotion, and is it received in Orthodoxy?",
      expectedAnswer: "A Roman Catholic devotion that emerged in 17th-century France through the visions of Margaret Mary Alacoque (1647-90). The Sacred Heart of Jesus is depicted as a physical organ, often crowned with thorns and aflame, exposed outside His chest. The image is foreign to Orthodox iconography, which never depicts a body part in isolation. The Orthodox icon of Christ shows the whole Person (typically Christ Pantokrator, Christ the Good Shepherd, etc.). The Orthodox do not receive the Sacred Heart devotion; it represents a sentimental-physiological piety alien to the patristic tradition.",
      citations: [{ source: "Catechism of the Catholic Church § 2669; Margaret Mary Alacoque, Autobiography" }],
    },
    {
      id: "rcc-sp-003",
      kind: "qa",
      difficulty: 3,
      tags: ["stigmata"],
      prompt: "What are the stigmata, and how do Orthodoxy and Roman Catholicism differ on this phenomenon?",
      expectedAnswer: "Stigmata are bodily wounds (typically on hands, feet, side, brow) mirroring Christ's crucifixion wounds, claimed by certain Western mystics (Francis of Assisi 1224, Padre Pio 1918, Catherine of Siena, etc.). The Roman Catholic Church has recognized stigmata as a charism of identification with the suffering Christ. Orthodoxy regards this phenomenon as deeply suspect — a form of bodily mysticism foreign to the patristic tradition, often signaling spiritual delusion (prelest). The genuine union with the suffering Christ in Orthodox tradition is INTERIOR, manifested in tears of repentance and growing love, not in visible bodily wounds.",
      citations: [
        { source: "Ignatius Brianchaninov, On Prelest" },
        { source: "Bonaventure, Major Life of St. Francis 13" },
      ],
    },
    {
      id: "rcc-sp-004",
      kind: "qa",
      difficulty: 3,
      tags: ["fatima"],
      prompt: "What are the Marian apparitions at Fatima, and what is the Orthodox response?",
      expectedAnswer: "From May to October 1917, three Portuguese shepherd children (Lucia, Francisco, Jacinta) reported apparitions of the Virgin Mary at Fatima, Portugal, culminating in the 'Miracle of the Sun' on October 13. The Roman Catholic Church investigated and approved the apparitions in 1930. Three 'secrets' were communicated, the third only published in 2000. The Orthodox response: caution. We do not have a doctrine that rules out post-apostolic appearances of the Theotokos (many Orthodox saints have reported them), but the discernment of such phenomena belongs to the Church, and a confessionally Roman Catholic context is not the Orthodox sphere of discernment. Many Orthodox treat Fatima with theological reserve.",
      citations: [{ source: "Lucia dos Santos, Memoirs" }],
    },
  ],
};
