import type { Topic } from "@/lib/types";

export const dogmaFinalPack: Topic = {
  id: "dogma-final-pack",
  title: "Dogma — Final Pack",
  summary: "Final MCQs on dogmatic distinctions and terminology.",
  learningObjectives: ["Drill remaining vocabulary."],
  primarySources: ["Standard Orthodox dogmatic theology"],
  items: [
    {
      id: "dog-fin-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedonian-definition"],
      prompt:
        "The Definition of Chalcedon affirms Christ as one Person 'known in two natures' qualified by how many negative adverbs?",
      choices: [
        { id: "a", text: "Four — inconfusedly, unchangeably, indivisibly, inseparably.", rationale: "Two against confusion (asynchytōs, atreptōs); two against separation (adiairetōs, achōristōs). Aimed simultaneously at Eutyches and at Nestorius." },
        { id: "b", text: "Two — invisibly and indivisibly.", rationale: "Wrong. There are four adverbs of negation in the Chalcedonian Definition." },
        { id: "c", text: "Three — inconfusedly, indivisibly, and ineffably.", rationale: "Wrong. The fourth (inseparably) is essential to balance the third." },
        { id: "d", text: "Seven — one for each major heresy condemned at the Council.", rationale: "Wrong. There are four — two against monophysite confusion, two against Nestorian division." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Definition of Chalcedon (451)" }],
    },
    {
      id: "dog-fin-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["communicatio-idiomatum"],
      prompt: "What is the 'communicatio idiomatum'?",
      choices: [
        { id: "a", text: "The mutual exchange of properties between Christ's two natures, predicated of His one Person.", rationale: "We may say 'God was born' and 'God died' — because the subject is Christ's Person, in whom the natures are united. Cyril of Alexandria; John of Damascus, Exact Exposition III.3-4." },
        { id: "b", text: "The Roman canonical permission for the Pope to communicate with eastern patriarchs without local synodal consent.", rationale: "Wrong. The Latin phrase looks legal but is a Christological-theological term, not a canonical one." },
        { id: "c", text: "The sharing of sacraments (intercommunion) between separated Christian bodies.", rationale: "Wrong. Intercommunion is a modern ecumenical question; the communicatio idiomatum is a 5th-c. Christological doctrine." },
        { id: "d", text: "The early-Church practice of bishops carrying letters of communion (literae formatae) when traveling.", rationale: "Wrong — but literae formatae IS a real institution (carried by traveling clergy as proof of orthodoxy). Communicatio idiomatum is the Christological term." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Cyril of Alexandria, On the Unity of Christ; John of Damascus, Exact Exposition III.3-4" }],
    },
    {
      id: "dog-fin-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["perichoresis"],
      prompt: "What is 'perichoresis' in Trinitarian theology?",
      choices: [
        { id: "a", text: "The mutual interpenetration / co-inherence of the three Hypostases — they dwell in one another without confusion of Persons.", rationale: "John of Damascus, Exact Exposition I.8, 14. Each Person fully indwells the others; what one wills, all will." },
        { id: "b", text: "The eternal dance (perichoreuein) of the angels around the throne of God.", rationale: "Wrong. The term sounds like 'dancing around' (from chōreō 'to make room'), but it refers to the Trinitarian co-inherence, not angelic worship." },
        { id: "c", text: "A liturgical procession around the church during the Great Entrance of the Liturgy.", rationale: "Wrong. The Great Entrance and other processions are real liturgical actions, but the technical term perichoresis is reserved for Trinitarian theology." },
        { id: "d", text: "The Eucharistic real presence — Christ's penetration of the bread and wine.", rationale: "Wrong. Eucharistic presence is metabole or metousiōsis; perichoresis is the Trinitarian co-inherence." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John of Damascus, Exact Exposition I.8, 14" }],
    },
    {
      id: "dog-fin-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["kenosis"],
      prompt: "What is 'kenosis' in Christology?",
      choices: [
        { id: "a", text: "The self-emptying of Christ in the Incarnation — He, being in the form of God, took the form of a servant.", rationale: "Philippians 2:5-11. The kenotic hymn is the locus classicus. Orthodox tradition reads it as voluntary self-humbling without diminution of divinity." },
        { id: "b", text: "The eternal procession of the Holy Spirit from the Father.", rationale: "Wrong. That is EKPOREUSIS (procession), a Trinitarian term — distinct from kenosis (Christological self-emptying)." },
        { id: "c", text: "The veneration of icons through prostration and kissing.", rationale: "Wrong. That is proskynesis, not kenosis." },
        { id: "d", text: "The Lenten practice of emptying the soul through fasting and prayer.", rationale: "Wrong. Lenten fasting is a real spiritual practice, but kenosis specifically describes Christ's Incarnation." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philippians 2:5-11" }],
    },
    {
      id: "dog-fin-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["anaphora"],
      prompt: "What is the Anaphora in the Divine Liturgy?",
      choices: [
        { id: "a", text: "The central Eucharistic prayer — from the Dialogue ('Lift up your hearts') through Sanctus, Words of Institution, Anamnesis, Epiclesis, Intercessions, and final Doxology.", rationale: "Greek anaphorā 'a lifting up.' The high point of the Liturgy of the Faithful. Different anaphorae for Liturgies of Chrysostom, Basil, James, Mark." },
        { id: "b", text: "The morning office of prayer sung at sunrise before the Liturgy (Orthros / Matins).", rationale: "Wrong. Orthros is the daily-cycle morning office; the Anaphora is the Eucharistic prayer at the heart of the Liturgy." },
        { id: "c", text: "The Lenten penitential canon attributed to St. Andrew of Crete.", rationale: "Wrong. The Great Canon of St. Andrew is a real penitential canon (8th c.), chanted in Lent — but it is not the Anaphora." },
        { id: "d", text: "A type of priestly vestment worn during the Eucharist.", rationale: "Wrong. Priestly vestments include sticharion, epitrachelion, zone, phelonion — but no 'anaphora' vestment exists." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Anaphora of St. John Chrysostom" }],
    },
    {
      id: "dog-fin-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["dianoia-nous"],
      prompt: "What is the distinction between dianoia and nous in Orthodox anthropology?",
      choices: [
        { id: "a", text: "Dianoia is discursive reasoning (step-by-step thinking); nous is the soul's direct intuitive faculty for knowing God.", rationale: "Distinction goes back to Plato; given Christian content by the Cappadocians and Maximus. The Philokalic Glossary is the standard summary." },
        { id: "b", text: "Dianoia and nous are synonymous Greek terms for the same faculty.", rationale: "Wrong. The two terms are carefully distinguished in patristic and Philokalic literature." },
        { id: "c", text: "Dianoia is heavenly knowledge (post-resurrection); nous is earthly reasoning (this life).", rationale: "Wrong. Both belong to the soul as we know it now; both are healed and elevated by theosis." },
        { id: "d", text: "Nous belongs to angelic beings alone; dianoia is human.", rationale: "Wrong. The nous belongs to the human soul (made in the image of God). Patristic anthropology uses these as faculties of one human soul." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philokalia, Glossary — entries 'Nous' and 'Dianoia'" }],
    },
    {
      id: "dog-fin-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["hesychasm"],
      prompt: "What is hesychasm?",
      choices: [
        { id: "a", text: "The Orthodox monastic and lay tradition of inner stillness (hesychia), continual Jesus Prayer, and the descent of the nous into the heart.", rationale: "Vindicated by St. Gregory Palamas at the Hesychast Councils of Constantinople (1341, 1347, 1351). Roots earlier — Evagrius, Diadochos, Symeon the New Theologian." },
        { id: "b", text: "A medieval Western mystical movement centered on the Rhine cities (Eckhart, Tauler, Suso).", rationale: "Wrong. Rhineland mysticism is real but Western Latin; hesychasm is Eastern Orthodox." },
        { id: "c", text: "A theological school of Byzantine philosophy that synthesized Plato with Trinitarian theology.", rationale: "Wrong. That would describe John Italos and 11th-c. Constantinopolitan philosophy (which was condemned). Hesychasm is a spiritual-ascetical tradition, not a philosophical school." },
        { id: "d", text: "A type of Liturgy used on Athonite monasteries during Lent.", rationale: "Wrong. The Athonite typikon DOES govern Lenten Liturgies, but hesychasm is the broader spiritual-ascetical practice, not a Liturgy." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "St. Gregory Palamas, Triads in Defense of the Holy Hesychasts; Synodal Tome of 1351" }],
    },
  ],
};
