import type { Topic } from "@/lib/types";

export const dogmaFinalPack: Topic = {
  id: "dogma-final-pack",
  title: "Dogma — Final Pack",
  summary: "Final MCQs on dogmatic distinctions and terminology.",
  learningObjectives: ["Drill remaining vocabulary."],
  primarySources: ["Standard Orthodox dogmatic theology"],
  items: [
    {
      id: "dog-fin-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["chalcedonian-definition"],
      prompt: "The Definition of Chalcedon affirms that Christ is one Person 'made known in two natures' with how many adverbs of negation?",
      choices: [
        { id: "a", text: "Four: inconfusedly, unchangeably, indivisibly, inseparably.", rationale: "Correct." },
        { id: "b", text: "Two" },
        { id: "c", text: "Three" },
        { id: "d", text: "Seven" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Definition of Chalcedon (451)" }],
    },
    {
      id: "dog-fin-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["communicatio-idiomatum"],
      prompt: "What is the 'communicatio idiomatum'?",
      choices: [
        { id: "a", text: "The mutual exchange of properties between Christ's two natures: we may say God was born, God died — because these are predicated of His Person, in whom the natures are united.", rationale: "Correct." },
        { id: "b", text: "Exchange of letters between bishops" },
        { id: "c", text: "Sacramental sharing between churches" },
        { id: "d", text: "The Eucharistic distribution" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Cyril of Alexandria, On the Unity of Christ; John of Damascus, Exact Exposition III.3-4" }],
    },
    {
      id: "dog-fin-003",
      kind: "mcq",
      difficulty: 4,
      tags: ["perichoresis"],
      prompt: "What is 'perichoresis' (περιχώρησις) in Trinitarian theology?",
      choices: [
        { id: "a", text: "The mutual interpenetration of the three Hypostases — they dwell in one another without confusion. From John of Damascus.", rationale: "Correct." },
        { id: "b", text: "The dance of the angels around God" },
        { id: "c", text: "A liturgical procession" },
        { id: "d", text: "The Eucharistic real presence" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John of Damascus, Exact Exposition I.8, 14" }],
    },
    {
      id: "dog-fin-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["kenosis"],
      prompt: "What is 'kenosis' in Christology?",
      choices: [
        { id: "a", text: "The self-emptying of Christ in the Incarnation — He, being in the form of God, made Himself of no reputation (Phil 2:5-8). He took the form of a servant.", rationale: "Correct." },
        { id: "b", text: "The procession of the Spirit" },
        { id: "c", text: "The veneration of icons" },
        { id: "d", text: "A fasting practice" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philippians 2:5-11" }],
    },
    {
      id: "dog-fin-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["anaphora"],
      prompt: "What is the Anaphora?",
      choices: [
        { id: "a", text: "The central Eucharistic prayer of the Divine Liturgy — from the Dialogue ('Let us lift up our hearts') through the Sanctus, Words of Institution, Anamnesis, Epiclesis, Intercessions, and Doxology.", rationale: "Correct." },
        { id: "b", text: "The morning prayer service" },
        { id: "c", text: "The penitential canon" },
        { id: "d", text: "A type of vestment" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Hieratikon — Anaphora of St. John Chrysostom" }],
    },
    {
      id: "dog-fin-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["dianoia-nous"],
      prompt: "What is the distinction between dianoia and nous in Orthodox anthropology?",
      choices: [
        { id: "a", text: "Dianoia is discursive reasoning (the brain working step by step); nous is the soul's direct intuitive faculty for knowing God.", rationale: "Correct." },
        { id: "b", text: "They are synonymous" },
        { id: "c", text: "Dianoia is heavenly, nous earthly" },
        { id: "d", text: "Nous belongs to angels alone" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philokalia, Glossary — entries 'Nous' and 'Dianoia'" }],
    },
    {
      id: "dog-fin-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["hesychasm"],
      prompt: "What is hesychasm?",
      choices: [
        { id: "a", text: "The Orthodox monastic and lay tradition of inner stillness (hesychia), continual Jesus Prayer, and the descent of the nous into the heart. Defended by Palamas at Constantinople (1341-51).", rationale: "Correct." },
        { id: "b", text: "A medieval Western mystical sect" },
        { id: "c", text: "A theological school" },
        { id: "d", text: "A type of liturgy" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Gregory Palamas, Triads in Defense of the Holy Hesychasts" }],
    },
  ],
};
