import type { Topic } from "@/lib/types";

export const dogmaFactsPack: Topic = {
  id: "dogma-facts-pack",
  title: "Dogma — Quick Recall",
  summary: "MCQ pack on dogmatic distinctions.",
  learningObjectives: ["Drill terminology and major distinctions."],
  primarySources: ["Symbol of Faith; Cappadocian and Palamite writings"],
  items: [
    {
      id: "dog-fp-001",
      kind: "mcq",
      difficulty: 2,
      tags: ["dogma-vs-theologoumenon"],
      prompt: "What is the distinction between dogma and theologoumenon?",
      choices: [
        { id: "a", text: "Dogma is binding teaching defined by the Church (Councils, Symbol); theologoumenon is a pious theological opinion held by some Fathers but not dogmatized.", rationale: "Correct. E.g., the soul's immediate journey to heaven/hell is theologoumenon territory; the Resurrection of the body is dogma." },
        { id: "b", text: "They are synonyms" },
        { id: "c", text: "Dogma is Roman Catholic, theologoumenon is Orthodox" },
        { id: "d", text: "Dogma is biblical, theologoumenon is patristic" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Vladimir Lossky, Mystical Theology of the Eastern Church" }],
    },
    {
      id: "dog-fp-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["seven-councils"],
      prompt: "What is the conciliar basis of Orthodox dogma?",
      choices: [
        { id: "a", text: "The Seven Ecumenical Councils — their dogmatic definitions and canons.", rationale: "Correct." },
        { id: "b", text: "Roman papal pronouncements" },
        { id: "c", text: "The Westminster Confession" },
        { id: "d", text: "The personal judgment of bishops" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "The Seven Ecumenical Councils" }],
    },
    {
      id: "dog-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["panagia"],
      prompt: "What does the Greek title 'Panagia' mean (used for the Theotokos)?",
      choices: [
        { id: "a", text: "All-Holy", rationale: "Correct." },
        { id: "b", text: "Ever-Virgin" },
        { id: "c", text: "Queen of Heaven" },
        { id: "d", text: "Mother of God" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Liturgical usage; Akathist Hymn" }],
    },
    {
      id: "dog-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["aeiparthenos"],
      prompt: "What does 'Aeiparthenos' mean?",
      choices: [
        { id: "a", text: "Ever-Virgin", rationale: "Correct. The Theotokos: before, during, and after the birth of Christ." },
        { id: "b", text: "All-Holy" },
        { id: "c", text: "Mother of God" },
        { id: "d", text: "Queen of Heaven" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople II (553)" }],
    },
    {
      id: "dog-fp-005",
      kind: "mcq",
      difficulty: 3,
      tags: ["latreia-proskynesis"],
      prompt: "Distinguish proskynesis from latreia.",
      choices: [
        { id: "a", text: "Proskynesis is veneration / honor (due to icons, saints, the Cross); latreia is worship/adoration (due to God alone).", rationale: "Correct. Defined at Nicaea II." },
        { id: "b", text: "They are synonyms" },
        { id: "c", text: "Latreia is for Mary alone" },
        { id: "d", text: "Proskynesis is monastic" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Definition of Nicaea II (787)" }],
    },
    {
      id: "dog-fp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["nous"],
      prompt: "In Orthodox spiritual anthropology, what is the 'nous'?",
      choices: [
        { id: "a", text: "The highest faculty of the soul — the eye of the heart, by which one knows God directly.", rationale: "Correct. Distinct from discursive reasoning (dianoia)." },
        { id: "b", text: "The intellect in the sense of reasoning" },
        { id: "c", text: "The emotions" },
        { id: "d", text: "The body's brain alone" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philokalia, Glossary entry 'Nous'" }],
    },
    {
      id: "dog-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["prelest"],
      prompt: "What is 'prelest' (Russian) / 'plani' (Greek) in Orthodox spiritual literature?",
      choices: [
        { id: "a", text: "Spiritual delusion — taking demonic or pridefully-self-generated experiences for the genuine action of God.", rationale: "Correct." },
        { id: "b", text: "Mortal sin" },
        { id: "c", text: "Heresy" },
        { id: "d", text: "Apostasy" },
      ],
      correctChoiceId: "a",
      citations: [
        { source: "Ignatius Brianchaninov, On Prelest" },
        { source: "Various Athonite writings" },
      ],
    },
    {
      id: "dog-fp-008",
      kind: "mcq",
      difficulty: 4,
      tags: ["filioque-eo"],
      prompt: "What is the Orthodox position on the Holy Spirit's eternal procession?",
      choices: [
        { id: "a", text: "From the Father alone (ekporeusis), per Jn 15:26 and the Symbol of Faith.", rationale: "Correct. The temporal mission (pempsis) is through the Son." },
        { id: "b", text: "From the Father and the Son (Filioque)" },
        { id: "c", text: "From the Son alone" },
        { id: "d", text: "From the Theotokos" },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 15:26; Symbol of Constantinople (381)" }],
    },
  ],
};
