import type { Topic } from "@/lib/types";

export const dogmaFactsPack: Topic = {
  id: "dogma-facts-pack",
  title: "Dogma — Quick Recall",
  summary: "MCQ pack on dogmatic distinctions.",
  learningObjectives: ["Drill terminology and major distinctions."],
  primarySources: ["Symbol of Faith; Cappadocian and Palamite writings"],
  items: [
    {
      id: "dog-fp-001",
      kind: "mcq",
      difficulty: 3,
      tags: ["dogma-vs-theologoumenon"],
      prompt: "How does the Orthodox tradition distinguish dogma from theologoumenon?",
      choices: [
        { id: "a", text: "Dogma is binding teaching defined by the Church (in Council or Symbol); theologoumenon is a pious opinion held by Fathers but not formally dogmatized.", rationale: "The aerial toll-houses, the precise nature of the soul's intermediate state, the question of Mary's death — these are theologoumena. The Resurrection of the body is dogma." },
        { id: "b", text: "Dogma is the Greek-Father position; theologoumenon is the Latin-Father position on the same question.", rationale: "Wrong. The distinction is not about East vs. West but about defined teaching vs. pious opinion." },
        { id: "c", text: "Dogma is binding in Roman Catholicism; theologoumenon is the equivalent Orthodox concept.", rationale: "Wrong. Both terms ARE used in Catholic theology, but they describe two different levels of authority within ONE tradition, not parallel traditions." },
        { id: "d", text: "Dogma is found in Scripture alone; theologoumenon is what the Fathers add by reflection.", rationale: "Wrong. The Symbol of Faith, the conciliar definitions, and the Fathers all contribute to dogma; theologoumena are unsettled opinions within the broader Tradition." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Vladimir Lossky, Mystical Theology of the Eastern Church" }],
    },
    {
      id: "dog-fp-002",
      kind: "mcq",
      difficulty: 3,
      tags: ["seven-councils"],
      prompt: "What is the conciliar foundation of Orthodox dogma?",
      choices: [
        { id: "a", text: "The Seven Ecumenical Councils — their dogmatic definitions and binding canons.", rationale: "Plus the Photian (879-80) and Hesychast (1341-51) councils, received as ecumenical in force by many Orthodox." },
        { id: "b", text: "The continuous papal magisterium of the See of Rome since Peter.", rationale: "Wrong. That is the Roman Catholic understanding; Orthodoxy locates authority in conciliar consensus, not in a single see." },
        { id: "c", text: "The Westminster Confession of Faith and the Helvetic Confessions of the 17th century.", rationale: "Wrong. Those are Reformed Protestant confessions, not Orthodox sources." },
        { id: "d", text: "The personal interpretation of Scripture by individual bishops in their own dioceses.", rationale: "Wrong. Orthodoxy requires conciliar (not individual) authority for binding teaching." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "The Seven Ecumenical Councils; Confession of Dositheus (1672)" }],
    },
    {
      id: "dog-fp-003",
      kind: "mcq",
      difficulty: 3,
      tags: ["panagia"],
      prompt: "What does the Greek title 'Panagia' mean, as used for the Theotokos?",
      choices: [
        { id: "a", text: "All-Holy — from pan (all) + hagia (holy).", rationale: "Used throughout the liturgy; expresses the Orthodox confession of Mary's holiness without committing to the Roman dogma of Immaculate Conception." },
        { id: "b", text: "Ever-Virgin — from pan (always) + parthenos (virgin).", rationale: "Wrong. That is AEIPARTHENOS, a different Marian title (Constantinople II, 553)." },
        { id: "c", text: "Queen of Heaven — from pan (all) + basileia (kingdom).", rationale: "Wrong. The Greek would be something like Vasilissa tou Ouranou; Panagia means All-Holy." },
        { id: "d", text: "Mother of God — equivalent to Theotokos (Ephesus 431).", rationale: "Wrong. Mother of God is THEOTOKOS (literally God-bearer); Panagia is a separate honorific." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Liturgical usage (Greek Orthodox); Akathist Hymn" }],
    },
    {
      id: "dog-fp-004",
      kind: "mcq",
      difficulty: 3,
      tags: ["aeiparthenos"],
      prompt: "What does the Greek title 'Aeiparthenos' mean, as used for the Theotokos?",
      choices: [
        { id: "a", text: "Ever-Virgin — virgin before, during, and after the birth of Christ.", rationale: "Conciliar at Constantinople II (553). Same confession in the early Reformers (Luther, Calvin)." },
        { id: "b", text: "All-Holy — equivalent to the title Panagia used in liturgy.", rationale: "Wrong. All-Holy is PANAGIA, a different title." },
        { id: "c", text: "Mother of God — equivalent to Theotokos (Ephesus 431).", rationale: "Wrong. Mother of God is THEOTOKOS; Aeiparthenos refers to perpetual virginity." },
        { id: "d", text: "Queen of Heaven — Mary's eschatological role.", rationale: "Wrong. Aeiparthenos addresses her virginity, not her queenly title." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Acts of Constantinople II (553)" }],
    },
    {
      id: "dog-fp-005",
      kind: "mcq",
      difficulty: 4,
      tags: ["latreia-proskynesis"],
      prompt: "How does the Orthodox tradition distinguish proskynesis from latreia?",
      choices: [
        { id: "a", text: "Proskynesis is veneration / honor (due to icons, saints, the Cross); latreia is worship / adoration (due to God alone).", rationale: "Conciliarly defined at Nicaea II (787). The distinction underlies the rejection of iconoclasm: kissing an icon is proskynesis, not latreia." },
        { id: "b", text: "Proskynesis is bowing of the body; latreia is interior worship of the heart.", rationale: "Wrong. The distinction is about the OBJECT of honor (creature vs. God), not the bodily mode." },
        { id: "c", text: "Proskynesis is private devotion; latreia is public liturgy.", rationale: "Wrong. Both have public and private expressions; the distinction is creaturely honor vs. divine worship." },
        { id: "d", text: "Proskynesis is reserved for the Theotokos alone; latreia is for the Trinity.", rationale: "Wrong. Proskynesis is given to all saints and icons; the Theotokos receives hyperdoulia (special veneration) above other saints but still proskynesis." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Definition of Nicaea II (787)" }],
    },
    {
      id: "dog-fp-006",
      kind: "mcq",
      difficulty: 4,
      tags: ["nous"],
      prompt: "In Orthodox spiritual anthropology, what is the 'nous'?",
      choices: [
        { id: "a", text: "The highest faculty of the soul — the 'eye of the heart' by which one knows God directly, distinct from discursive reasoning.", rationale: "Distinguished from dianoia (discursive reason). The Fall darkens the nous; theosis is its illumination by the uncreated Light." },
        { id: "b", text: "The intellect in the modern sense of analytical reasoning, equivalent to Latin ratio.", rationale: "Wrong. Latin ratio corresponds more to dianoia (discursive reason); nous is the higher noetic faculty." },
        { id: "c", text: "The emotions and affective life, the seat of the passions.", rationale: "Wrong. The passions belong to the disordered movements of the soul, not to the nous itself." },
        { id: "d", text: "The biological brain — equivalent to the modern neuroscientific category.", rationale: "Wrong. Orthodox anthropology distinguishes nous (a faculty of the soul) from the bodily brain." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "Philokalia, Glossary entry 'Nous'" }],
    },
    {
      id: "dog-fp-007",
      kind: "mcq",
      difficulty: 4,
      tags: ["prelest"],
      prompt: "What is 'prelest' (Russian) / 'plani' (Greek) in Orthodox spiritual literature?",
      choices: [
        { id: "a", text: "Spiritual delusion — taking demonic or self-generated experiences for the genuine action of God.", rationale: "Often manifests as premature claims to visions, miraculous gifts, or spiritual maturity. Brianchaninov's On Prelest is the classic Russian treatment." },
        { id: "b", text: "Mortal sin — a grave act that severs the soul from divine grace.", rationale: "Wrong. Mortal sin is a separate category (closer to the Latin distinction); prelest is specifically spiritual self-deception." },
        { id: "c", text: "Doctrinal heresy as defined by the seven Ecumenical Councils.", rationale: "Wrong. Heresy is a doctrinal category; prelest is a spiritual-psychological one (though they can interact)." },
        { id: "d", text: "Apostasy — formal renunciation of the Christian faith after baptism.", rationale: "Wrong. Apostasy is a canonical category for formal abandonment of the faith; prelest is internal self-deception." },
      ],
      correctChoiceId: "a",
      citations: [
        { source: "Ignatius Brianchaninov, On Prelest" },
        { source: "Various Athonite spiritual writings" },
      ],
    },
    {
      id: "dog-fp-008",
      kind: "mcq",
      difficulty: 4,
      tags: ["filioque-eo"],
      prompt: "What is the Orthodox position on the eternal procession of the Holy Spirit?",
      choices: [
        { id: "a", text: "From the Father alone (ekporeusis), per John 15:26 and the original Symbol of Faith (381).", rationale: "The Son's role is in the temporal mission (pempsis), not the eternal procession. Ephesus canon 7 forbade additions to the Symbol." },
        { id: "b", text: "From the Father and the Son (Filioque) as a single principle, as defined at Lyon II (1274) and Florence (1439).", rationale: "Wrong. This is the LATIN position rejected by Orthodoxy; Lyon and Florence are not received as ecumenical by the East." },
        { id: "c", text: "From the Son alone, with the Father acting only through the Son as agent.", rationale: "Wrong. No tradition has taught this; it would be incoherent with the monarchy of the Father." },
        { id: "d", text: "From the Father through the Son (dia tou Yiou), as a synthesis position between East and West.", rationale: "Wrong, although DIA TOU YIOU IS a real patristic phrase (Cyril, Maximus) for the temporal mission of the Spirit. As ETERNAL procession, the Orthodox confess from the FATHER ALONE." },
      ],
      correctChoiceId: "a",
      citations: [{ source: "John 15:26; Symbol of Constantinople (381); Photios, Mystagogy" }],
    },
  ],
};
